CREATE TABLE IF NOT EXISTS `logical_store` (
    `id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `manager_user_id` BIGINT DEFAULT NULL,
    `project_code` VARCHAR(100) NOT NULL,
    `project_name` VARCHAR(200) DEFAULT NULL,
    `status` VARCHAR(30) DEFAULT 'ACTIVE',
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logical_store_owner_project` (`owner_user_id`, `project_code`),
    KEY `idx_logical_store_project_code` (`project_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `product_management_id_sequence` (
    `sequence_name` VARCHAR(80) NOT NULL,
    `next_id` BIGINT NOT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`sequence_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `logical_store_site` (
    `id` BIGINT NOT NULL,
    `logical_store_id` BIGINT NOT NULL,
    `store_code` VARCHAR(100) NOT NULL,
    `site` VARCHAR(20) NOT NULL,
    `is_reference_site` BIT(1) DEFAULT b'0',
    `is_mounted` BIT(1) DEFAULT b'1',
    `site_status` VARCHAR(30) DEFAULT NULL,
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logical_store_site_store_code` (`store_code`),
    UNIQUE KEY `uk_logical_store_site_logical_site` (`logical_store_id`, `site`),
    KEY `idx_logical_store_site_logical_store_id` (`logical_store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `product_master` (
    `id` BIGINT NOT NULL,
    `logical_store_id` BIGINT NOT NULL,
    `sku_parent` VARCHAR(100) NOT NULL,
    `brand_cache` VARCHAR(200) DEFAULT NULL,
    `title_cache` VARCHAR(500) DEFAULT NULL,
    `title_cn_cache` VARCHAR(500) DEFAULT NULL,
    `product_fulltype_cache` VARCHAR(200) DEFAULT NULL,
    `cover_image_url` VARCHAR(1000) DEFAULT NULL,
    `group_ref` VARCHAR(200) DEFAULT NULL,
    `group_member_count` INT DEFAULT NULL,
    `variant_count_cache` INT DEFAULT NULL,
    `sync_status` VARCHAR(30) DEFAULT 'synced',
    `last_synced_at` DATETIME DEFAULT NULL,
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_master_store_sku_parent` (`logical_store_id`, `sku_parent`),
    KEY `idx_product_master_sync_status` (`sync_status`),
    KEY `idx_product_master_title_cn_cache` (`title_cn_cache`(191)),
    KEY `idx_product_master_last_synced_at` (`last_synced_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `product_variant` (
    `id` BIGINT NOT NULL,
    `product_master_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT NOT NULL,
    `child_sku` VARCHAR(100) DEFAULT NULL,
    `partner_sku` VARCHAR(100) NOT NULL,
    `size_en` VARCHAR(200) DEFAULT NULL,
    `size_ar` VARCHAR(200) DEFAULT NULL,
    `variant_ix` INT DEFAULT NULL,
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_variant_store_partner_sku` (`logical_store_id`, `partner_sku`),
    UNIQUE KEY `uk_product_variant_master_child_sku` (`product_master_id`, `child_sku`),
    KEY `idx_product_variant_product_master_id` (`product_master_id`),
    KEY `idx_product_variant_store_id` (`logical_store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `product_barcode` (
    `id` BIGINT NOT NULL,
    `variant_id` BIGINT NOT NULL,
    `barcode` VARCHAR(100) NOT NULL,
    `barcode_type` VARCHAR(50) DEFAULT NULL,
    `is_primary` BIT(1) DEFAULT b'0',
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_barcode_barcode` (`barcode`),
    KEY `idx_product_barcode_variant_id` (`variant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `product_site_offer` (
    `id` BIGINT NOT NULL,
    `variant_id` BIGINT NOT NULL,
    `site_id` BIGINT NOT NULL,
    `psku_code` VARCHAR(100) DEFAULT NULL,
    `offer_code` VARCHAR(100) DEFAULT NULL,
    `price` DECIMAL(12,2) DEFAULT NULL,
    `sale_price` DECIMAL(12,2) DEFAULT NULL,
    `sale_start` DATETIME DEFAULT NULL,
    `sale_end` DATETIME DEFAULT NULL,
    `price_min` DECIMAL(12,2) DEFAULT NULL,
    `price_max` DECIMAL(12,2) DEFAULT NULL,
    `pricing_method` VARCHAR(40) DEFAULT 'manual',
    `pricing_rule` VARCHAR(80) DEFAULT NULL,
    `price_engine_min` DECIMAL(12,2) DEFAULT NULL,
    `price_engine_max` DECIMAL(12,2) DEFAULT NULL,
    `id_warranty` INT DEFAULT NULL,
    `offer_note` VARCHAR(500) DEFAULT NULL,
    `is_active` BIT(1) DEFAULT NULL,
    `live_status` VARCHAR(50) DEFAULT NULL,
    `status_code` VARCHAR(50) DEFAULT NULL,
    `fbn_stock` INT DEFAULT NULL,
    `supermall_stock` INT DEFAULT NULL,
    `fbp_stock` INT DEFAULT NULL,
    `last_synced_at` DATETIME DEFAULT NULL,
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_site_offer_variant_site` (`variant_id`, `site_id`),
    UNIQUE KEY `uk_product_site_offer_site_psku` (`site_id`, `psku_code`),
    UNIQUE KEY `uk_product_site_offer_site_offer_code` (`site_id`, `offer_code`),
    KEY `idx_product_site_offer_variant_id` (`variant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `product_master_snapshot` (
    `id` BIGINT NOT NULL,
    `product_master_id` BIGINT NOT NULL,
    `snapshot_type` VARCHAR(30) NOT NULL,
    `snapshot_hash` VARCHAR(128) DEFAULT NULL,
    `snapshot_json` LONGTEXT NOT NULL,
    `fetched_at` DATETIME NOT NULL,
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_product_master_snapshot_master_type` (`product_master_id`, `snapshot_type`),
    KEY `idx_product_master_snapshot_hash` (`product_master_id`, `snapshot_type`, `snapshot_hash`),
    KEY `idx_product_master_snapshot_fetched_at` (`fetched_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `product_master_draft` (
    `id` BIGINT NOT NULL,
    `product_master_id` BIGINT NOT NULL,
    `baseline_snapshot_id` BIGINT NOT NULL,
    `version_no` INT NOT NULL DEFAULT 1,
    `dirty_site_codes_json` LONGTEXT DEFAULT NULL,
    `draft_json` LONGTEXT NOT NULL,
    `saved_at` DATETIME NOT NULL,
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_master_draft_master` (`product_master_id`),
    KEY `idx_product_master_draft_baseline_snapshot_id` (`baseline_snapshot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `product_action_log` (
    `id` BIGINT NOT NULL,
    `product_master_id` BIGINT NOT NULL,
    `baseline_snapshot_id` BIGINT DEFAULT NULL,
    `target_site_id` BIGINT DEFAULT NULL,
    `target_variant_id` BIGINT DEFAULT NULL,
    `action_type` VARCHAR(50) NOT NULL,
    `stage` VARCHAR(50) DEFAULT NULL,
    `result_status` VARCHAR(30) NOT NULL,
    `error_code` VARCHAR(100) DEFAULT NULL,
    `psku_code` VARCHAR(100) DEFAULT NULL,
    `offer_code` VARCHAR(100) DEFAULT NULL,
    `retry_count` INT NOT NULL DEFAULT 0,
    `summary_json` LONGTEXT DEFAULT NULL,
    `occurred_at` DATETIME NOT NULL,
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_product_action_log_master_time` (`product_master_id`, `occurred_at`),
    KEY `idx_product_action_log_target_site_id` (`target_site_id`),
    KEY `idx_product_action_log_target_variant_id` (`target_variant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `product_key_content_history` (
    `id` BIGINT NOT NULL,
    `product_master_id` BIGINT NOT NULL,
    `baseline_snapshot_id` BIGINT DEFAULT NULL,
    `target_site_id` BIGINT DEFAULT NULL,
    `source_action_type` VARCHAR(50) NOT NULL,
    `visibility_status` VARCHAR(30) NOT NULL DEFAULT 'pending',
    `change_types_json` LONGTEXT NOT NULL,
    `summary_json` LONGTEXT NOT NULL,
    `published_at` DATETIME NOT NULL,
    `visible_after` DATETIME NOT NULL,
    `visible_at` DATETIME DEFAULT NULL,
    `is_deleted` BIT(1) DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_product_key_content_history_master_time` (`product_master_id`, `published_at`),
    KEY `idx_product_key_content_history_visibility` (`visibility_status`, `visible_after`),
    KEY `idx_product_key_content_history_target_site_id` (`target_site_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
