-- Nuono Next manual product-selection source collection.
-- Scope: keep only the source collection records used by the manual selection UI.

CREATE TABLE IF NOT EXISTS `product_selection_source_collection` (
    `id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT NOT NULL,
    `collection_no` VARCHAR(60) NOT NULL,
    `source_type` VARCHAR(30) NOT NULL DEFAULT 'image-search-source',
    `source_platform` VARCHAR(80) DEFAULT NULL,
    `source_url` VARCHAR(1000) DEFAULT NULL,
    `page_url` VARCHAR(1000) DEFAULT NULL,
    `source_title` VARCHAR(500) DEFAULT NULL,
    `source_title_cn` VARCHAR(500) DEFAULT NULL,
    `source_title_ar` VARCHAR(500) DEFAULT NULL,
    `source_image_url` VARCHAR(1000) DEFAULT NULL,
    `image_urls_json` TEXT DEFAULT NULL,
    `price_summary` VARCHAR(300) DEFAULT NULL,
    `moq_hint` VARCHAR(200) DEFAULT NULL,
    `shipping_from` VARCHAR(200) DEFAULT NULL,
    `brand_name` VARCHAR(200) DEFAULT NULL,
    `unit_count` VARCHAR(100) DEFAULT NULL,
    `color_name` VARCHAR(200) DEFAULT NULL,
    `spec_hints_json` TEXT DEFAULT NULL,
    `spec_attribute_count` INT NOT NULL DEFAULT 0,
    `source_description_en` TEXT DEFAULT NULL,
    `source_description_ar` TEXT DEFAULT NULL,
    `source_selling_points_en_json` TEXT DEFAULT NULL,
    `source_selling_points_ar_json` TEXT DEFAULT NULL,
    `selected_text` VARCHAR(2000) DEFAULT NULL,
    `selected_text_ar` VARCHAR(2000) DEFAULT NULL,
    `notes` VARCHAR(1000) DEFAULT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'success',
    `failure_code` VARCHAR(80) DEFAULT NULL,
    `failure_message` VARCHAR(500) DEFAULT NULL,
    `locked_at` DATETIME DEFAULT NULL,
    `locked_by` VARCHAR(120) DEFAULT NULL,
    `attempt_count` INT NOT NULL DEFAULT 0,
    `collected_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_selection_source_collection_no` (`collection_no`),
    KEY `idx_product_selection_source_store` (`logical_store_id`, `collected_at`),
    KEY `idx_product_selection_source_status` (`status`),
    KEY `idx_product_selection_source_claim` (`status`, `source_type`, `locked_at`, `collected_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `product_selection_source_collection` MODIFY COLUMN `status` VARCHAR(30) NOT NULL DEFAULT 'success';
