-- Noon data completeness ledger and gap patrol.

CREATE TABLE IF NOT EXISTS `noon_data_completeness` (
    `id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `store_code` VARCHAR(100) NOT NULL,
    `site_code` VARCHAR(32) NOT NULL,
    `data_category` VARCHAR(64) NOT NULL,
    `latest_status` VARCHAR(64) NOT NULL,
    `history_status` VARCHAR(64) NOT NULL,
    `latest_data_date` DATE DEFAULT NULL,
    `history_covered_from` DATE DEFAULT NULL,
    `history_covered_to` DATE DEFAULT NULL,
    `patrol_enabled` BIT(1) NOT NULL DEFAULT b'1',
    `next_patrol_at` DATETIME DEFAULT NULL,
    `active_gap_count` INT NOT NULL DEFAULT 0,
    `last_task_id` BIGINT DEFAULT NULL,
    `last_source_batch_id` VARCHAR(100) DEFAULT NULL,
    `last_failure_type` VARCHAR(64) DEFAULT NULL,
    `diagnostic_summary` VARCHAR(2000) DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_noon_data_completeness_scope` (`owner_user_id`, `store_code`, `site_code`, `data_category`),
    KEY `idx_noon_data_completeness_status` (`latest_status`, `history_status`),
    KEY `idx_noon_data_completeness_patrol` (`patrol_enabled`, `next_patrol_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `noon_data_gap_window` (
    `id` BIGINT NOT NULL,
    `completeness_id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `store_code` VARCHAR(100) NOT NULL,
    `site_code` VARCHAR(32) NOT NULL,
    `data_category` VARCHAR(64) NOT NULL,
    `window_type` VARCHAR(64) NOT NULL,
    `date_from` DATE DEFAULT NULL,
    `date_to` DATE DEFAULT NULL,
    `status` VARCHAR(64) NOT NULL,
    `attempts` INT NOT NULL DEFAULT 0,
    `next_retry_at` DATETIME DEFAULT NULL,
    `linked_pull_plan_id` BIGINT DEFAULT NULL,
    `linked_pull_task_id` BIGINT DEFAULT NULL,
    `linked_source_batch_id` VARCHAR(100) DEFAULT NULL,
    `row_or_item_count` INT DEFAULT NULL,
    `failure_type` VARCHAR(64) DEFAULT NULL,
    `retryable` BIT(1) DEFAULT NULL,
    `requires_manual_action` BIT(1) DEFAULT NULL,
    `diagnostic_summary` VARCHAR(2000) DEFAULT NULL,
    `completed_empty_evidence_summary` VARCHAR(2000) DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_noon_data_gap_window_natural` (`completeness_id`, `data_category`, `window_type`, `date_from`, `date_to`),
    KEY `idx_noon_data_gap_window_scope` (`owner_user_id`, `store_code`, `site_code`, `data_category`),
    KEY `idx_noon_data_gap_window_status` (`status`, `next_retry_at`),
    KEY `idx_noon_data_gap_window_task` (`linked_pull_task_id`, `linked_source_batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

