CREATE TABLE IF NOT EXISTS `logistics_service_line` (
    `id` BIGINT NOT NULL,
    `natural_key` VARCHAR(500) NOT NULL,
    `forwarder_code` VARCHAR(80) NOT NULL,
    `forwarder_name` VARCHAR(160) DEFAULT NULL,
    `country` VARCHAR(80) DEFAULT NULL,
    `transport_mode` VARCHAR(80) DEFAULT NULL,
    `service_scope` VARCHAR(120) DEFAULT NULL,
    `channel_name` VARCHAR(160) DEFAULT NULL,
    `origin_node` VARCHAR(160) DEFAULT NULL,
    `destination_node` VARCHAR(160) DEFAULT NULL,
    `origin_warehouse` VARCHAR(160) DEFAULT NULL,
    `destination_warehouse` VARCHAR(160) DEFAULT NULL,
    `fulfillment_mode` VARCHAR(120) DEFAULT NULL,
    `estimated_days_min` INT DEFAULT NULL,
    `estimated_days_max` INT DEFAULT NULL,
    `departure_frequency` VARCHAR(160) DEFAULT NULL,
    `effective_from` DATE DEFAULT NULL,
    `effective_to` DATE DEFAULT NULL,
    `source_type` VARCHAR(40) NOT NULL,
    `source_task_id` BIGINT DEFAULT NULL,
    `source_result_id` BIGINT DEFAULT NULL,
    `source_version_id` BIGINT DEFAULT NULL,
    `source_version_item_id` BIGINT DEFAULT NULL,
    `source_file_name` VARCHAR(255) DEFAULT NULL,
    `source_locator` VARCHAR(255) DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logistics_service_line_source_item` (`source_version_item_id`),
    KEY `idx_logistics_service_line_natural_key` (`natural_key`),
    KEY `idx_logistics_service_line_source_version` (`source_version_id`),
    KEY `idx_logistics_service_line_status` (`status`),
    KEY `idx_logistics_service_line_scope` (`country`, `transport_mode`, `service_scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `logistics_cargo_category` (
    `id` BIGINT NOT NULL,
    `natural_key` VARCHAR(500) NOT NULL,
    `forwarder_code` VARCHAR(80) NOT NULL,
    `service_line_id` BIGINT DEFAULT NULL,
    `service_line_key` VARCHAR(500) DEFAULT NULL,
    `category_code` VARCHAR(120) DEFAULT NULL,
    `category_name` VARCHAR(255) NOT NULL,
    `source_category_name` VARCHAR(255) DEFAULT NULL,
    `product_examples` LONGTEXT DEFAULT NULL,
    `keywords` LONGTEXT DEFAULT NULL,
    `electric_type` VARCHAR(120) DEFAULT NULL,
    `sensitive_tags` VARCHAR(500) DEFAULT NULL,
    `packing_policy` VARCHAR(500) DEFAULT NULL,
    `manual_confirm_required` BIT(1) NOT NULL DEFAULT b'0',
    `source_type` VARCHAR(40) NOT NULL,
    `source_task_id` BIGINT DEFAULT NULL,
    `source_result_id` BIGINT DEFAULT NULL,
    `source_version_id` BIGINT DEFAULT NULL,
    `source_version_item_id` BIGINT DEFAULT NULL,
    `source_file_name` VARCHAR(255) DEFAULT NULL,
    `source_locator` VARCHAR(255) DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logistics_cargo_category_source_item` (`source_version_item_id`),
    KEY `idx_logistics_cargo_category_natural_key` (`natural_key`),
    KEY `idx_logistics_cargo_category_source_version` (`source_version_id`),
    KEY `idx_logistics_cargo_category_status` (`status`),
    KEY `idx_logistics_cargo_category_service` (`service_line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `logistics_price_rule` (
    `id` BIGINT NOT NULL,
    `natural_key` VARCHAR(500) NOT NULL,
    `forwarder_code` VARCHAR(80) NOT NULL,
    `service_line_id` BIGINT DEFAULT NULL,
    `service_line_key` VARCHAR(500) DEFAULT NULL,
    `cargo_category_id` BIGINT DEFAULT NULL,
    `cargo_category_key` VARCHAR(500) DEFAULT NULL,
    `billing_unit` VARCHAR(80) DEFAULT NULL,
    `pricing_model` VARCHAR(80) DEFAULT NULL,
    `currency` VARCHAR(30) DEFAULT NULL,
    `unit_price` DECIMAL(18,6) DEFAULT NULL,
    `weight_min` DECIMAL(18,6) DEFAULT NULL,
    `weight_max` DECIMAL(18,6) DEFAULT NULL,
    `volume_min` DECIMAL(18,6) DEFAULT NULL,
    `volume_max` DECIMAL(18,6) DEFAULT NULL,
    `minimum_billable_unit` DECIMAL(18,6) DEFAULT NULL,
    `minimum_billable_unit_type` VARCHAR(80) DEFAULT NULL,
    `minimum_charge` DECIMAL(18,6) DEFAULT NULL,
    `volume_divisor` DECIMAL(18,6) DEFAULT NULL,
    `sea_weight_ratio` VARCHAR(120) DEFAULT NULL,
    `rounding_rule` VARCHAR(500) DEFAULT NULL,
    `price_status` VARCHAR(80) NOT NULL DEFAULT 'NORMAL',
    `effective_from` DATE DEFAULT NULL,
    `effective_to` DATE DEFAULT NULL,
    `source_type` VARCHAR(40) NOT NULL,
    `source_task_id` BIGINT DEFAULT NULL,
    `source_result_id` BIGINT DEFAULT NULL,
    `source_version_id` BIGINT DEFAULT NULL,
    `source_version_item_id` BIGINT DEFAULT NULL,
    `source_file_name` VARCHAR(255) DEFAULT NULL,
    `source_locator` VARCHAR(255) DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logistics_price_rule_source_item` (`source_version_item_id`),
    KEY `idx_logistics_price_rule_natural_key` (`natural_key`),
    KEY `idx_logistics_price_rule_source_version` (`source_version_id`),
    KEY `idx_logistics_price_rule_status` (`status`),
    KEY `idx_logistics_price_rule_match` (`forwarder_code`, `billing_unit`, `currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `logistics_surcharge_rule` (
    `id` BIGINT NOT NULL,
    `natural_key` VARCHAR(500) NOT NULL,
    `forwarder_code` VARCHAR(80) NOT NULL,
    `service_line_id` BIGINT DEFAULT NULL,
    `service_line_key` VARCHAR(500) DEFAULT NULL,
    `surcharge_name` VARCHAR(255) NOT NULL,
    `surcharge_type` VARCHAR(120) DEFAULT NULL,
    `trigger_condition` VARCHAR(1000) DEFAULT NULL,
    `pricing_model` VARCHAR(80) DEFAULT NULL,
    `currency` VARCHAR(30) DEFAULT NULL,
    `amount` DECIMAL(18,6) DEFAULT NULL,
    `rate` DECIMAL(18,8) DEFAULT NULL,
    `billing_unit` VARCHAR(80) DEFAULT NULL,
    `minimum_charge` DECIMAL(18,6) DEFAULT NULL,
    `included_in_base_price` BIT(1) NOT NULL DEFAULT b'0',
    `source_type` VARCHAR(40) NOT NULL,
    `source_task_id` BIGINT DEFAULT NULL,
    `source_result_id` BIGINT DEFAULT NULL,
    `source_version_id` BIGINT DEFAULT NULL,
    `source_version_item_id` BIGINT DEFAULT NULL,
    `source_file_name` VARCHAR(255) DEFAULT NULL,
    `source_locator` VARCHAR(255) DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logistics_surcharge_rule_source_item` (`source_version_item_id`),
    KEY `idx_logistics_surcharge_rule_natural_key` (`natural_key`),
    KEY `idx_logistics_surcharge_rule_source_version` (`source_version_id`),
    KEY `idx_logistics_surcharge_rule_status` (`status`),
    KEY `idx_logistics_surcharge_rule_service` (`service_line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `logistics_billing_rule` (
    `id` BIGINT NOT NULL,
    `natural_key` VARCHAR(500) NOT NULL,
    `forwarder_code` VARCHAR(80) NOT NULL,
    `service_line_id` BIGINT DEFAULT NULL,
    `service_line_key` VARCHAR(500) DEFAULT NULL,
    `cargo_category_id` BIGINT DEFAULT NULL,
    `cargo_category_key` VARCHAR(500) DEFAULT NULL,
    `rule_name` VARCHAR(255) NOT NULL,
    `rule_type` VARCHAR(120) DEFAULT NULL,
    `condition_text` LONGTEXT DEFAULT NULL,
    `structured_field` VARCHAR(160) DEFAULT NULL,
    `operator` VARCHAR(80) DEFAULT NULL,
    `threshold_value` DECIMAL(18,6) DEFAULT NULL,
    `threshold_unit` VARCHAR(80) DEFAULT NULL,
    `action_text` LONGTEXT DEFAULT NULL,
    `severity` VARCHAR(80) DEFAULT NULL,
    `source_type` VARCHAR(40) NOT NULL,
    `source_task_id` BIGINT DEFAULT NULL,
    `source_result_id` BIGINT DEFAULT NULL,
    `source_version_id` BIGINT DEFAULT NULL,
    `source_version_item_id` BIGINT DEFAULT NULL,
    `source_file_name` VARCHAR(255) DEFAULT NULL,
    `source_locator` VARCHAR(255) DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logistics_billing_rule_source_item` (`source_version_item_id`),
    KEY `idx_logistics_billing_rule_natural_key` (`natural_key`),
    KEY `idx_logistics_billing_rule_source_version` (`source_version_id`),
    KEY `idx_logistics_billing_rule_status` (`status`),
    KEY `idx_logistics_billing_rule_service` (`service_line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `logistics_warehouse_fee_rule` (
    `id` BIGINT NOT NULL,
    `natural_key` VARCHAR(500) NOT NULL,
    `forwarder_code` VARCHAR(80) NOT NULL,
    `country` VARCHAR(80) DEFAULT NULL,
    `warehouse_node` VARCHAR(160) DEFAULT NULL,
    `service_name` VARCHAR(255) NOT NULL,
    `service_type` VARCHAR(120) DEFAULT NULL,
    `processing_scope` VARCHAR(160) DEFAULT NULL,
    `fee_type` VARCHAR(120) DEFAULT NULL,
    `pricing_model` VARCHAR(80) DEFAULT NULL,
    `currency` VARCHAR(30) DEFAULT NULL,
    `amount` DECIMAL(18,6) DEFAULT NULL,
    `rate` DECIMAL(18,8) DEFAULT NULL,
    `billing_unit` VARCHAR(80) DEFAULT NULL,
    `condition_text` LONGTEXT DEFAULT NULL,
    `free_condition` VARCHAR(1000) DEFAULT NULL,
    `source_type` VARCHAR(40) NOT NULL,
    `source_task_id` BIGINT DEFAULT NULL,
    `source_result_id` BIGINT DEFAULT NULL,
    `source_version_id` BIGINT DEFAULT NULL,
    `source_version_item_id` BIGINT DEFAULT NULL,
    `source_file_name` VARCHAR(255) DEFAULT NULL,
    `source_locator` VARCHAR(255) DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logistics_warehouse_fee_rule_source_item` (`source_version_item_id`),
    KEY `idx_logistics_warehouse_fee_rule_natural_key` (`natural_key`),
    KEY `idx_logistics_warehouse_fee_rule_source_version` (`source_version_id`),
    KEY `idx_logistics_warehouse_fee_rule_status` (`status`),
    KEY `idx_logistics_warehouse_fee_rule_scope` (`country`, `warehouse_node`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `logistics_restriction_rule` (
    `id` BIGINT NOT NULL,
    `natural_key` VARCHAR(500) NOT NULL,
    `forwarder_code` VARCHAR(80) NOT NULL,
    `service_line_id` BIGINT DEFAULT NULL,
    `service_line_key` VARCHAR(500) DEFAULT NULL,
    `restriction_type` VARCHAR(120) NOT NULL,
    `item_text` VARCHAR(1000) NOT NULL,
    `requirement_text` LONGTEXT DEFAULT NULL,
    `applicability_scope` VARCHAR(1000) DEFAULT NULL,
    `severity` VARCHAR(80) DEFAULT NULL,
    `manual_confirm_required` BIT(1) NOT NULL DEFAULT b'0',
    `source_type` VARCHAR(40) NOT NULL,
    `source_task_id` BIGINT DEFAULT NULL,
    `source_result_id` BIGINT DEFAULT NULL,
    `source_version_id` BIGINT DEFAULT NULL,
    `source_version_item_id` BIGINT DEFAULT NULL,
    `source_file_name` VARCHAR(255) DEFAULT NULL,
    `source_locator` VARCHAR(255) DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logistics_restriction_rule_source_item` (`source_version_item_id`),
    KEY `idx_logistics_restriction_rule_natural_key` (`natural_key`),
    KEY `idx_logistics_restriction_rule_source_version` (`source_version_id`),
    KEY `idx_logistics_restriction_rule_status` (`status`),
    KEY `idx_logistics_restriction_rule_service` (`service_line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
