CREATE TABLE IF NOT EXISTS `procurement_logistics_requirement` (
    `id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `demand_item_id` BIGINT NOT NULL,
    `transport_mode` VARCHAR(40) NOT NULL,
    `destination_country` VARCHAR(80) DEFAULT NULL,
    `destination_node` VARCHAR(160) DEFAULT NULL,
    `origin_node` VARCHAR(160) DEFAULT NULL,
    `package_length_cm` DECIMAL(12,3) DEFAULT NULL,
    `package_width_cm` DECIMAL(12,3) DEFAULT NULL,
    `package_height_cm` DECIMAL(12,3) DEFAULT NULL,
    `unit_weight_grams` DECIMAL(12,3) DEFAULT NULL,
    `quantity` INT DEFAULT NULL,
    `cargo_attributes` VARCHAR(500) DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_procurement_logistics_requirement_demand` (`demand_item_id`),
    KEY `idx_procurement_logistics_requirement_owner` (`owner_user_id`),
    KEY `idx_procurement_logistics_requirement_mode` (`transport_mode`),
    KEY `idx_procurement_logistics_requirement_destination` (`destination_country`, `destination_node`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
