CREATE TABLE IF NOT EXISTS `product_selection_ali1688_plugin_assignment` (
    `id` BIGINT NOT NULL,
    `assignment_code` VARCHAR(80) NOT NULL,
    `assignment_type` VARCHAR(40) NOT NULL,
    `task_id` BIGINT NOT NULL,
    `candidate_id` BIGINT NULL,
    `source_collection_id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT NOT NULL,
    `current_assignment_key` VARCHAR(180) NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'created',
    `idempotency_key` VARCHAR(120) NULL,
    `result_status` VARCHAR(60) NULL,
    `result_snapshot_json` MEDIUMTEXT NULL,
    `failure_code` VARCHAR(100) NULL,
    `failure_message` VARCHAR(500) NULL,
    `submitted_candidate_count` INT NOT NULL DEFAULT 0,
    `accepted_candidate_count` INT NOT NULL DEFAULT 0,
    `rejected_candidate_count` INT NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `expires_at` DATETIME NULL,
    `started_at` DATETIME NULL,
    `finished_at` DATETIME NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT NULL,
    `updated_by` BIGINT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ali1688_plugin_assignment_code` (`assignment_code`),
    UNIQUE KEY `uk_ali1688_plugin_assignment_current` (`current_assignment_key`),
    KEY `idx_ali1688_plugin_assignment_task` (`task_id`),
    KEY `idx_ali1688_plugin_assignment_candidate` (`candidate_id`),
    KEY `idx_ali1688_plugin_assignment_store_status` (`logical_store_id`, `status`, `gmt_updated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
