CREATE TABLE IF NOT EXISTS `product_selection_ali1688_detail_enrichment_snapshot` (
    `id` BIGINT NOT NULL,
    `assignment_id` BIGINT NOT NULL,
    `task_id` BIGINT NOT NULL,
    `candidate_id` BIGINT NOT NULL,
    `source_collection_id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT NOT NULL,
    `snapshot_source` VARCHAR(60) NOT NULL DEFAULT 'browser-extension',
    `collected_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `collected_at_text` VARCHAR(80) NULL,
    `page_url` VARCHAR(1000) NULL,
    `detail_title` VARCHAR(500) NULL,
    `main_image_urls_json` MEDIUMTEXT NULL,
    `detail_image_urls_json` MEDIUMTEXT NULL,
    `image_urls_json` MEDIUMTEXT NULL,
    `sku_options_json` MEDIUMTEXT NULL,
    `moq_text` VARCHAR(200) NULL,
    `supplier_name` VARCHAR(300) NULL,
    `location_text` VARCHAR(200) NULL,
    `list_price_text` VARCHAR(200) NULL,
    `service_labels_json` MEDIUMTEXT NULL,
    `sales_labels_json` MEDIUMTEXT NULL,
    `raw_evidence_snippets_json` MEDIUMTEXT NULL,
    `raw_snapshot_json` MEDIUMTEXT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT NULL,
    `updated_by` BIGINT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_ali1688_detail_snapshot_assignment` (`assignment_id`),
    KEY `idx_ali1688_detail_snapshot_candidate` (`candidate_id`, `gmt_updated`),
    KEY `idx_ali1688_detail_snapshot_task` (`task_id`, `gmt_updated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
