SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `in_transit_batch` (
    `id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `standard_forwarder_id` BIGINT DEFAULT NULL,
    `raw_forwarder_name` VARCHAR(255) DEFAULT NULL,
    `normalized_raw_forwarder_name` VARCHAR(255) DEFAULT NULL,
    `forwarder_quality_status` VARCHAR(60) NOT NULL DEFAULT 'forwarder_unmatched',
    `transport_mode` ENUM('SEA','AIR') DEFAULT NULL,
    `batch_status` ENUM('draft','pending_shipment','shipped','in_transit','customs_clearance','delivering','warehouse_received','exception','completed','cancelled') NOT NULL DEFAULT 'draft',
    `target_store_code` VARCHAR(80) DEFAULT NULL,
    `target_site_code` VARCHAR(80) DEFAULT NULL,
    `target_warehouse_name` VARCHAR(160) DEFAULT NULL,
    `departure_date` DATE DEFAULT NULL,
    `eta_date` DATE DEFAULT NULL,
    `tracking_no` VARCHAR(160) DEFAULT NULL,
    `container_no` VARCHAR(160) DEFAULT NULL,
    `batch_reference_no` VARCHAR(160) DEFAULT NULL,
    `remark` VARCHAR(1000) DEFAULT NULL,
    `missing_fields_json` LONGTEXT DEFAULT NULL,
    `sku_count` INT DEFAULT NULL,
    `shipped_quantity_total` INT DEFAULT NULL,
    `received_quantity_total` INT DEFAULT NULL,
    `remaining_quantity_total` INT DEFAULT NULL,
    `carton_count_total` INT DEFAULT NULL,
    `total_weight_kg` DECIMAL(18,6) DEFAULT NULL,
    `total_volume_cbm` DECIMAL(18,6) DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_in_transit_batch_filter` (`owner_user_id`, `standard_forwarder_id`, `transport_mode`, `target_store_code`, `target_site_code`, `batch_status`),
    KEY `idx_in_transit_batch_eta` (`owner_user_id`, `eta_date`, `batch_status`),
    KEY `idx_in_transit_batch_raw_forwarder` (`owner_user_id`, `normalized_raw_forwarder_name`),
    KEY `idx_in_transit_batch_tracking` (`owner_user_id`, `tracking_no`, `container_no`, `batch_reference_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
