SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `in_transit_goods_line` (
    `id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `batch_id` BIGINT NOT NULL,
    `package_id` BIGINT DEFAULT NULL,
    `box_no` VARCHAR(160) DEFAULT NULL,
    `sku` VARCHAR(160) NOT NULL,
    `msku` VARCHAR(160) DEFAULT NULL,
    `psku` VARCHAR(160) DEFAULT NULL,
    `product_name` VARCHAR(500) DEFAULT NULL,
    `store_code` VARCHAR(80) DEFAULT NULL,
    `site_code` VARCHAR(80) DEFAULT NULL,
    `shipped_quantity` INT NOT NULL DEFAULT 0,
    `received_quantity` INT NOT NULL DEFAULT 0,
    `remaining_quantity` INT NOT NULL DEFAULT 0,
    `carton_count` INT DEFAULT NULL,
    `units_per_carton` INT DEFAULT NULL,
    `carton_weight_kg` DECIMAL(18,6) DEFAULT NULL,
    `carton_volume_cbm` DECIMAL(18,6) DEFAULT NULL,
    `remark` VARCHAR(1000) DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_in_transit_goods_line_batch` (`owner_user_id`, `batch_id`, `is_deleted`),
    KEY `idx_in_transit_goods_line_package` (`owner_user_id`, `batch_id`, `package_id`, `is_deleted`),
    KEY `idx_in_transit_goods_line_sku` (`owner_user_id`, `sku`, `msku`, `psku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
