CREATE TABLE IF NOT EXISTS `product_selection_ali1688_price_preview_snapshot` (
    `id` BIGINT NOT NULL,
    `assignment_id` BIGINT NOT NULL,
    `task_id` BIGINT NOT NULL,
    `candidate_id` BIGINT NOT NULL,
    `source_collection_id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT NOT NULL,
    `snapshot_source` VARCHAR(60) NOT NULL DEFAULT 'browser-extension',
    `result_status` VARCHAR(60) NOT NULL DEFAULT 'success',
    `failure_code` VARCHAR(100) NULL,
    `failure_message` VARCHAR(500) NULL,
    `collected_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `collected_at_text` VARCHAR(80) NULL,
    `sku_options_json` MEDIUMTEXT NULL,
    `quantity` INT NULL,
    `unit_price_text` VARCHAR(160) NULL,
    `shipping_text` VARCHAR(160) NULL,
    `discount_text` VARCHAR(160) NULL,
    `total_price_text` VARCHAR(160) NULL,
    `currency` VARCHAR(20) NULL,
    `region_text` VARCHAR(300) NULL,
    `safety_mode` VARCHAR(60) NOT NULL DEFAULT 'preview_only',
    `side_effect_policy` VARCHAR(100) NOT NULL DEFAULT 'no_payment_no_order_no_message',
    `raw_snapshot_json` MEDIUMTEXT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT NULL,
    `updated_by` BIGINT NULL,
    `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_ali1688_price_preview_assignment` (`assignment_id`),
    KEY `idx_ali1688_price_preview_candidate` (`candidate_id`, `gmt_updated`),
    KEY `idx_ali1688_price_preview_task` (`task_id`, `gmt_updated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
