CREATE TABLE IF NOT EXISTS `procurement_ali1688_order_item_product_link` (
  `id` BIGINT NOT NULL,
  `owner_user_id` BIGINT NOT NULL,
  `authorization_id` BIGINT NOT NULL,
  `order_id` BIGINT NOT NULL,
  `item_id` BIGINT NOT NULL,
  `assignment_id` BIGINT NOT NULL,
  `target_store_code` VARCHAR(120) NOT NULL,
  `target_site_code` VARCHAR(40) DEFAULT NULL,
  `sku_parent` VARCHAR(160) NOT NULL,
  `partner_sku` VARCHAR(160) DEFAULT NULL,
  `psku_code` VARCHAR(160) DEFAULT NULL,
  `product_title` VARCHAR(1000) DEFAULT NULL,
  `product_image_url` VARCHAR(1000) DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'active',
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `idx_ali1688_item_product_link_owner_assignment` (`owner_user_id`, `assignment_id`, `status`, `is_deleted`),
  KEY `idx_ali1688_item_product_link_owner_sku` (`owner_user_id`, `target_store_code`, `target_site_code`, `sku_parent`, `status`, `is_deleted`),
  KEY `idx_ali1688_item_product_link_order_item` (`order_id`, `item_id`, `assignment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='1688历史订单分配行商品关联事实';
