-- Noon official warehouse statistics facts and review events.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `official_warehouse_stock_correction_event` (
    `id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT DEFAULT NULL,
    `store_code` VARCHAR(100) NOT NULL,
    `site_code` VARCHAR(20) NOT NULL,
    `project_code` VARCHAR(100) DEFAULT NULL,
    `partner_id` VARCHAR(80) DEFAULT NULL,
    `correction_type` VARCHAR(40) NOT NULL,
    `target_ref_type` VARCHAR(80) NOT NULL,
    `target_ref_id` BIGINT DEFAULT NULL,
    `product_master_id` BIGINT DEFAULT NULL,
    `product_variant_id` BIGINT DEFAULT NULL,
    `product_site_offer_id` BIGINT DEFAULT NULL,
    `partner_sku` VARCHAR(100) DEFAULT NULL,
    `psku_code` VARCHAR(100) DEFAULT NULL,
    `noon_sku` VARCHAR(100) DEFAULT NULL,
    `warehouse_code` VARCHAR(100) DEFAULT NULL,
    `from_stock_bucket` VARCHAR(60) DEFAULT NULL,
    `to_stock_bucket` VARCHAR(60) NOT NULL,
    `quantity` INT NOT NULL,
    `reason_code` VARCHAR(100) DEFAULT NULL,
    `reason_text` VARCHAR(1000) DEFAULT NULL,
    `before_payload_json` LONGTEXT DEFAULT NULL,
    `after_payload_json` LONGTEXT DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_official_warehouse_stock_correction_scope` (`owner_user_id`, `store_code`, `site_code`, `correction_type`),
    KEY `idx_official_warehouse_stock_correction_product` (`product_site_offer_id`, `warehouse_code`, `to_stock_bucket`),
    KEY `idx_official_warehouse_stock_correction_target` (`target_ref_type`, `target_ref_id`),
    KEY `idx_official_warehouse_stock_correction_time` (`gmt_create`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `official_warehouse_inventory_sync_batch` (
    `id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT DEFAULT NULL,
    `store_code` VARCHAR(100) NOT NULL,
    `site_code` VARCHAR(20) NOT NULL,
    `project_code` VARCHAR(100) DEFAULT NULL,
    `partner_id` VARCHAR(80) DEFAULT NULL,
    `source_type` VARCHAR(60) NOT NULL,
    `request_summary_json` LONGTEXT DEFAULT NULL,
    `response_summary_json` LONGTEXT DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL,
    `total_pages` INT DEFAULT NULL,
    `total_rows` INT DEFAULT NULL,
    `valid_rows` INT DEFAULT NULL,
    `error_rows` INT DEFAULT NULL,
    `synced_at` DATETIME DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_official_warehouse_inventory_sync_scope` (`owner_user_id`, `store_code`, `site_code`, `source_type`, `status`),
    KEY `idx_official_warehouse_inventory_sync_time` (`synced_at`, `gmt_create`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `official_warehouse_inventory_snapshot_line` (
    `id` BIGINT NOT NULL,
    `sync_batch_id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT DEFAULT NULL,
    `store_code` VARCHAR(100) NOT NULL,
    `site_code` VARCHAR(20) NOT NULL,
    `project_code` VARCHAR(100) DEFAULT NULL,
    `partner_id` VARCHAR(80) DEFAULT NULL,
    `product_master_id` BIGINT DEFAULT NULL,
    `product_variant_id` BIGINT DEFAULT NULL,
    `product_site_offer_id` BIGINT DEFAULT NULL,
    `partner_sku` VARCHAR(100) DEFAULT NULL,
    `psku_code` VARCHAR(100) DEFAULT NULL,
    `noon_sku` VARCHAR(100) DEFAULT NULL,
    `pbarcode` VARCHAR(100) DEFAULT NULL,
    `barcode` VARCHAR(100) DEFAULT NULL,
    `warehouse_code` VARCHAR(100) DEFAULT NULL,
    `country_code` VARCHAR(20) DEFAULT NULL,
    `inventory_type` VARCHAR(100) DEFAULT NULL,
    `reason_code` VARCHAR(100) DEFAULT NULL,
    `classification_code` VARCHAR(100) DEFAULT NULL,
    `stock_bucket` VARCHAR(60) NOT NULL,
    `qty` INT NOT NULL DEFAULT 0,
    `inventory_snapshot_at` DATETIME DEFAULT NULL,
    `title_cache` VARCHAR(1000) DEFAULT NULL,
    `brand_cache` VARCHAR(255) DEFAULT NULL,
    `match_status` VARCHAR(60) DEFAULT NULL,
    `match_message` VARCHAR(1000) DEFAULT NULL,
    `raw_payload_json` LONGTEXT DEFAULT NULL,
    `is_current` BIT(1) NOT NULL DEFAULT b'1',
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_official_warehouse_inventory_line_scope` (`owner_user_id`, `store_code`, `site_code`, `is_current`, `warehouse_code`, `stock_bucket`),
    KEY `idx_official_warehouse_inventory_line_sku` (`owner_user_id`, `store_code`, `site_code`, `noon_sku`),
    KEY `idx_official_warehouse_inventory_line_partner_sku` (`owner_user_id`, `store_code`, `site_code`, `partner_sku`),
    KEY `idx_official_warehouse_inventory_line_product` (`product_site_offer_id`, `warehouse_code`, `stock_bucket`),
    KEY `idx_official_warehouse_inventory_line_batch` (`sync_batch_id`, `is_current`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `official_warehouse_report_import` (
    `id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT DEFAULT NULL,
    `store_code` VARCHAR(100) NOT NULL,
    `site_code` VARCHAR(20) NOT NULL,
    `project_code` VARCHAR(100) DEFAULT NULL,
    `partner_id` VARCHAR(80) DEFAULT NULL,
    `report_type` VARCHAR(80) NOT NULL,
    `source_type` VARCHAR(60) NOT NULL,
    `source_export_code` VARCHAR(120) DEFAULT NULL,
    `file_name` VARCHAR(500) DEFAULT NULL,
    `file_sha256` VARCHAR(64) DEFAULT NULL,
    `snapshot_at` DATETIME DEFAULT NULL,
    `business_date_start` DATE DEFAULT NULL,
    `business_date_end` DATE DEFAULT NULL,
    `total_rows` INT DEFAULT NULL,
    `valid_rows` INT DEFAULT NULL,
    `warning_rows` INT DEFAULT NULL,
    `error_rows` INT DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL,
    `summary_json` LONGTEXT DEFAULT NULL,
    `raw_preview_json` LONGTEXT DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_official_warehouse_report_import_scope` (`owner_user_id`, `store_code`, `site_code`, `report_type`, `status`),
    KEY `idx_official_warehouse_report_import_export` (`report_type`, `source_export_code`, `is_deleted`),
    KEY `idx_official_warehouse_report_import_file` (`file_sha256`),
    KEY `idx_official_warehouse_report_import_time` (`snapshot_at`, `gmt_create`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `official_warehouse_report_row` (
    `id` BIGINT NOT NULL,
    `import_id` BIGINT NOT NULL,
    `report_type` VARCHAR(80) NOT NULL,
    `row_no` INT NOT NULL,
    `business_key` VARCHAR(500) DEFAULT NULL,
    `business_key_hash` VARCHAR(64) DEFAULT NULL,
    `row_status` VARCHAR(40) NOT NULL,
    `warning_code` VARCHAR(500) DEFAULT NULL,
    `error_message` VARCHAR(1000) DEFAULT NULL,
    `raw_row_json` LONGTEXT DEFAULT NULL,
    `normalized_row_json` LONGTEXT DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_official_warehouse_report_row_import_row` (`import_id`, `row_no`),
    KEY `idx_official_warehouse_report_row_key` (`report_type`, `business_key_hash`, `row_status`),
    KEY `idx_official_warehouse_report_row_import` (`import_id`, `row_status`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `official_warehouse_inbound_receipt_line` (
    `id` BIGINT NOT NULL,
    `import_id` BIGINT NOT NULL,
    `report_row_id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT DEFAULT NULL,
    `store_code` VARCHAR(100) NOT NULL,
    `site_code` VARCHAR(20) NOT NULL,
    `project_code` VARCHAR(100) DEFAULT NULL,
    `partner_id` VARCHAR(80) DEFAULT NULL,
    `asn_id` BIGINT DEFAULT NULL,
    `asn_line_id` BIGINT DEFAULT NULL,
    `noon_asn_nr` VARCHAR(120) DEFAULT NULL,
    `product_master_id` BIGINT DEFAULT NULL,
    `product_variant_id` BIGINT DEFAULT NULL,
    `product_site_offer_id` BIGINT DEFAULT NULL,
    `partner_sku` VARCHAR(100) DEFAULT NULL,
    `psku_code` VARCHAR(100) DEFAULT NULL,
    `noon_sku` VARCHAR(100) DEFAULT NULL,
    `pbarcode_canonical` VARCHAR(120) DEFAULT NULL,
    `partner_warehouse` VARCHAR(100) DEFAULT NULL,
    `noon_warehouse` VARCHAR(100) DEFAULT NULL,
    `country_code` VARCHAR(20) DEFAULT NULL,
    `qty_expected` INT NOT NULL DEFAULT 0,
    `received_qty` INT NOT NULL DEFAULT 0,
    `qc_failed_qty` INT NOT NULL DEFAULT 0,
    `unidentified_qty` INT NOT NULL DEFAULT 0,
    `qc_failed_reason` VARCHAR(1000) DEFAULT NULL,
    `receipt_status` VARCHAR(60) NOT NULL,
    `match_status` VARCHAR(60) NOT NULL,
    `anomaly_flags_json` LONGTEXT DEFAULT NULL,
    `asn_created_at` DATETIME DEFAULT NULL,
    `asn_schedule_date` DATE DEFAULT NULL,
    `asn_completed_at` DATETIME DEFAULT NULL,
    `raw_payload_json` LONGTEXT DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_official_warehouse_receipt_line_scope` (`owner_user_id`, `store_code`, `site_code`, `receipt_status`, `match_status`),
    KEY `idx_official_warehouse_receipt_line_import` (`import_id`, `is_deleted`),
    KEY `idx_official_warehouse_receipt_line_report_row` (`report_row_id`),
    KEY `idx_official_warehouse_receipt_line_asn` (`asn_id`, `asn_line_id`, `noon_asn_nr`),
    KEY `idx_official_warehouse_receipt_line_sku` (`owner_user_id`, `store_code`, `site_code`, `noon_sku`),
    KEY `idx_official_warehouse_receipt_line_partner_sku` (`owner_user_id`, `store_code`, `site_code`, `partner_sku`),
    KEY `idx_official_warehouse_receipt_line_product` (`product_site_offer_id`, `receipt_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `official_warehouse_delivery_accuracy_asn` (
    `id` BIGINT NOT NULL,
    `import_id` BIGINT NOT NULL,
    `report_row_id` BIGINT NOT NULL,
    `owner_user_id` BIGINT NOT NULL,
    `logical_store_id` BIGINT DEFAULT NULL,
    `store_code` VARCHAR(100) NOT NULL,
    `site_code` VARCHAR(20) NOT NULL,
    `project_code` VARCHAR(100) DEFAULT NULL,
    `partner_id` VARCHAR(80) DEFAULT NULL,
    `asn_id` BIGINT DEFAULT NULL,
    `appointment_id` BIGINT DEFAULT NULL,
    `noon_asn_nr` VARCHAR(120) DEFAULT NULL,
    `warehouse_code` VARCHAR(100) DEFAULT NULL,
    `country_code` VARCHAR(20) DEFAULT NULL,
    `asn_creation_date` DATETIME DEFAULT NULL,
    `scheduled_date` DATE DEFAULT NULL,
    `delivery_date` DATE DEFAULT NULL,
    `scheduled_qty` INT NOT NULL DEFAULT 0,
    `grn_qty` INT NOT NULL DEFAULT 0,
    `inbound_qty_variance` INT NOT NULL DEFAULT 0,
    `accuracy_status` VARCHAR(80) DEFAULT NULL,
    `inbound_utilization_efficiency` DECIMAL(8,2) DEFAULT NULL,
    `match_status` VARCHAR(60) NOT NULL,
    `anomaly_flags_json` LONGTEXT DEFAULT NULL,
    `raw_payload_json` LONGTEXT DEFAULT NULL,
    `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
    `created_by` BIGINT DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `gmt_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_official_warehouse_delivery_accuracy_import` (`import_id`, `noon_asn_nr`, `is_deleted`),
    KEY `idx_official_warehouse_delivery_accuracy_scope` (`owner_user_id`, `store_code`, `site_code`, `noon_asn_nr`),
    KEY `idx_official_warehouse_delivery_accuracy_asn` (`asn_id`),
    KEY `idx_official_warehouse_delivery_accuracy_appointment` (`appointment_id`),
    KEY `idx_official_warehouse_delivery_accuracy_status` (`accuracy_status`, `scheduled_date`),
    KEY `idx_official_warehouse_delivery_accuracy_warehouse` (`owner_user_id`, `store_code`, `site_code`, `warehouse_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `product_management_id_sequence` (`sequence_name`, `next_id`, `gmt_create`, `gmt_updated`)
VALUES
  ('official_warehouse_stock_correction_event', 620000, NOW(), NOW()),
  ('official_warehouse_inventory_sync_batch', 621000, NOW(), NOW()),
  ('official_warehouse_inventory_snapshot_line', 622000, NOW(), NOW()),
  ('official_warehouse_report_import', 623000, NOW(), NOW()),
  ('official_warehouse_report_row', 624000, NOW(), NOW()),
  ('official_warehouse_inbound_receipt_line', 625000, NOW(), NOW()),
  ('official_warehouse_delivery_accuracy_asn', 626000, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `next_id` = GREATEST(`next_id`, VALUES(`next_id`)),
  `gmt_updated` = NOW();
