SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `post_sale_profit_recalculation_run` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `owner_user_id` BIGINT NOT NULL,
  `store_code` VARCHAR(64) NOT NULL,
  `site_code` VARCHAR(32) NOT NULL,
  `date_from` DATE NOT NULL,
  `date_to` DATE NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `scope_hash` VARCHAR(128) NOT NULL,
  `order_line_count` INT NOT NULL DEFAULT 0,
  `attributed_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0,
  `locked_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0,
  `unassigned_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0,
  `missing_issue_count` INT NOT NULL DEFAULT 0,
  `diagnostic_json` JSON DEFAULT NULL,
  `started_at` DATETIME NOT NULL,
  `finished_at` DATETIME DEFAULT NULL,
  `created_by` BIGINT DEFAULT NULL,
  `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_psp_run_scope_hash` (`owner_user_id`, `scope_hash`, `is_deleted`),
  KEY `idx_psp_run_scope` (`owner_user_id`, `store_code`, `site_code`, `date_from`, `date_to`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `post_sale_profit_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `run_id` BIGINT NOT NULL,
  `owner_user_id` BIGINT NOT NULL,
  `store_code` VARCHAR(64) NOT NULL,
  `site_code` VARCHAR(32) NOT NULL,
  `product_master_id` BIGINT DEFAULT NULL,
  `product_variant_id` BIGINT DEFAULT NULL,
  `sku_parent` VARCHAR(128) DEFAULT NULL,
  `partner_sku` VARCHAR(128) DEFAULT NULL,
  `title_snapshot` VARCHAR(512) DEFAULT NULL,
  `image_url_snapshot` VARCHAR(1024) DEFAULT NULL,
  `purchase_source_type` VARCHAR(64) NOT NULL,
  `purchase_source_id` VARCHAR(128) DEFAULT NULL,
  `purchase_batch_time` DATETIME DEFAULT NULL,
  `purchase_time_source` VARCHAR(64) DEFAULT NULL,
  `purchase_quantity` DECIMAL(18,4) DEFAULT NULL,
  `purchase_unit_cost_cny` DECIMAL(18,6) DEFAULT NULL,
  `purchase_cost_cny` DECIMAL(18,6) DEFAULT NULL,
  `shipping_source_type` VARCHAR(64) NOT NULL,
  `shipping_source_id` VARCHAR(128) DEFAULT NULL,
  `shipping_batch_no` VARCHAR(128) DEFAULT NULL,
  `in_transit_batch_id` VARCHAR(128) DEFAULT NULL,
  `in_transit_reference_no` VARCHAR(128) DEFAULT NULL,
  `available_at` DATETIME DEFAULT NULL,
  `available_at_source` VARCHAR(64) DEFAULT NULL,
  `headhaul_cost_source_type` VARCHAR(64) NOT NULL,
  `headhaul_unit_cost_cny` DECIMAL(18,6) DEFAULT NULL,
  `headhaul_cost_cny` DECIMAL(18,6) DEFAULT NULL,
  `sold_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0,
  `locked_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0,
  `auto_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0,
  `unassigned_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0,
  `net_proceeds_lcy` DECIMAL(18,6) DEFAULT NULL,
  `referral_fee_lcy` DECIMAL(18,6) DEFAULT NULL,
  `fulfillment_fee_lcy` DECIMAL(18,6) DEFAULT NULL,
  `other_fee_net_lcy` DECIMAL(18,6) DEFAULT NULL,
  `currency` VARCHAR(16) DEFAULT NULL,
  `fx_rate_to_cny` DECIMAL(18,8) DEFAULT NULL,
  `profit_cny` DECIMAL(18,6) DEFAULT NULL,
  `profit_rate` DECIMAL(18,8) DEFAULT NULL,
  `quality_status_json` JSON NOT NULL,
  `evidence_json` JSON DEFAULT NULL,
  `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `idx_psp_batch_scope` (`owner_user_id`, `store_code`, `site_code`, `is_deleted`),
  KEY `idx_psp_batch_run` (`run_id`, `is_deleted`),
  KEY `idx_psp_batch_sku_time` (`owner_user_id`, `store_code`, `site_code`, `partner_sku`, `purchase_batch_time`, `is_deleted`),
  KEY `idx_psp_batch_profit` (`owner_user_id`, `store_code`, `site_code`, `profit_cny`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `post_sale_profit_order_attribution` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `run_id` BIGINT NOT NULL,
  `batch_id` BIGINT NOT NULL,
  `owner_user_id` BIGINT NOT NULL,
  `store_code` VARCHAR(64) NOT NULL,
  `site_code` VARCHAR(32) NOT NULL,
  `order_line_fact_id` BIGINT DEFAULT NULL,
  `finance_item_nr` VARCHAR(128) DEFAULT NULL,
  `order_nr` VARCHAR(128) DEFAULT NULL,
  `item_nr` VARCHAR(128) DEFAULT NULL,
  `order_time` DATETIME DEFAULT NULL,
  `partner_sku` VARCHAR(128) DEFAULT NULL,
  `sku` VARCHAR(128) DEFAULT NULL,
  `product_variant_id` BIGINT DEFAULT NULL,
  `attributed_quantity` DECIMAL(18,4) NOT NULL,
  `attribution_method` VARCHAR(32) NOT NULL,
  `locked` BIT(1) NOT NULL DEFAULT b'0',
  `manual_reason` VARCHAR(512) DEFAULT NULL,
  `net_proceeds_lcy` DECIMAL(18,6) DEFAULT NULL,
  `referral_fee_lcy` DECIMAL(18,6) DEFAULT NULL,
  `fulfillment_fee_lcy` DECIMAL(18,6) DEFAULT NULL,
  `other_fee_net_lcy` DECIMAL(18,6) DEFAULT NULL,
  `currency` VARCHAR(16) DEFAULT NULL,
  `quality_status_json` JSON NOT NULL,
  `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `idx_psp_attr_scope` (`owner_user_id`, `store_code`, `site_code`, `is_deleted`),
  KEY `idx_psp_attr_batch` (`batch_id`, `is_deleted`),
  KEY `idx_psp_attr_item` (`owner_user_id`, `store_code`, `site_code`, `item_nr`, `is_deleted`),
  KEY `idx_psp_attr_locked` (`run_id`, `locked`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `post_sale_profit_fx_rate` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `owner_user_id` BIGINT DEFAULT NULL,
  `site_code` VARCHAR(32) NOT NULL,
  `currency` VARCHAR(16) NOT NULL,
  `rate_to_cny` DECIMAL(18,8) NOT NULL,
  `effective_from` DATE NOT NULL,
  `effective_to` DATE DEFAULT NULL,
  `source_label` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `idx_psp_fx_scope` (`owner_user_id`, `site_code`, `currency`, `effective_from`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
