package com.nuono.next.infrastructure.mapper;

import com.nuono.next.competitoranalysis.dp08.Dp08KeywordScopeRow;
import com.nuono.next.competitoranalysis.dp08.Dp08ListTargetRow;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

/** Globally row-bounded native member keysets; no logical scope can expand one SQL call. */
@Mapper
public interface Dp08BoundedScheduleScopeMapper {
    @Select({"<script>",
            "SELECT target.ownerUserId,target.logicalStoreId,target.watchProductId,target.keywordId,",
            "target.storeCode,target.siteCode,target.keyword,target.locale,target.trackedProductType,",
            "target.competitorProductId,target.trackedNoonProductCode,target.sourceUpdatedAtUtc",
            "FROM (",
            " SELECT wp.owner_user_id ownerUserId,wp.logical_store_id logicalStoreId,",
            " wp.id watchProductId,kw.id keywordId,UPPER(wp.store_code) storeCode,",
            " UPPER(wp.site_code) siteCode,kw.keyword,kw.locale,'SELF' trackedProductType,",
            " NULL competitorProductId,UPPER(TRIM(wp.self_noon_product_code)) trackedNoonProductCode,",
            " GREATEST(wp.gmt_updated,kw.gmt_updated) sourceUpdatedAtUtc,0 memberOrder,0 memberId",
            " FROM operations_competitor_watch_product wp",
            " JOIN operations_competitor_keyword kw ON kw.watch_product_id=wp.id",
            "  AND kw.status='ACTIVE' AND kw.is_deleted=b'0'",
            " WHERE wp.status='ACTIVE' AND wp.is_deleted=b'0'",
            "  AND NULLIF(TRIM(wp.self_noon_product_code),'') IS NOT NULL",
            " UNION ALL",
            " SELECT wp.owner_user_id,wp.logical_store_id,wp.id,kw.id,UPPER(wp.store_code),",
            " UPPER(wp.site_code),kw.keyword,kw.locale,'COMPETITOR',cp.id,",
            " UPPER(TRIM(cp.noon_product_code)),",
            " GREATEST(wp.gmt_updated,kw.gmt_updated,kp.gmt_updated,cp.gmt_updated),1,cp.id",
            " FROM operations_competitor_watch_product wp",
            " JOIN operations_competitor_keyword kw ON kw.watch_product_id=wp.id",
            "  AND kw.status='ACTIVE' AND kw.is_deleted=b'0'",
            " JOIN operations_competitor_keyword_product kp ON kp.keyword_id=kw.id",
            "  AND kp.relation_status&lt;&gt;'IGNORED' AND kp.is_deleted=b'0'",
            " JOIN operations_competitor_product cp ON cp.id=kp.competitor_product_id",
            "  AND cp.watch_product_id=wp.id AND cp.review_status='CONFIRMED' AND cp.is_deleted=b'0'",
            " WHERE wp.status='ACTIVE' AND wp.is_deleted=b'0'",
            "  AND NULLIF(TRIM(wp.self_noon_product_code),'') IS NOT NULL",
            "  AND NULLIF(TRIM(cp.noon_product_code),'') IS NOT NULL",
            ") target",
            "<if test='afterOwnerUserId != null'>",
            "WHERE (target.ownerUserId&gt;#{afterOwnerUserId}",
            " OR (target.ownerUserId=#{afterOwnerUserId} AND target.watchProductId&gt;#{afterWatchProductId})",
            " OR (target.ownerUserId=#{afterOwnerUserId} AND target.watchProductId=#{afterWatchProductId}",
            "  AND target.keywordId&gt;#{afterKeywordId})",
            " OR (target.ownerUserId=#{afterOwnerUserId} AND target.watchProductId=#{afterWatchProductId}",
            "  AND target.keywordId=#{afterKeywordId} AND target.memberOrder&gt;#{afterMemberOrder})",
            " OR (target.ownerUserId=#{afterOwnerUserId} AND target.watchProductId=#{afterWatchProductId}",
            "  AND target.keywordId=#{afterKeywordId} AND target.memberOrder=#{afterMemberOrder}",
            "  AND target.memberId&gt;#{afterMemberId}))",
            "</if>",
            "ORDER BY target.ownerUserId,target.watchProductId,target.keywordId,target.memberOrder,target.memberId",
            "LIMIT #{limit}","</script>"})
    List<Dp08KeywordScopeRow> listKeywordMembersAfter(
            @Param("afterOwnerUserId") Long owner,@Param("afterWatchProductId") Long watch,
            @Param("afterKeywordId") Long keyword,@Param("afterMemberOrder") Integer order,
            @Param("afterMemberId") Long memberId,@Param("limit") int limit);

    @Select({"<script>",
            "SELECT target.ownerUserId,target.logicalStoreId,target.storeCode,target.siteCode,",
            "target.noonProductCode,target.watchProductId,target.competitorProductId,target.sourceUpdatedAtUtc",
            "FROM (",
            " SELECT wp.owner_user_id ownerUserId,wp.logical_store_id logicalStoreId,",
            " UPPER(wp.store_code) storeCode,UPPER(wp.site_code) siteCode,",
            " UPPER(TRIM(wp.self_noon_product_code)) noonProductCode,wp.id watchProductId,",
            " NULL competitorProductId,wp.gmt_updated sourceUpdatedAtUtc,0 memberId",
            " FROM operations_competitor_watch_product wp",
            " WHERE wp.status='ACTIVE' AND wp.is_deleted=b'0'",
            "  AND NULLIF(TRIM(wp.self_noon_product_code),'') IS NOT NULL",
            " UNION ALL",
            " SELECT wp.owner_user_id,wp.logical_store_id,UPPER(wp.store_code),UPPER(wp.site_code),",
            " UPPER(TRIM(cp.noon_product_code)),wp.id,cp.id,GREATEST(wp.gmt_updated,cp.gmt_updated),cp.id",
            " FROM operations_competitor_watch_product wp",
            " JOIN operations_competitor_product cp ON cp.watch_product_id=wp.id",
            "  AND cp.review_status='CONFIRMED' AND cp.is_deleted=b'0'",
            " WHERE wp.status='ACTIVE' AND wp.is_deleted=b'0'",
            "  AND NULLIF(TRIM(cp.noon_product_code),'') IS NOT NULL",
            "  AND UPPER(TRIM(cp.noon_product_code))&lt;&gt;COALESCE(UPPER(TRIM(wp.self_noon_product_code)),'')",
            ") target",
            "WHERE (target.noonProductCode LIKE 'Z%' OR target.noonProductCode LIKE 'N%')",
            "<if test='afterOwnerUserId != null'>",
            " AND (target.ownerUserId&gt;#{afterOwnerUserId}",
            " OR (target.ownerUserId=#{afterOwnerUserId} AND BINARY target.storeCode&gt;BINARY #{afterStoreCode})",
            " OR (target.ownerUserId=#{afterOwnerUserId} AND BINARY target.storeCode=BINARY #{afterStoreCode}",
            "  AND BINARY target.siteCode&gt;BINARY #{afterSiteCode})",
            " OR (target.ownerUserId=#{afterOwnerUserId} AND BINARY target.storeCode=BINARY #{afterStoreCode}",
            "  AND BINARY target.siteCode=BINARY #{afterSiteCode}",
            "  AND BINARY target.noonProductCode&gt;BINARY #{afterNoonProductCode})",
            " OR (target.ownerUserId=#{afterOwnerUserId} AND BINARY target.storeCode=BINARY #{afterStoreCode}",
            "  AND BINARY target.siteCode=BINARY #{afterSiteCode}",
            "  AND BINARY target.noonProductCode=BINARY #{afterNoonProductCode}",
            "  AND target.watchProductId&gt;#{afterWatchProductId})",
            " OR (target.ownerUserId=#{afterOwnerUserId} AND BINARY target.storeCode=BINARY #{afterStoreCode}",
            "  AND BINARY target.siteCode=BINARY #{afterSiteCode}",
            "  AND BINARY target.noonProductCode=BINARY #{afterNoonProductCode}",
            "  AND target.watchProductId=#{afterWatchProductId} AND target.memberId&gt;#{afterMemberId}))",
            "</if>",
            "ORDER BY target.ownerUserId,BINARY target.storeCode,BINARY target.siteCode,",
            "BINARY target.noonProductCode,target.watchProductId,target.memberId LIMIT #{limit}","</script>"})
    List<Dp08ListTargetRow> listTargetMembersAfter(
            @Param("afterOwnerUserId") Long owner,@Param("afterStoreCode") String store,
            @Param("afterSiteCode") String site,@Param("afterNoonProductCode") String code,
            @Param("afterWatchProductId") Long watch,@Param("afterMemberId") Long memberId,
            @Param("limit") int limit);
}
