package com.nuono.next.infrastructure.mapper;

import com.nuono.next.foundation.FoundationStats;
import com.nuono.next.foundation.FoundationUserDetail;
import com.nuono.next.foundation.FoundationUserHierarchyRow;
import com.nuono.next.foundation.FoundationUserSnapshot;
import com.nuono.next.foundation.FoundationUserStoreLink;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface FoundationOverviewMapper {

    @Select({
            "SELECT",
            "  (SELECT COUNT(*) FROM role WHERE is_deleted = 0) AS role_count,",
            "  (SELECT COUNT(*) FROM `user` WHERE is_deleted = 0) AS user_count,",
            "  (SELECT COUNT(*) FROM `user` WHERE is_deleted = 0 AND status = 1) AS active_user_count,",
            "  (SELECT COUNT(*) FROM user_project WHERE is_deleted = 0) AS store_link_count,",
            "  (SELECT COUNT(*) FROM user_project WHERE is_deleted = 0 AND is_authorized = 1) AS authorized_store_count,",
            "  (SELECT COUNT(*)",
            "     FROM user_project",
            "    WHERE is_deleted = 0",
            "      AND bind_status = 1) AS noon_binding_user_count"
    })
    FoundationStats selectStats();

    @Select({
            "<script>",
            "SELECT",
            "  u.id,",
            "  u.account_no,",
            "  u.real_name,",
            "  u.phone,",
            "  u.account_type,",
            "  u.company_name,",
            "  u.status,",
            "  r.name AS role_name,",
            "  COALESCE(store_stats.store_count, 0) AS store_count,",
            "  COALESCE(store_stats.authorized_store_count, 0) AS authorized_store_count,",
            "  COALESCE(store_stats.sites, '') AS sites,",
            "  CASE",
            "    WHEN COALESCE(store_stats.bound_store_count, 0) > 0 THEN 'PROJECT_BOUND'",
            "    WHEN COALESCE(store_stats.store_count, 0) > 0 THEN 'ACCOUNT_ONLY'",
            "    ELSE 'UNBOUND'",
            "  END AS binding_status",
            "FROM `user` u",
            "LEFT JOIN role r ON r.id = u.role_id AND r.is_deleted = 0",
            "LEFT JOIN (",
            "  SELECT",
            "    visible.scope_user_id AS user_id,",
            "    COUNT(DISTINCT id) AS store_count,",
            "    COUNT(DISTINCT CASE WHEN is_authorized = 1 THEN id END) AS authorized_store_count,",
            "    COUNT(DISTINCT CASE WHEN bind_status = 1 THEN id END) AS bound_store_count,",
            "    GROUP_CONCAT(DISTINCT site ORDER BY site SEPARATOR ', ') AS sites",
            "  FROM (",
            "    SELECT up.user_id AS scope_user_id, up.id, up.is_authorized, up.bind_status, us.site",
            "    FROM user_project up",
            "    LEFT JOIN user_store us ON us.user_id = up.user_id AND us.project_code = up.project_code AND us.is_deleted = 0",
            "    WHERE up.is_deleted = 0",
            "    UNION ALL",
            "    SELECT upa.user_id AS scope_user_id, up.id, up.is_authorized, up.bind_status, us.site",
            "    FROM user_project_access upa",
            "    JOIN user_project up ON up.id = upa.project_id AND up.is_deleted = 0",
            "    LEFT JOIN user_store us ON us.user_id = up.user_id AND us.project_code = up.project_code AND us.is_deleted = 0",
            "    WHERE upa.is_deleted = 0",
            "  ) visible",
            "  GROUP BY visible.scope_user_id",
            ") store_stats ON store_stats.user_id = u.id",
            "WHERE u.is_deleted = 0",
            "ORDER BY u.gmt_updated DESC, u.id DESC",
            "LIMIT #{limit}",
            "</script>"
    })
    List<FoundationUserSnapshot> listSampleUsers(@Param("limit") int limit);

    @Select({
            "SELECT",
            "  u.id,",
            "  u.account_no,",
            "  u.real_name,",
            "  u.phone,",
            "  u.email,",
            "  u.company_name,",
            "  u.status,",
            "  u.account_type,",
            "  u.role_id,",
            "  r.name AS role_name,",
            "  r.level AS role_level,",
            "  r.is_system AS system_role,",
            "  u.list_limit,",
            "  u.collect_limit,",
            "  u.wh_ap_limit,",
            "  u.chatgpt_translate_limit,",
            "  COALESCE(store_stats.store_count, 0) AS store_count,",
            "  COALESCE(store_stats.authorized_store_count, 0) AS authorized_store_count,",
            "  COALESCE(store_stats.sites, '') AS sites,",
            "  COALESCE(role_menu_stats.role_menu_count, 0) AS role_menu_count,",
            "  COALESCE(user_menu_stats.user_menu_count, 0) AS user_menu_count,",
            "  CASE",
            "    WHEN COALESCE(store_stats.bound_store_count, 0) > 0 THEN 'PROJECT_BOUND'",
            "    WHEN COALESCE(store_stats.store_count, 0) > 0 THEN 'ACCOUNT_ONLY'",
            "    ELSE 'UNBOUND'",
            "  END AS binding_status,",
            "  project_credential.noon_partner_user,",
            "  project_credential.noon_partner_project_user,",
            "  project_credential.noon_partner_id,",
            "  project_credential.noon_partner_user_code,",
            "  project_credential.noon_partner_mail_auth_code,",
            "  DATE_FORMAT(project_credential.cookie_generate_time, '%Y-%m-%d %H:%i:%s') AS cookie_generate_time,",
            "  DATE_FORMAT(u.effective_time, '%Y-%m-%d %H:%i:%s') AS effective_time,",
            "  DATE_FORMAT(u.expired_time, '%Y-%m-%d %H:%i:%s') AS expired_time",
            "FROM `user` u",
            "LEFT JOIN role r ON r.id = u.role_id AND r.is_deleted = 0",
            "LEFT JOIN (",
            "  SELECT",
            "    visible.scope_user_id AS user_id,",
            "    COUNT(DISTINCT id) AS store_count,",
            "    COUNT(DISTINCT CASE WHEN is_authorized = 1 THEN id END) AS authorized_store_count,",
            "    COUNT(DISTINCT CASE WHEN bind_status = 1 THEN id END) AS bound_store_count,",
            "    GROUP_CONCAT(DISTINCT site ORDER BY site SEPARATOR ', ') AS sites",
            "  FROM (",
            "    SELECT up.user_id AS scope_user_id, up.id, up.is_authorized, up.bind_status, us.site",
            "    FROM user_project up",
            "    LEFT JOIN user_store us ON us.user_id = up.user_id AND us.project_code = up.project_code AND us.is_deleted = 0",
            "    WHERE up.is_deleted = 0",
            "    UNION ALL",
            "    SELECT upa.user_id AS scope_user_id, up.id, up.is_authorized, up.bind_status, us.site",
            "    FROM user_project_access upa",
            "    JOIN user_project up ON up.id = upa.project_id AND up.is_deleted = 0",
            "    LEFT JOIN user_store us ON us.user_id = up.user_id AND us.project_code = up.project_code AND us.is_deleted = 0",
            "    WHERE upa.is_deleted = 0",
            "  ) visible",
            "  GROUP BY visible.scope_user_id",
            ") store_stats ON store_stats.user_id = u.id",
            "LEFT JOIN (",
            "  SELECT",
            "    user_id,",
            "    MAX(NULLIF(noon_partner_user, '')) AS noon_partner_user,",
            "    MAX(NULLIF(noon_partner_project_user, '')) AS noon_partner_project_user,",
            "    MAX(NULLIF(noon_partner_id, '')) AS noon_partner_id,",
            "    MAX(NULLIF(noon_partner_user_code, '')) AS noon_partner_user_code,",
            "    MAX(NULLIF(noon_partner_mail_auth_code, '')) AS noon_partner_mail_auth_code,",
            "    MAX(cookie_generate_time) AS cookie_generate_time",
            "  FROM user_project",
            "  WHERE is_deleted = 0",
            "  GROUP BY user_id",
            ") project_credential ON project_credential.user_id = u.id",
            "LEFT JOIN (",
            "  SELECT role_id, COUNT(*) AS role_menu_count",
            "  FROM role_menu",
            "  WHERE is_deleted = 0",
            "  GROUP BY role_id",
            ") role_menu_stats ON role_menu_stats.role_id = u.role_id",
            "LEFT JOIN (",
            "  SELECT user_id, COUNT(*) AS user_menu_count",
            "  FROM user_menu",
            "  WHERE is_deleted = 0 AND status = 1",
            "  GROUP BY user_id",
            ") user_menu_stats ON user_menu_stats.user_id = u.id",
            "WHERE u.id = #{userId}",
            "  AND u.is_deleted = 0",
            "LIMIT 1"
    })
    FoundationUserDetail selectUserDetail(@Param("userId") Long userId);

    @Select({
            "SELECT",
            "  visible.id,",
            "  visible.user_id AS userId,",
            "  visible.org_code,",
            "  visible.org_name,",
            "  visible.project_code,",
            "  visible.project_name,",
            "  visible.project_code AS store_code,",
            "  NULL AS site,",
            "  visible.is_authorized AS authorized,",
            "  visible.bind_status AS bindStatus,",
            "  visible.noon_partner_user AS noonPartnerUser,",
            "  visible.noon_partner_project_user AS noonPartnerProjectUser,",
            "  visible.noon_partner_id AS noonPartnerId,",
            "  visible.list_limit AS listLimit,",
            "  visible.collect_limit AS collectLimit,",
            "  visible.wh_ap_limit AS whApLimit,",
            "  visible.chatgpt_translate_limit AS chatgptTranslateLimit",
            "FROM (",
            "  SELECT up.id, up.user_id, up.org_code, up.org_name, up.project_code, up.project_name, up.is_authorized,",
            "         up.bind_status, up.noon_partner_user, up.noon_partner_project_user, up.noon_partner_id,",
            "         up.list_limit, up.collect_limit, up.wh_ap_limit, up.chatgpt_translate_limit",
            "  FROM user_project up",
            "  WHERE up.user_id = #{userId}",
            "    AND up.is_deleted = 0",
            "  UNION",
            "  SELECT up.id, upa.user_id, up.org_code, up.org_name, up.project_code, up.project_name, up.is_authorized,",
            "         up.bind_status, up.noon_partner_user, up.noon_partner_project_user, up.noon_partner_id,",
            "         up.list_limit, up.collect_limit, up.wh_ap_limit, up.chatgpt_translate_limit",
            "  FROM user_project_access upa",
            "  JOIN user_project up ON up.id = upa.project_id AND up.is_deleted = 0",
            "  WHERE upa.user_id = #{userId}",
            "    AND upa.is_deleted = 0",
            ") visible",
            "ORDER BY visible.project_code ASC, visible.id ASC"
    })
    List<FoundationUserStoreLink> listUserStoreLinks(@Param("userId") Long userId);

    @Select({
            "SELECT",
            "  id,",
            "  created_by AS createdBy,",
            "  account_no AS accountNo,",
            "  real_name AS realName",
            "FROM `user`",
            "WHERE is_deleted = 0",
            "ORDER BY id ASC"
    })
    List<FoundationUserHierarchyRow> listUserHierarchyRows();

    @Select({
            "SELECT",
            "  visible.id,",
            "  visible.scope_user_id AS userId,",
            "  visible.org_code AS orgCode,",
            "  visible.org_name AS orgName,",
            "  visible.project_code AS projectCode,",
            "  visible.project_name AS projectName,",
            "  visible.project_code AS storeCode,",
            "  NULL AS site,",
            "  visible.is_authorized AS authorized,",
            "  visible.bind_status AS bindStatus,",
            "  visible.noon_partner_user AS noonPartnerUser,",
            "  visible.noon_partner_project_user AS noonPartnerProjectUser,",
            "  visible.noon_partner_id AS noonPartnerId,",
            "  visible.list_limit AS listLimit,",
            "  visible.collect_limit AS collectLimit,",
            "  visible.wh_ap_limit AS whApLimit,",
            "  visible.chatgpt_translate_limit AS chatgptTranslateLimit,",
            "  u.account_no AS ownerAccountNo,",
            "  u.real_name AS ownerRealName",
            "FROM (",
            "  SELECT up.id, up.user_id AS scope_user_id, up.user_id AS owner_user_id, up.org_code, up.org_name, up.project_code, up.project_name, up.is_authorized,",
            "         up.bind_status, up.noon_partner_user, up.noon_partner_project_user, up.noon_partner_id,",
            "         up.list_limit, up.collect_limit, up.wh_ap_limit, up.chatgpt_translate_limit",
            "  FROM user_project up",
            "  WHERE up.is_deleted = 0",
            "  UNION ALL",
            "  SELECT up.id, upa.user_id AS scope_user_id, up.user_id AS owner_user_id, up.org_code, up.org_name, up.project_code, up.project_name, up.is_authorized,",
            "         up.bind_status, up.noon_partner_user, up.noon_partner_project_user, up.noon_partner_id,",
            "         up.list_limit, up.collect_limit, up.wh_ap_limit, up.chatgpt_translate_limit",
            "  FROM user_project_access upa",
            "  JOIN user_project up ON up.id = upa.project_id AND up.is_deleted = 0",
            "  WHERE upa.is_deleted = 0",
            ") visible",
            "LEFT JOIN `user` u ON u.id = visible.owner_user_id AND u.is_deleted = 0",
            "ORDER BY visible.scope_user_id ASC, visible.project_code ASC, visible.id ASC"
    })
    List<FoundationUserStoreLink> listAllUserStoreLinks();
}
