package com.nuono.next.infrastructure.mapper;

public interface InTransitGoodsSql {

    String LINE_LEGACY_PSKU_ALIAS = "CASE WHEN line.psku REGEXP '^[A-Za-z]+B[0-9]+$' "
            + "THEN CONCAT(REGEXP_REPLACE(line.psku, 'B[0-9]+$', '', 1, 1, 'c'), "
            + "REGEXP_SUBSTR(line.psku, '[0-9]+$')) ELSE line.psku END";

    String FORWARDER_SELECT = ""
            + "SELECT id, owner_user_id, forwarder_code, forwarder_name, status, created_by, updated_by "
            + "FROM in_transit_forwarder ";

    String ALIAS_SELECT = ""
            + "SELECT alias.id, alias.owner_user_id, alias.standard_forwarder_id, alias.raw_forwarder_name, "
            + "alias.normalized_raw_forwarder_name, alias.status, alias.created_by, alias.updated_by, "
            + "forwarder.forwarder_code AS standard_forwarder_code, forwarder.forwarder_name AS standard_forwarder_name "
            + "FROM in_transit_forwarder_alias alias "
            + "LEFT JOIN in_transit_forwarder forwarder ON forwarder.id = alias.standard_forwarder_id "
            + "AND forwarder.owner_user_id = alias.owner_user_id AND forwarder.is_deleted = b'0' ";

    String BATCH_SELECT = ""
            + "SELECT batch.id, batch.owner_user_id, batch.standard_forwarder_id, "
            + "forwarder.forwarder_code AS standard_forwarder_code, forwarder.forwarder_name AS standard_forwarder_name, "
            + "batch.raw_forwarder_name, batch.normalized_raw_forwarder_name, batch.forwarder_quality_status, "
            + "batch.transport_mode, batch.batch_status, batch.target_store_code, batch.target_site_code, batch.target_warehouse_name, "
            + "batch.departure_date, batch.eta_date, batch.external_shipment_no, batch.source_created_at, "
            + "batch.estimated_departure_at, batch.estimated_arrival_at, batch.estimated_arrival_source, "
            + "batch.estimated_arrival_source_detail, batch.estimated_arrival_updated_at, batch.estimated_arrival_updated_by, "
            + "batch.delivery_appointment_text, "
            + "(SELECT domestic.node_happened_at FROM in_transit_logistics_node domestic "
            + "WHERE domestic.owner_user_id = batch.owner_user_id AND domestic.batch_id = batch.id "
            + "AND domestic.node_status = 'handed_to_forwarder' AND domestic.description = '国内收货' "
            + "AND domestic.is_deleted = b'0' "
            + "ORDER BY domestic.node_happened_at ASC, domestic.id ASC LIMIT 1) AS domestic_received_at, "
            + "batch.tracking_no, batch.container_no, batch.batch_reference_no, "
            + "batch.missing_fields_json, batch.box_count, batch.sku_count, batch.shipped_quantity_total, batch.received_quantity_total, "
            + "batch.remaining_quantity_total, batch.carton_count_total, batch.total_weight_kg, batch.total_volume_cbm, "
            + "batch.latest_node_status, batch.latest_node_happened_at, batch.latest_node_description, "
            + "(SELECT received.node_happened_at FROM in_transit_logistics_node received "
            + "WHERE received.owner_user_id = batch.owner_user_id AND received.batch_id = batch.id "
            + "AND received.node_status = 'warehouse_received' AND received.is_deleted = b'0' "
            + "ORDER BY received.node_happened_at DESC, received.id DESC LIMIT 1) AS actual_arrival_at, "
            + "batch.gmt_create AS created_at, batch.created_by, batch.updated_by "
            + "FROM in_transit_batch batch "
            + "LEFT JOIN in_transit_forwarder forwarder ON forwarder.id = batch.standard_forwarder_id "
            + "AND forwarder.owner_user_id = batch.owner_user_id AND forwarder.is_deleted = b'0' ";

    String BATCH_FILTER_CONDITIONS = ""
            + "WHERE batch.owner_user_id = #{query.ownerUserId} AND batch.is_deleted = b'0' "
            + "<if test='query.standardForwarderId != null'> AND batch.standard_forwarder_id = #{query.standardForwarderId}</if> "
            + "<if test='query.rawForwarderName != null and query.rawForwarderName != \"\"'> AND batch.raw_forwarder_name LIKE CONCAT('%', #{query.rawForwarderName}, '%')</if> "
            + "<if test='query.transportMode != null and query.transportMode != \"\"'> AND batch.transport_mode = #{query.transportMode}</if> "
            + "<if test='query.targetStoreCode != null and query.targetStoreCode != \"\"'> AND batch.target_store_code = #{query.targetStoreCode}</if> "
            + "<if test='query.targetSiteCode != null and query.targetSiteCode != \"\"'> AND batch.target_site_code = #{query.targetSiteCode}</if> "
            + "<if test='query.accessScopeRestricted'> "
            + "AND ( "
            + "(batch.target_store_code IS NULL OR batch.target_store_code = '' OR batch.target_site_code IS NULL OR batch.target_site_code = '') "
            + "<if test='query.allowedStoreSites != null and query.allowedStoreSites.size() > 0'> "
            + "OR "
            + "<foreach collection='query.allowedStoreSites' item='scope' separator=' OR '> "
            + "(batch.target_store_code = #{scope.storeCode} AND batch.target_site_code = #{scope.siteCode}) "
            + "</foreach> "
            + "</if> "
            + ") "
            + "</if> "
            + "<if test='query.targetWarehouseName != null and query.targetWarehouseName != \"\"'> AND batch.target_warehouse_name LIKE CONCAT('%', #{query.targetWarehouseName}, '%')</if> "
            + "<if test='query.batchStatus != null and query.batchStatus != \"\"'> AND batch.batch_status = #{query.batchStatus}</if> "
            + "<if test='(query.batchStatus == null or query.batchStatus == \"\") and query.statusScope == \"active\"'> "
            + "AND batch.batch_status NOT IN ('warehouse_received', 'completed', 'cancelled') "
            + "</if> "
            + "<if test='(query.batchStatus == null or query.batchStatus == \"\") and query.statusScope == \"completed\"'> "
            + "AND batch.batch_status IN ('warehouse_received', 'completed', 'cancelled') "
            + "</if> "
            + "<if test='query.skuKeyword != null and query.skuKeyword != \"\"'> "
            + "AND EXISTS ( "
            + "SELECT 1 FROM in_transit_goods_line line "
            + "WHERE line.owner_user_id = batch.owner_user_id AND line.batch_id = batch.id AND line.is_deleted = b'0' "
            + "AND (line.sku LIKE CONCAT('%', #{query.skuKeyword}, '%') "
            + "OR line.msku LIKE CONCAT('%', #{query.skuKeyword}, '%') "
            + "OR line.psku LIKE CONCAT('%', #{query.skuKeyword}, '%')) "
            + ") "
            + "</if> "
            + "<if test='query.etaFrom != null'> AND batch.eta_date &gt;= #{query.etaFrom}</if> "
            + "<if test='query.etaTo != null'> AND batch.eta_date &lt;= #{query.etaTo}</if> "
            + "<if test='query.todo == \"missingEstimatedArrival\"'> "
            + "AND batch.estimated_arrival_at IS NULL AND batch.eta_date IS NULL "
            + "AND batch.batch_status NOT IN ('warehouse_received', 'completed', 'cancelled') "
            + "AND (batch.latest_node_status IS NULL OR batch.latest_node_status NOT IN ('warehouse_received', 'cancelled')) "
            + "AND NOT EXISTS ( "
            + "SELECT 1 FROM in_transit_logistics_node received "
            + "WHERE received.owner_user_id = batch.owner_user_id AND received.batch_id = batch.id "
            + "AND received.node_status = 'warehouse_received' AND received.is_deleted = b'0' "
            + ") "
            + "</if> ";

    String LINE_SELECT = ""
            + "SELECT line.id, line.owner_user_id, line.batch_id, line.package_id, line.box_no, line.sku, line.msku, line.psku, "
            + "line.product_name, line.store_code, line.site_code, line.shipped_quantity, line.received_quantity, "
            + "line.remaining_quantity, line.carton_count, line.units_per_carton, line.carton_weight_kg, line.carton_volume_cbm, "
            + "line.created_by, line.updated_by, "
            + "pkg.external_box_no AS external_box_no, pkg.tracking_no AS package_tracking_no, "
            + "pkg.weight_kg AS package_weight_kg, pkg.length_cm AS package_length_cm, "
            + "pkg.width_cm AS package_width_cm, pkg.height_cm AS package_height_cm, pkg.volume_cbm AS package_volume_cbm, "
            + "pkg.volume_weight_kg AS package_volume_weight_kg, pkg.chargeable_weight_kg AS package_chargeable_weight_kg, "
            + "pkg.measured_weight_kg AS measured_weight_kg, pkg.measured_length_cm AS measured_length_cm, "
            + "pkg.measured_width_cm AS measured_width_cm, pkg.measured_height_cm AS measured_height_cm, "
            + "pkg.measured_volume_cbm AS measured_volume_cbm, pkg.package_status AS package_status, "
            + "pkg.logistics_status AS logistics_status, "
            + "pm.id AS matched_product_id, pm.sku_parent AS product_sku_parent, "
            + "pm.title_cache AS product_title, pm.cover_image_url AS product_image_url "
            + "FROM in_transit_goods_line line "
            + "LEFT JOIN in_transit_package pkg ON pkg.owner_user_id = line.owner_user_id "
            + "AND pkg.batch_id = line.batch_id AND pkg.id = line.package_id AND pkg.is_deleted = b'0' "
            + "LEFT JOIN product_master pm ON pm.id = COALESCE("
            + "(SELECT exact_pm.id "
            + "FROM logical_store_site exact_lss "
            + "JOIN logical_store exact_ls ON exact_ls.id = exact_lss.logical_store_id "
            + "AND exact_ls.owner_user_id = line.owner_user_id AND exact_ls.is_deleted = b'0' "
            + "JOIN product_site_offer exact_pso ON exact_pso.site_id = exact_lss.id "
            + "AND exact_pso.is_deleted = b'0' "
            + "JOIN product_variant exact_pv ON exact_pv.id = exact_pso.variant_id "
            + "AND exact_pv.partner_sku IN (line.psku, " + LINE_LEGACY_PSKU_ALIAS + ") "
            + "AND exact_pv.is_deleted = b'0' "
            + "JOIN product_master exact_pm ON exact_pm.id = exact_pv.product_master_id "
            + "AND exact_pm.logical_store_id = exact_ls.id AND exact_pm.is_deleted = b'0' "
            + "WHERE exact_lss.store_code = line.store_code "
            + "AND exact_lss.site = line.site_code AND exact_lss.is_deleted = b'0' "
            + "ORDER BY exact_pm.cover_image_url IS NULL ASC, exact_pm.gmt_updated DESC, exact_pm.id DESC "
            + "LIMIT 1), "
            + "(SELECT fallback_pm.id "
            + "FROM logical_store fallback_ls "
            + "JOIN product_master fallback_pm ON fallback_pm.logical_store_id = fallback_ls.id "
            + "AND fallback_pm.is_deleted = b'0' "
            + "JOIN product_variant fallback_pv ON fallback_pv.product_master_id = fallback_pm.id "
            + "AND fallback_pv.partner_sku IN (line.psku, " + LINE_LEGACY_PSKU_ALIAS + ") "
            + "AND fallback_pv.is_deleted = b'0' "
            + "WHERE fallback_ls.owner_user_id = line.owner_user_id AND fallback_ls.is_deleted = b'0' "
            + "ORDER BY CASE WHEN fallback_pv.partner_sku = line.psku THEN 0 ELSE 1 END, "
            + "fallback_pm.cover_image_url IS NULL ASC, fallback_pm.gmt_updated DESC, fallback_pm.id DESC "
            + "LIMIT 1)) "
            + "AND pm.is_deleted = b'0' ";

    String PACKAGE_SELECT = ""
            + "SELECT id, owner_user_id, batch_id, box_no, external_box_no, tracking_no, "
            + "weight_kg, length_cm, width_cm, height_cm, volume_cbm, "
            + "volume_weight_kg, chargeable_weight_kg, "
            + "measured_weight_kg, measured_length_cm, measured_width_cm, measured_height_cm, measured_volume_cbm, "
            + "package_status, logistics_status, created_by, updated_by "
            + "FROM in_transit_package ";

    String NODE_SELECT = ""
            + "SELECT id, owner_user_id, batch_id, node_status, node_happened_at, description, operator_name, created_by, updated_by "
            + "FROM in_transit_logistics_node ";
}
