package com.nuono.next.infrastructure.mapper;

import com.nuono.next.noonads.NoonAdvertisingCampaignFact;
import com.nuono.next.noonads.NoonAdvertisingCampaignRow;
import com.nuono.next.noonads.NoonAdvertisingDashboardQuery;
import com.nuono.next.noonads.NoonAdvertisingDataStatus;
import com.nuono.next.noonads.NoonAdvertisingLatestReportWindowView;
import com.nuono.next.noonads.NoonAdvertisingProductRow;
import com.nuono.next.noonads.NoonAdvertisingQueryFact;
import com.nuono.next.noonads.NoonAdvertisingQueryRow;
import com.nuono.next.noonads.NoonAdvertisingReportBatch;
import com.nuono.next.noonads.NoonAdvertisingSalesSummaryView;
import com.nuono.next.noonads.NoonAdvertisingScopeQuery;
import com.nuono.next.noonads.NoonAdvertisingSummaryView;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;

public interface NoonAdvertisingMapper {

    @Insert({
            "INSERT INTO noon_ad_id_sequence (sequence_name, next_id, gmt_create, gmt_updated)",
            "VALUES (#{sequenceName}, LAST_INSERT_ID(#{initialValue} + 1), NOW(), NOW())",
            "ON DUPLICATE KEY UPDATE",
            "  next_id = LAST_INSERT_ID(next_id + 1),",
            "  gmt_updated = NOW()"
    })
    @SelectKey(
            statement = "SELECT LAST_INSERT_ID()",
            keyProperty = "allocatedId",
            before = false,
            resultType = Long.class
    )
    void nextId(IdSequenceCommand command);

    default Long nextReportBatchId() {
        return nextNoonAdvertisingId("noon_ad_report_batch", 200000L);
    }

    default Long nextCampaignFactId() {
        return nextNoonAdvertisingId("noon_ad_campaign_fact", 210000L);
    }

    default Long nextQueryFactId() {
        return nextNoonAdvertisingId("noon_ad_query_fact", 220000L);
    }

    default Long nextNoonAdvertisingId(String sequenceName, Long initialValue) {
        IdSequenceCommand command = new IdSequenceCommand(sequenceName, initialValue);
        nextId(command);
        Long id = command.getAllocatedId();
        if (id == null || id <= 0) {
            throw new IllegalStateException("Noon advertising ID allocation failed: " + sequenceName);
        }
        return id;
    }

    @Insert({
            "INSERT INTO noon_ad_report_batch (",
            "  id, source_system, source_name, source_digest_sha256, owner_user_id, project_code,",
            "  store_code, site_code, report_date_from, report_date_to, status,",
            "  campaign_row_count, query_row_count, notes, created_by, updated_by, gmt_create, gmt_updated",
            ") VALUES (",
            "  #{id}, #{sourceSystem}, #{sourceName}, #{sourceDigestSha256}, #{ownerUserId}, #{projectCode},",
            "  #{storeCode}, #{siteCode}, #{reportDateFrom}, #{reportDateTo}, #{status},",
            "  #{campaignRowCount}, #{queryRowCount}, #{notes}, #{createdBy}, #{updatedBy}, NOW(), NOW()",
            ")"
    })
    int insertReportBatch(NoonAdvertisingReportBatch batch);

    @Select({
            "<script>",
            "SELECT id",
            "FROM noon_ad_report_batch",
            "WHERE source_system = #{batch.sourceSystem}",
            "  AND owner_user_id = #{batch.ownerUserId}",
            "  AND project_code = #{batch.projectCode}",
            "  AND store_code = #{batch.storeCode}",
            "  AND site_code = #{batch.siteCode}",
            "  AND report_date_from = #{batch.reportDateFrom}",
            "  AND report_date_to = #{batch.reportDateTo}",
            "  AND source_digest_sha256 = #{batch.sourceDigestSha256}",
            "ORDER BY id ASC",
            "LIMIT 1",
            "</script>"
    })
    Long findReportBatchId(@Param("batch") NoonAdvertisingReportBatch batch);

    @Select({
            "<script>",
            "SELECT",
            "  TRUE AS dataAvailable,",
            "  report_date_from AS dateFrom,",
            "  report_date_to AS dateTo",
            "FROM noon_ad_report_batch",
            "WHERE owner_user_id = #{query.ownerUserId}",
            "  AND project_code = #{query.projectCode}",
            "  AND store_code = #{query.storeCode}",
            "  AND site_code = #{query.siteCode}",
            "  AND status = 'imported'",
            "ORDER BY report_date_to DESC, DATEDIFF(report_date_to, report_date_from) DESC, id DESC",
            "LIMIT 1",
            "</script>"
    })
    NoonAdvertisingLatestReportWindowView selectLatestReportWindow(@Param("query") NoonAdvertisingScopeQuery query);

    @Insert({
            "INSERT INTO noon_ad_campaign_fact (",
            "  id, batch_id, source_system, owner_user_id, project_code, store_code, site_code,",
            "  report_date_from, report_date_to, campaign_code, campaign_name, campaign_status, qc_status,",
            "  adgroup_code, campaign_start_date, campaign_end_date, views, clicks, orders_count,",
            "  assisted_orders, atc_count, spend_amount, ad_revenue, ctr_percentage, roas, cpc, cps,",
            "  cvr_percentage, zero_order_spend_amount, zero_order_spend_share, raw_payload_json,",
            "  gmt_create, gmt_updated",
            ") VALUES (",
            "  #{id}, #{batchId}, #{sourceSystem}, #{ownerUserId}, #{projectCode}, #{storeCode}, #{siteCode},",
            "  #{reportDateFrom}, #{reportDateTo}, #{campaignCode}, #{campaignName}, #{campaignStatus}, #{qcStatus},",
            "  #{adgroupCode}, #{campaignStartDate}, #{campaignEndDate}, #{views}, #{clicks}, #{ordersCount},",
            "  #{assistedOrders}, #{atcCount}, #{spendAmount}, #{adRevenue}, #{ctrPercentage}, #{roas}, #{cpc}, #{cps},",
            "  #{cvrPercentage}, #{zeroOrderSpendAmount}, #{zeroOrderSpendShare}, #{rawPayloadJson},",
            "  NOW(), NOW()",
            ")",
            "ON DUPLICATE KEY UPDATE",
            "  batch_id = VALUES(batch_id),",
            "  campaign_name = VALUES(campaign_name),",
            "  campaign_status = VALUES(campaign_status),",
            "  qc_status = VALUES(qc_status),",
            "  adgroup_code = VALUES(adgroup_code),",
            "  campaign_start_date = VALUES(campaign_start_date),",
            "  campaign_end_date = VALUES(campaign_end_date),",
            "  views = VALUES(views),",
            "  clicks = VALUES(clicks),",
            "  orders_count = VALUES(orders_count),",
            "  assisted_orders = VALUES(assisted_orders),",
            "  atc_count = VALUES(atc_count),",
            "  spend_amount = VALUES(spend_amount),",
            "  ad_revenue = VALUES(ad_revenue),",
            "  ctr_percentage = VALUES(ctr_percentage),",
            "  roas = VALUES(roas),",
            "  cpc = VALUES(cpc),",
            "  cps = VALUES(cps),",
            "  cvr_percentage = VALUES(cvr_percentage),",
            "  zero_order_spend_amount = VALUES(zero_order_spend_amount),",
            "  zero_order_spend_share = VALUES(zero_order_spend_share),",
            "  raw_payload_json = VALUES(raw_payload_json),",
            "  gmt_updated = NOW()"
    })
    int upsertCampaignFact(NoonAdvertisingCampaignFact fact);

    @Insert({
            "INSERT INTO noon_ad_query_fact (",
            "  id, batch_id, source_system, owner_user_id, project_code, store_code, site_code,",
            "  report_date_from, report_date_to, campaign_code, campaign_name, ad_sku_code, partner_sku, query_text, query_hash,",
            "  query_kind, views, clicks, orders_count, assisted_orders, atc_count, spend_amount, ad_revenue,",
            "  ctr_percentage, roas, cpc, cps, cvr_percentage, raw_payload_json, gmt_create, gmt_updated",
            ") VALUES (",
            "  #{id}, #{batchId}, #{sourceSystem}, #{ownerUserId}, #{projectCode}, #{storeCode}, #{siteCode},",
            "  #{reportDateFrom}, #{reportDateTo}, #{campaignCode}, #{campaignName}, #{adSkuCode}, #{partnerSku}, #{queryText}, #{queryHash},",
            "  #{queryKind}, #{views}, #{clicks}, #{ordersCount}, #{assistedOrders}, #{atcCount}, #{spendAmount}, #{adRevenue},",
            "  #{ctrPercentage}, #{roas}, #{cpc}, #{cps}, #{cvrPercentage}, #{rawPayloadJson}, NOW(), NOW()",
            ")",
            "ON DUPLICATE KEY UPDATE",
            "  batch_id = VALUES(batch_id),",
            "  campaign_name = VALUES(campaign_name),",
            "  query_text = VALUES(query_text),",
            "  query_kind = VALUES(query_kind),",
            "  views = VALUES(views),",
            "  clicks = VALUES(clicks),",
            "  orders_count = VALUES(orders_count),",
            "  assisted_orders = VALUES(assisted_orders),",
            "  atc_count = VALUES(atc_count),",
            "  spend_amount = VALUES(spend_amount),",
            "  ad_revenue = VALUES(ad_revenue),",
            "  ctr_percentage = VALUES(ctr_percentage),",
            "  roas = VALUES(roas),",
            "  cpc = VALUES(cpc),",
            "  cps = VALUES(cps),",
            "  cvr_percentage = VALUES(cvr_percentage),",
            "  raw_payload_json = VALUES(raw_payload_json),",
            "  gmt_updated = NOW()"
    })
    int upsertQueryFact(NoonAdvertisingQueryFact fact);

    @Select({
            "<script>",
            "SELECT",
            "  COUNT(DISTINCT campaign_code) AS campaignCount,",
            "  (SELECT COUNT(1)",
            "   FROM noon_ad_query_fact q",
            "   WHERE q.owner_user_id = #{query.ownerUserId}",
            "     AND q.project_code = #{query.projectCode}",
            "     AND q.store_code = #{query.storeCode}",
            "     AND q.site_code = #{query.siteCode}",
            "     AND q.report_date_from = #{query.dateFrom}",
            "     AND q.report_date_to = #{query.dateTo}) AS queryCount,",
            "  COALESCE(SUM(views), 0) AS views,",
            "  COALESCE(SUM(clicks), 0) AS clicks,",
            "  COALESCE(SUM(orders_count), 0) AS ordersCount,",
            "  COALESCE(SUM(assisted_orders), 0) AS assistedOrders,",
            "  COALESCE(SUM(atc_count), 0) AS atcCount,",
            "  COALESCE(SUM(spend_amount), 0) AS spendAmount,",
            "  COALESCE(SUM(ad_revenue), 0) AS adRevenue,",
            "  CASE WHEN COALESCE(SUM(views), 0) = 0 THEN 0 ELSE COALESCE(SUM(clicks), 0) / COALESCE(SUM(views), 0) END AS ctrPercentage,",
            "  CASE WHEN COALESCE(SUM(spend_amount), 0) = 0 THEN 0 ELSE COALESCE(SUM(ad_revenue), 0) / COALESCE(SUM(spend_amount), 0) END AS roas,",
            "  CASE WHEN COALESCE(SUM(clicks), 0) = 0 THEN 0 ELSE COALESCE(SUM(spend_amount), 0) / COALESCE(SUM(clicks), 0) END AS cpc,",
            "  CASE WHEN COALESCE(SUM(orders_count), 0) = 0 THEN 0 ELSE COALESCE(SUM(spend_amount), 0) / COALESCE(SUM(orders_count), 0) END AS cps,",
            "  CASE WHEN COALESCE(SUM(clicks), 0) = 0 THEN 0 ELSE COALESCE(SUM(orders_count), 0) / COALESCE(SUM(clicks), 0) END AS cvrPercentage,",
            "  COALESCE(SUM(zero_order_spend_amount), 0) AS zeroOrderSpendAmount,",
            "  CASE WHEN COALESCE(SUM(spend_amount), 0) = 0 THEN 0 ELSE COALESCE(SUM(zero_order_spend_amount), 0) / COALESCE(SUM(spend_amount), 0) END AS zeroOrderSpendShare",
            "FROM noon_ad_campaign_fact",
            "WHERE owner_user_id = #{query.ownerUserId}",
            "  AND project_code = #{query.projectCode}",
            "  AND store_code = #{query.storeCode}",
            "  AND site_code = #{query.siteCode}",
            "  AND report_date_from = #{query.dateFrom}",
            "  AND report_date_to = #{query.dateTo}",
            "</script>"
    })
    NoonAdvertisingSummaryView selectAdSummary(@Param("query") NoonAdvertisingDashboardQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  COALESCE(SUM(net_units), 0) AS netUnits,",
            "  COALESCE(SUM(revenue_shipped), 0) AS revenueShipped",
            "FROM daily_sales_fact",
            "WHERE owner_user_id = #{query.ownerUserId}",
            "  AND store_code = #{query.storeCode}",
            "  AND site_code = #{query.siteCode}",
            "  AND fact_date &gt;= #{query.dateFrom}",
            "  AND fact_date &lt;= #{query.dateTo}",
            "</script>"
    })
    NoonAdvertisingSalesSummaryView selectSalesSummary(@Param("query") NoonAdvertisingDashboardQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  COUNT(DISTINCT COALESCE(source_digest_sha256, CAST(id AS CHAR))) AS batchCount,",
            "  (SELECT COUNT(1)",
            "   FROM noon_ad_campaign_fact c",
            "   WHERE c.owner_user_id = #{query.ownerUserId}",
            "     AND c.project_code = #{query.projectCode}",
            "     AND c.store_code = #{query.storeCode}",
            "     AND c.site_code = #{query.siteCode}",
            "     AND c.report_date_from = #{query.dateFrom}",
            "     AND c.report_date_to = #{query.dateTo}) AS campaignRowCount,",
            "  (SELECT COUNT(1)",
            "   FROM noon_ad_query_fact q",
            "   WHERE q.owner_user_id = #{query.ownerUserId}",
            "     AND q.project_code = #{query.projectCode}",
            "     AND q.store_code = #{query.storeCode}",
            "     AND q.site_code = #{query.siteCode}",
            "     AND q.report_date_from = #{query.dateFrom}",
            "     AND q.report_date_to = #{query.dateTo}) AS queryRowCount,",
            "  MIN(report_date_from) AS earliestReportDate,",
            "  MAX(report_date_to) AS latestReportDate,",
            "  CASE WHEN COUNT(1) &gt; 0",
            "    OR (SELECT COUNT(1)",
            "        FROM noon_ad_campaign_fact c",
            "        WHERE c.owner_user_id = #{query.ownerUserId}",
            "          AND c.project_code = #{query.projectCode}",
            "          AND c.store_code = #{query.storeCode}",
            "          AND c.site_code = #{query.siteCode}",
            "          AND c.report_date_from = #{query.dateFrom}",
            "          AND c.report_date_to = #{query.dateTo}) &gt; 0",
            "    OR (SELECT COUNT(1)",
            "        FROM noon_ad_query_fact q",
            "        WHERE q.owner_user_id = #{query.ownerUserId}",
            "          AND q.project_code = #{query.projectCode}",
            "          AND q.store_code = #{query.storeCode}",
            "          AND q.site_code = #{query.siteCode}",
            "          AND q.report_date_from = #{query.dateFrom}",
            "          AND q.report_date_to = #{query.dateTo}) &gt; 0",
            "    THEN TRUE ELSE FALSE END AS dataAvailable",
            "FROM noon_ad_report_batch",
            "WHERE owner_user_id = #{query.ownerUserId}",
            "  AND project_code = #{query.projectCode}",
            "  AND store_code = #{query.storeCode}",
            "  AND site_code = #{query.siteCode}",
            "  AND report_date_from = #{query.dateFrom}",
            "  AND report_date_to = #{query.dateTo}",
            "</script>"
    })
    NoonAdvertisingDataStatus selectDataStatus(@Param("query") NoonAdvertisingDashboardQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  c.campaign_code AS campaignCode,",
            "  c.campaign_name AS campaignName,",
            "  c.store_code AS storeCode,",
            "  c.site_code AS siteCode,",
            "  (SELECT q.ad_sku_code",
            "   FROM noon_ad_query_fact q",
            "   WHERE q.owner_user_id = c.owner_user_id",
            "     AND q.project_code = c.project_code",
            "     AND q.store_code = c.store_code",
            "     AND q.site_code = c.site_code",
            "     AND q.report_date_from = c.report_date_from",
            "     AND q.report_date_to = c.report_date_to",
            "     AND q.campaign_code = c.campaign_code",
            "     AND COALESCE(q.ad_sku_code, '') != ''",
            "   ORDER BY COALESCE(q.spend_amount, 0) DESC, q.orders_count DESC, q.ad_sku_code ASC",
            "   LIMIT 1) AS primaryAdSkuCode,",
            "  (SELECT COALESCE(NULLIF(q.partner_sku, ''), ow.partner_sku, pp.partner_sku)",
            "   FROM noon_ad_query_fact q",
            "   LEFT JOIN (",
            "     SELECT store_code, site_code, noon_sku, MIN(partner_sku) AS partner_sku",
            "     FROM official_warehouse_inventory_snapshot_line",
            "     WHERE COALESCE(partner_sku, '') != ''",
            "       AND COALESCE(noon_sku, '') != ''",
            "     GROUP BY store_code, site_code, noon_sku",
            "   ) ow ON ow.store_code = q.store_code",
            "     AND ow.site_code = q.site_code",
            "     AND UPPER(TRIM(ow.noon_sku)) = UPPER(TRIM(q.ad_sku_code))",
            "   LEFT JOIN (",
            "     SELECT store_code, site_code, noon_product_code, MIN(partner_sku) AS partner_sku",
            "     FROM product_public_detail_snapshot pp",
            "     WHERE pp.is_latest = b'1'",
            "       AND pp.is_deleted = b'0'",
            "       AND COALESCE(partner_sku, '') != ''",
            "       AND COALESCE(noon_product_code, '') != ''",
            "     GROUP BY store_code, site_code, noon_product_code",
            "   ) pp ON pp.store_code = q.store_code",
            "     AND pp.site_code = q.site_code",
            "     AND UPPER(TRIM(pp.noon_product_code)) = UPPER(TRIM(SUBSTRING_INDEX(q.ad_sku_code, '-', 1)))",
            "   WHERE q.owner_user_id = c.owner_user_id",
            "     AND q.project_code = c.project_code",
            "     AND q.store_code = c.store_code",
            "     AND q.site_code = c.site_code",
            "     AND q.report_date_from = c.report_date_from",
            "     AND q.report_date_to = c.report_date_to",
            "     AND q.campaign_code = c.campaign_code",
            "     AND COALESCE(COALESCE(NULLIF(q.partner_sku, ''), ow.partner_sku, pp.partner_sku), '') != ''",
            "   ORDER BY COALESCE(q.spend_amount, 0) DESC, q.orders_count DESC, COALESCE(NULLIF(q.partner_sku, ''), ow.partner_sku, pp.partner_sku) ASC",
            "   LIMIT 1) AS primaryPartnerSku,",
            "  c.campaign_status AS campaignStatus,",
            "  c.qc_status AS qcStatus,",
            "  c.views,",
            "  c.clicks,",
            "  c.orders_count AS ordersCount,",
            "  c.assisted_orders AS assistedOrders,",
            "  c.atc_count AS atcCount,",
            "  COALESCE(c.spend_amount, 0) AS spendAmount,",
            "  COALESCE(c.ad_revenue, 0) AS adRevenue,",
            "  COALESCE(c.ctr_percentage, 0) AS ctrPercentage,",
            "  COALESCE(c.roas, 0) AS roas,",
            "  COALESCE(c.cpc, 0) AS cpc,",
            "  COALESCE(c.cps, 0) AS cps,",
            "  COALESCE(c.cvr_percentage, 0) AS cvrPercentage,",
            "  COALESCE(c.zero_order_spend_amount, 0) AS zeroOrderSpendAmount,",
            "  COALESCE(c.zero_order_spend_share, 0) AS zeroOrderSpendShare",
            "FROM noon_ad_campaign_fact c",
            "WHERE c.owner_user_id = #{query.ownerUserId}",
            "  AND c.project_code = #{query.projectCode}",
            "  AND c.store_code = #{query.storeCode}",
            "  AND c.site_code = #{query.siteCode}",
            "  AND c.report_date_from = #{query.dateFrom}",
            "  AND c.report_date_to = #{query.dateTo}",
            "ORDER BY c.spend_amount DESC, c.orders_count DESC, c.campaign_code ASC",
            "LIMIT 1000",
            "</script>"
    })
    List<NoonAdvertisingCampaignRow> selectCampaignRows(@Param("query") NoonAdvertisingDashboardQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  product.storeCode,",
            "  product.siteCode,",
            "  product.adSkuCode,",
            "  product.partnerSku,",
            "  product_image.image_url AS imageUrl,",
            "  product.campaignCount,",
            "  product.queryCount,",
            "  product.views,",
            "  product.clicks,",
            "  product.ordersCount,",
            "  product.assistedOrders,",
            "  product.atcCount,",
            "  product.spendAmount,",
            "  product.adRevenue,",
            "  product.ctrPercentage,",
            "  product.roas,",
            "  product.cpc,",
            "  product.cps,",
            "  product.cvrPercentage,",
            "  product.zeroOrderSpendAmount,",
            "  product.zeroOrderSpendShare",
            "FROM (",
            "  SELECT",
            "    resolved.store_code AS storeCode,",
            "    resolved.site_code AS siteCode,",
            "    MIN(resolved.ad_sku_code) AS adSkuCode,",
            "    MIN(NULLIF(resolved.partner_sku, '')) AS partnerSku,",
            "    COUNT(DISTINCT resolved.campaign_code) AS campaignCount,",
            "    COUNT(1) AS queryCount,",
            "    COALESCE(SUM(resolved.views), 0) AS views,",
            "    COALESCE(SUM(resolved.clicks), 0) AS clicks,",
            "    COALESCE(SUM(resolved.orders_count), 0) AS ordersCount,",
            "    COALESCE(SUM(resolved.assisted_orders), 0) AS assistedOrders,",
            "    COALESCE(SUM(resolved.atc_count), 0) AS atcCount,",
            "    COALESCE(SUM(resolved.spend_amount), 0) AS spendAmount,",
            "    COALESCE(SUM(resolved.ad_revenue), 0) AS adRevenue,",
            "    CASE WHEN COALESCE(SUM(resolved.views), 0) = 0 THEN 0 ELSE COALESCE(SUM(resolved.clicks), 0) / COALESCE(SUM(resolved.views), 0) END AS ctrPercentage,",
            "    CASE WHEN COALESCE(SUM(resolved.spend_amount), 0) = 0 THEN 0 ELSE COALESCE(SUM(resolved.ad_revenue), 0) / COALESCE(SUM(resolved.spend_amount), 0) END AS roas,",
            "    CASE WHEN COALESCE(SUM(resolved.clicks), 0) = 0 THEN 0 ELSE COALESCE(SUM(resolved.spend_amount), 0) / COALESCE(SUM(resolved.clicks), 0) END AS cpc,",
            "    CASE WHEN COALESCE(SUM(resolved.orders_count), 0) = 0 THEN 0 ELSE COALESCE(SUM(resolved.spend_amount), 0) / COALESCE(SUM(resolved.orders_count), 0) END AS cps,",
            "    CASE WHEN COALESCE(SUM(resolved.clicks), 0) = 0 THEN 0 ELSE COALESCE(SUM(resolved.orders_count), 0) / COALESCE(SUM(resolved.clicks), 0) END AS cvrPercentage,",
            "    COALESCE(SUM(CASE WHEN resolved.orders_count = 0 THEN resolved.spend_amount ELSE 0 END), 0) AS zeroOrderSpendAmount,",
            "    CASE WHEN COALESCE(SUM(resolved.spend_amount), 0) = 0 THEN 0",
            "      ELSE COALESCE(SUM(CASE WHEN resolved.orders_count = 0 THEN resolved.spend_amount ELSE 0 END), 0) / COALESCE(SUM(resolved.spend_amount), 0)",
            "    END AS zeroOrderSpendShare",
            "  FROM (",
            "    SELECT",
            "      q.store_code,",
            "      q.site_code,",
            "      q.ad_sku_code,",
            "      COALESCE(NULLIF(q.partner_sku, ''), ow.partner_sku, pp.partner_sku) AS partner_sku,",
            "      q.campaign_code,",
            "      q.views,",
            "      q.clicks,",
            "      q.orders_count,",
            "      q.assisted_orders,",
            "      q.atc_count,",
            "      q.spend_amount,",
            "      q.ad_revenue",
            "    FROM noon_ad_query_fact q",
            "    LEFT JOIN (",
            "      SELECT store_code, site_code, noon_sku, MIN(partner_sku) AS partner_sku",
            "      FROM official_warehouse_inventory_snapshot_line",
            "      WHERE COALESCE(partner_sku, '') != ''",
            "        AND COALESCE(noon_sku, '') != ''",
            "      GROUP BY store_code, site_code, noon_sku",
            "    ) ow ON ow.store_code = q.store_code",
            "      AND ow.site_code = q.site_code",
            "      AND UPPER(TRIM(ow.noon_sku)) = UPPER(TRIM(q.ad_sku_code))",
            "    LEFT JOIN (",
            "      SELECT store_code, site_code, noon_product_code, MIN(partner_sku) AS partner_sku",
            "      FROM product_public_detail_snapshot pp",
            "      WHERE pp.is_latest = b'1'",
            "        AND pp.is_deleted = b'0'",
            "        AND COALESCE(partner_sku, '') != ''",
            "        AND COALESCE(noon_product_code, '') != ''",
            "      GROUP BY store_code, site_code, noon_product_code",
            "    ) pp ON pp.store_code = q.store_code",
            "      AND pp.site_code = q.site_code",
            "      AND UPPER(TRIM(pp.noon_product_code)) = UPPER(TRIM(SUBSTRING_INDEX(q.ad_sku_code, '-', 1)))",
            "    WHERE q.owner_user_id = #{query.ownerUserId}",
            "      AND q.project_code = #{query.projectCode}",
            "      AND q.store_code = #{query.storeCode}",
            "      AND q.site_code = #{query.siteCode}",
            "      AND q.report_date_from = #{query.dateFrom}",
            "      AND q.report_date_to = #{query.dateTo}",
            "  ) resolved",
            "  WHERE (COALESCE(resolved.partner_sku, '') != '' OR COALESCE(resolved.ad_sku_code, '') != '')",
            "  GROUP BY resolved.store_code, resolved.site_code, COALESCE(NULLIF(resolved.partner_sku, ''), CONCAT('ADSKU:', resolved.ad_sku_code))",
            ") product",
            "LEFT JOIN (",
            "  SELECT",
            "    lss.store_code,",
            "    lss.site AS site_code,",
            "    pv.partner_sku,",
            "    COALESCE(",
            "      MAX(NULLIF(pm.cover_image_url, '')),",
            "      MAX(NULLIF(pp.main_image_url, '')),",
            "      MAX(NULLIF(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(pms.snapshot_json, '$.content.mainImageUrl')), 'null'), '')),",
            "      MAX(NULLIF(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(pms.snapshot_json, '$.content.images[0]')), 'null'), ''))",
            "    ) AS image_url",
            "  FROM logical_store_site lss",
            "  JOIN logical_store ls ON ls.id = lss.logical_store_id",
            "    AND ls.owner_user_id = #{query.ownerUserId}",
            "    AND ls.is_deleted = b'0'",
            "  JOIN product_variant pv ON pv.logical_store_id = lss.logical_store_id",
            "    AND pv.is_deleted = b'0'",
            "  JOIN product_master pm ON pm.id = pv.product_master_id",
            "    AND pm.logical_store_id = lss.logical_store_id",
            "    AND pm.is_deleted = b'0'",
            "  LEFT JOIN product_public_detail_snapshot pp ON pp.owner_user_id = ls.owner_user_id",
            "    AND pp.store_code = lss.store_code",
            "    AND pp.site_code = lss.site",
            "    AND pp.partner_sku = pv.partner_sku",
            "    AND pp.is_latest = b'1'",
            "    AND pp.is_deleted = b'0'",
            "  LEFT JOIN product_master_snapshot pms ON pms.product_master_id = pm.id",
            "    AND pms.snapshot_type = 'baseline'",
            "    AND pms.is_deleted = b'0'",
            "    AND pms.id = (",
            "      SELECT pms_latest.id",
            "      FROM product_master_snapshot pms_latest",
            "      WHERE pms_latest.product_master_id = pm.id",
            "        AND pms_latest.snapshot_type = 'baseline'",
            "        AND pms_latest.is_deleted = b'0'",
            "      ORDER BY pms_latest.fetched_at DESC, pms_latest.id DESC",
            "      LIMIT 1",
            "    )",
            "  WHERE lss.store_code = #{query.storeCode}",
            "    AND lss.site = #{query.siteCode}",
            "    AND lss.is_deleted = b'0'",
            "  GROUP BY lss.store_code, lss.site, pv.partner_sku",
            ") product_image ON product_image.store_code = product.storeCode",
            "  AND product_image.site_code = product.siteCode",
            "  AND product_image.partner_sku = product.partnerSku",
            "ORDER BY product.spendAmount DESC, product.ordersCount DESC, product.partnerSku ASC, product.adSkuCode ASC",
            "LIMIT 1000",
            "</script>"
    })
    List<NoonAdvertisingProductRow> selectProductRows(@Param("query") NoonAdvertisingDashboardQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  q.campaign_code AS campaignCode,",
            "  q.campaign_name AS campaignName,",
            "  q.store_code AS storeCode,",
            "  q.site_code AS siteCode,",
            "  q.ad_sku_code AS adSkuCode,",
            "  COALESCE(NULLIF(q.partner_sku, ''), ow.partner_sku, pp.partner_sku) AS partnerSku,",
            "  q.query_text AS queryText,",
            "  q.query_kind AS queryKind,",
            "  q.views,",
            "  q.clicks,",
            "  q.orders_count AS ordersCount,",
            "  q.assisted_orders AS assistedOrders,",
            "  q.atc_count AS atcCount,",
            "  COALESCE(q.spend_amount, 0) AS spendAmount,",
            "  COALESCE(q.ad_revenue, 0) AS adRevenue,",
            "  COALESCE(q.ctr_percentage, 0) AS ctrPercentage,",
            "  COALESCE(q.roas, 0) AS roas,",
            "  COALESCE(q.cpc, 0) AS cpc,",
            "  COALESCE(q.cps, 0) AS cps,",
            "  COALESCE(q.cvr_percentage, 0) AS cvrPercentage",
            "FROM noon_ad_query_fact q",
            "LEFT JOIN (",
            "  SELECT store_code, site_code, noon_sku, MIN(partner_sku) AS partner_sku",
            "  FROM official_warehouse_inventory_snapshot_line",
            "  WHERE COALESCE(partner_sku, '') != ''",
            "    AND COALESCE(noon_sku, '') != ''",
            "  GROUP BY store_code, site_code, noon_sku",
            ") ow ON ow.store_code = q.store_code",
            "  AND ow.site_code = q.site_code",
            "  AND UPPER(TRIM(ow.noon_sku)) = UPPER(TRIM(q.ad_sku_code))",
            "LEFT JOIN (",
            "  SELECT store_code, site_code, noon_product_code, MIN(partner_sku) AS partner_sku",
            "  FROM product_public_detail_snapshot pp",
            "  WHERE pp.is_latest = b'1'",
            "    AND pp.is_deleted = b'0'",
            "    AND COALESCE(partner_sku, '') != ''",
            "    AND COALESCE(noon_product_code, '') != ''",
            "  GROUP BY store_code, site_code, noon_product_code",
            ") pp ON pp.store_code = q.store_code",
            "  AND pp.site_code = q.site_code",
            "  AND UPPER(TRIM(pp.noon_product_code)) = UPPER(TRIM(SUBSTRING_INDEX(q.ad_sku_code, '-', 1)))",
            "WHERE q.owner_user_id = #{query.ownerUserId}",
            "  AND q.project_code = #{query.projectCode}",
            "  AND q.store_code = #{query.storeCode}",
            "  AND q.site_code = #{query.siteCode}",
            "  AND q.report_date_from = #{query.dateFrom}",
            "  AND q.report_date_to = #{query.dateTo}",
            "  AND q.orders_count = 0",
            "  AND q.spend_amount &gt; 0",
            "ORDER BY q.spend_amount DESC, q.clicks DESC, q.campaign_code ASC, partnerSku ASC, q.ad_sku_code ASC, q.query_text ASC",
            "LIMIT 5000",
            "</script>"
    })
    List<NoonAdvertisingQueryRow> selectZeroOrderQueryRows(@Param("query") NoonAdvertisingDashboardQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  q.campaign_code AS campaignCode,",
            "  q.campaign_name AS campaignName,",
            "  q.store_code AS storeCode,",
            "  q.site_code AS siteCode,",
            "  q.ad_sku_code AS adSkuCode,",
            "  COALESCE(NULLIF(q.partner_sku, ''), ow.partner_sku, pp.partner_sku) AS partnerSku,",
            "  q.query_text AS queryText,",
            "  q.query_kind AS queryKind,",
            "  q.views,",
            "  q.clicks,",
            "  q.orders_count AS ordersCount,",
            "  q.assisted_orders AS assistedOrders,",
            "  q.atc_count AS atcCount,",
            "  COALESCE(q.spend_amount, 0) AS spendAmount,",
            "  COALESCE(q.ad_revenue, 0) AS adRevenue,",
            "  COALESCE(q.ctr_percentage, 0) AS ctrPercentage,",
            "  COALESCE(q.roas, 0) AS roas,",
            "  COALESCE(q.cpc, 0) AS cpc,",
            "  COALESCE(q.cps, 0) AS cps,",
            "  COALESCE(q.cvr_percentage, 0) AS cvrPercentage",
            "FROM noon_ad_query_fact q",
            "LEFT JOIN (",
            "  SELECT store_code, site_code, noon_sku, MIN(partner_sku) AS partner_sku",
            "  FROM official_warehouse_inventory_snapshot_line",
            "  WHERE COALESCE(partner_sku, '') != ''",
            "    AND COALESCE(noon_sku, '') != ''",
            "  GROUP BY store_code, site_code, noon_sku",
            ") ow ON ow.store_code = q.store_code",
            "  AND ow.site_code = q.site_code",
            "  AND UPPER(TRIM(ow.noon_sku)) = UPPER(TRIM(q.ad_sku_code))",
            "LEFT JOIN (",
            "  SELECT store_code, site_code, noon_product_code, MIN(partner_sku) AS partner_sku",
            "  FROM product_public_detail_snapshot pp",
            "  WHERE pp.is_latest = b'1'",
            "    AND pp.is_deleted = b'0'",
            "    AND COALESCE(partner_sku, '') != ''",
            "    AND COALESCE(noon_product_code, '') != ''",
            "  GROUP BY store_code, site_code, noon_product_code",
            ") pp ON pp.store_code = q.store_code",
            "  AND pp.site_code = q.site_code",
            "  AND UPPER(TRIM(pp.noon_product_code)) = UPPER(TRIM(SUBSTRING_INDEX(q.ad_sku_code, '-', 1)))",
            "WHERE q.owner_user_id = #{query.ownerUserId}",
            "  AND q.project_code = #{query.projectCode}",
            "  AND q.store_code = #{query.storeCode}",
            "  AND q.site_code = #{query.siteCode}",
            "  AND q.report_date_from = #{query.dateFrom}",
            "  AND q.report_date_to = #{query.dateTo}",
            "  AND q.orders_count &gt; 0",
            "  AND q.spend_amount &gt; 0",
            "ORDER BY q.roas DESC, q.ad_revenue DESC, q.orders_count DESC, q.campaign_code ASC, partnerSku ASC, q.ad_sku_code ASC, q.query_text ASC",
            "LIMIT 5000",
            "</script>"
    })
    List<NoonAdvertisingQueryRow> selectWinningQueryRows(@Param("query") NoonAdvertisingDashboardQuery query);
}
