package com.nuono.next.infrastructure.mapper;

public final class OfficialWarehouseShippingBatchDiagnosticSqlProvider {

    private OfficialWarehouseShippingBatchDiagnosticSqlProvider() {
    }

    public static String selectExactBatchDiagnostic() {
        return String.join("\n",
                OfficialWarehouseShippingBatchSqlProvider.strictBarcodeProductCtes(),
                ", matchedBatch AS (",
                "  SELECT b.id, b.owner_user_id, b.batch_reference_no, b.tracking_no, b.external_shipment_no,",
                "         b.target_store_code, b.target_site_code, b.batch_status, b.latest_node_status",
                "  FROM in_transit_batch b",
                "  WHERE b.owner_user_id = #{ownerUserId} AND b.is_deleted = b'0'",
                "    AND (BINARY b.batch_reference_no = BINARY #{keyword}",
                "         OR BINARY b.tracking_no = BINARY #{keyword}",
                "         OR BINARY b.external_shipment_no = BINARY #{keyword})",
                "  ORDER BY CASE WHEN BINARY b.batch_reference_no = BINARY #{keyword} THEN 0",
                "                WHEN BINARY b.tracking_no = BINARY #{keyword} THEN 1",
                "                WHEN BINARY b.external_shipment_no = BINARY #{keyword} THEN 2 ELSE 3 END,",
                "           b.gmt_updated DESC, b.id DESC",
                "  LIMIT 1",
                "), allocationScope AS (",
                "  SELECT owner_user_id, in_transit_goods_line_id,",
                "         CAST(FLOOR(SUM(GREATEST(COALESCE(allocated_quantity, 0), 0))) AS SIGNED) AS scopedQuantity,",
                "         MIN(product_variant_id) AS allocatedProductVariantId,",
                "         COUNT(DISTINCT product_variant_id) AS allocatedVariantCount",
                "  FROM procurement_logistics_shipment_allocation",
                "  WHERE owner_user_id = #{ownerUserId} AND is_deleted = b'0'",
                "    AND confirmation_status = 'CONFIRMED'",
                "    AND target_store_code = #{storeCode} AND target_site_code = #{siteCode}",
                "  GROUP BY owner_user_id, in_transit_goods_line_id",
                "), scheduled AS (",
                "  SELECT link.owner_user_id, link.in_transit_goods_line_id,",
                "         SUM(CASE WHEN EXISTS (",
                "           SELECT 1 FROM official_warehouse_appointment appointment",
                "           WHERE appointment.asn_id = link.asn_id",
                "             AND appointment.owner_user_id = link.owner_user_id",
                "             AND appointment.is_deleted = b'0' AND appointment.status = 'SCHEDULED'",
                "         ) THEN GREATEST(COALESCE(link.quantity, 0), 0) ELSE 0 END) AS scheduledQuantity",
                "  FROM official_warehouse_asn_shipping_batch_link link",
                "  JOIN official_warehouse_asn linkedAsn ON linkedAsn.id = link.asn_id",
                "   AND linkedAsn.owner_user_id = link.owner_user_id AND linkedAsn.is_deleted = b'0'",
                "   AND UPPER(COALESCE(linkedAsn.status, '')) NOT IN ('FAILED', 'CANCELED', 'CANCELLED')",
                "  WHERE link.owner_user_id = #{ownerUserId} AND link.is_deleted = b'0'",
                "    AND link.in_transit_goods_line_id IS NOT NULL",
                "  GROUP BY link.owner_user_id, link.in_transit_goods_line_id",
                "), resolvedLines AS (",
                "  SELECT line.id, line.batch_id, line.owner_user_id,",
                "         CASE WHEN allocation.scopedQuantity IS NOT NULL",
                "              THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), allocation.scopedQuantity)",
                "              ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END AS scopedQuantity,",
                "         GREATEST(COALESCE(scheduled.scheduledQuantity, 0), 0) AS scheduledQuantity",
                "  FROM matchedBatch batch",
                "  JOIN in_transit_goods_line line ON line.batch_id = batch.id",
                "   AND line.owner_user_id = batch.owner_user_id AND line.is_deleted = b'0'",
                "  JOIN barcodeProducts product ON product.barcode = line.sku",
                "   AND BINARY product.barcode = BINARY line.sku",
                "  LEFT JOIN allocationScope allocation ON allocation.owner_user_id = line.owner_user_id",
                "   AND allocation.in_transit_goods_line_id = line.id",
                "  LEFT JOIN scheduled ON scheduled.owner_user_id = line.owner_user_id",
                "   AND scheduled.in_transit_goods_line_id = line.id",
                "  WHERE line.psku = product.partnerSku",
                "    AND BINARY line.psku = BINARY product.partnerSku",
                "    AND (allocation.in_transit_goods_line_id IS NULL",
                "         OR (allocation.allocatedVariantCount = 1",
                "             AND allocation.allocatedProductVariantId = product.productVariantId))",
                ")",
                "SELECT batch.id,",
                "       COALESCE(NULLIF(batch.batch_reference_no, ''), NULLIF(batch.tracking_no, ''),",
                "                NULLIF(batch.external_shipment_no, ''), CAST(batch.id AS CHAR)) AS batchNo,",
                "       batch.target_store_code AS targetStoreCode, batch.target_site_code AS targetSiteCode,",
                "       batch.batch_status AS status, batch.latest_node_status AS latestNodeStatus,",
                "       (SELECT COUNT(*) FROM in_transit_package packageRow",
                "         WHERE packageRow.owner_user_id = batch.owner_user_id AND packageRow.batch_id = batch.id",
                "           AND packageRow.is_deleted = b'0') AS packageCount,",
                "       (SELECT COUNT(*) FROM in_transit_product_match_candidate candidate",
                "         WHERE candidate.owner_user_id = batch.owner_user_id AND candidate.batch_id = batch.id",
                "           AND candidate.is_deleted = b'0') AS sourceCandidateCount,",
                "       (SELECT COUNT(*) FROM in_transit_product_match_candidate candidate",
                "         WHERE candidate.owner_user_id = batch.owner_user_id AND candidate.batch_id = batch.id",
                "           AND candidate.is_deleted = b'0' AND (",
                "             (UPPER(candidate.store_code) = UPPER(#{storeCode})",
                "              AND UPPER(candidate.site_code) = UPPER(#{siteCode}))",
                "             OR (COALESCE(candidate.store_code, '') = ''",
                "                 AND COALESCE(candidate.site_code, '') = '')",
                "           )) AS currentScopeCandidateCount,",
                "       (SELECT COUNT(*) FROM in_transit_product_match_candidate candidate",
                "         WHERE candidate.owner_user_id = batch.owner_user_id AND candidate.batch_id = batch.id",
                "           AND candidate.match_status = 'UNMATCHED' AND candidate.is_deleted = b'0') AS unmatchedCandidateCount,",
                "       (SELECT COUNT(*) FROM in_transit_product_match_candidate candidate",
                "         WHERE candidate.owner_user_id = batch.owner_user_id AND candidate.batch_id = batch.id",
                "           AND candidate.match_status = 'EXCLUDED' AND candidate.is_deleted = b'0') AS excludedCandidateCount,",
                "       (SELECT COUNT(*) FROM in_transit_goods_line line",
                "         WHERE line.owner_user_id = batch.owner_user_id AND line.batch_id = batch.id",
                "           AND line.is_deleted = b'0') AS goodsLineCount,",
                "       (SELECT COUNT(*) FROM resolvedLines line WHERE line.batch_id = batch.id) AS resolvedLineCount,",
                "       COALESCE((SELECT SUM(line.scopedQuantity) FROM resolvedLines line",
                "                  WHERE line.batch_id = batch.id), 0) AS shippedQuantity,",
                "       COALESCE((SELECT SUM(GREATEST(line.scopedQuantity - line.scheduledQuantity, 0))",
                "                  FROM resolvedLines line WHERE line.batch_id = batch.id), 0) AS remainingQuantity",
                "FROM matchedBatch batch",
                "LIMIT 1"
        );
    }
}
