package com.nuono.next.infrastructure.mapper;

public final class OfficialWarehouseShippingBatchSqlProvider {

    private OfficialWarehouseShippingBatchSqlProvider() {
    }

    public static String listShippingBatchCandidates() {
        return String.join("\n",
                "<script>",
                strictBarcodeProductCtes(),
                ", allocationScope AS (",
                "  SELECT owner_user_id, in_transit_goods_line_id,",
                "         CAST(FLOOR(SUM(GREATEST(COALESCE(allocated_quantity, 0), 0))) AS SIGNED) AS scopedQuantity,",
                "         MIN(product_variant_id) AS allocatedProductVariantId,",
                "         COUNT(DISTINCT product_variant_id) AS allocatedVariantCount",
                "  FROM procurement_logistics_shipment_allocation",
                "  WHERE owner_user_id = #{ownerUserId} AND is_deleted = b'0'",
                "    AND confirmation_status = 'CONFIRMED'",
                "    AND target_store_code = #{storeCode} AND target_site_code = #{siteCode}",
                "  GROUP BY owner_user_id, in_transit_goods_line_id",
                "), eligibleBatches AS (",
                "  SELECT b.id, b.owner_user_id, b.batch_reference_no, b.tracking_no, b.external_shipment_no,",
                "         COALESCE(f.forwarder_name, b.raw_forwarder_name) AS forwarderName,",
                "         b.transport_mode, b.batch_status, b.latest_node_status, b.gmt_updated",
                "  FROM in_transit_batch b",
                "  LEFT JOIN in_transit_forwarder f ON f.id = b.standard_forwarder_id",
                "   AND f.owner_user_id = b.owner_user_id AND f.is_deleted = b'0'",
                "  WHERE b.owner_user_id = #{ownerUserId} AND b.is_deleted = b'0'",
                "    AND (",
                "      (b.target_site_code IS NOT NULL AND b.target_site_code &lt;&gt; '' AND b.target_site_code = #{siteCode})",
                "      OR (#{siteCode} = 'SA' AND (COALESCE(b.target_store_code, '') LIKE 'RUH%'",
                "          OR COALESCE(b.target_store_code, '') LIKE 'JED%'))",
                "      OR (#{siteCode} = 'AE' AND (COALESCE(b.target_store_code, '') LIKE 'DB%'",
                "          OR COALESCE(b.target_store_code, '') LIKE 'DXB%'",
                "          OR COALESCE(b.target_store_code, '') LIKE 'AUH%'))",
                "    )",
                "    AND (b.batch_status IN ('shipped', 'in_transit', 'customs_clearance', 'delivering', 'warehouse_received')",
                "         OR b.latest_node_status IN ('departed_origin', 'in_transit', 'arrived_port', 'customs_clearance',",
                "                                      'customs_released', 'delivering', 'warehouse_received'))",
                "  <if test='keywordLike != null and keywordLike != \"\"'>",
                "    AND (b.batch_reference_no LIKE #{keywordLike} OR b.tracking_no LIKE #{keywordLike}",
                "         OR b.external_shipment_no LIKE #{keywordLike} OR b.raw_forwarder_name LIKE #{keywordLike}",
                "         OR f.forwarder_name LIKE #{keywordLike})",
                "  </if>",
                "), resolvedLines AS (",
                "  SELECT line.id, line.batch_id, line.owner_user_id, line.shipped_quantity, line.sku,",
                "         product.productVariantId, product.partnerSku, allocation.scopedQuantity",
                "  FROM eligibleBatches batch",
                "  JOIN in_transit_goods_line line ON line.batch_id = batch.id",
                "   AND line.owner_user_id = batch.owner_user_id AND line.is_deleted = b'0'",
                "  JOIN barcodeProducts product ON product.barcode = line.sku",
                "   AND BINARY product.barcode = BINARY line.sku",
                "  LEFT JOIN allocationScope allocation ON allocation.owner_user_id = line.owner_user_id",
                "   AND allocation.in_transit_goods_line_id = line.id",
                "  WHERE line.psku = product.partnerSku",
                "    AND BINARY line.psku = BINARY product.partnerSku",
                "    AND (allocation.in_transit_goods_line_id IS NULL",
                "         OR (allocation.allocatedVariantCount = 1",
                "             AND allocation.allocatedProductVariantId = product.productVariantId))",
                "), linked AS (",
                "  SELECT link.owner_user_id, link.in_transit_goods_line_id,",
                "         SUM(GREATEST(COALESCE(link.quantity, 0), 0)) AS linkedQuantity,",
                "         SUM(CASE WHEN EXISTS (",
                "           SELECT 1 FROM official_warehouse_appointment scheduledAppointment",
                "           WHERE scheduledAppointment.asn_id = link.asn_id",
                "             AND scheduledAppointment.owner_user_id = link.owner_user_id",
                "             AND scheduledAppointment.is_deleted = b'0'",
                "             AND scheduledAppointment.status = 'SCHEDULED'",
                "         ) THEN GREATEST(COALESCE(link.quantity, 0), 0) ELSE 0 END) AS scheduledAppointmentQuantity",
                "  FROM official_warehouse_asn_shipping_batch_link link",
                "  JOIN official_warehouse_asn linkedAsn ON linkedAsn.id = link.asn_id",
                "   AND linkedAsn.owner_user_id = link.owner_user_id AND linkedAsn.is_deleted = b'0'",
                "   AND UPPER(COALESCE(linkedAsn.status, '')) NOT IN ('FAILED', 'CANCELED', 'CANCELLED')",
                "  WHERE link.owner_user_id = #{ownerUserId} AND link.is_deleted = b'0'",
                "    AND link.in_transit_goods_line_id IS NOT NULL",
                "  GROUP BY link.owner_user_id, link.in_transit_goods_line_id",
                "), purchase AS (",
                "  SELECT owner_user_id, in_transit_goods_line_id, COUNT(DISTINCT source_id) AS purchaseOrderCount",
                "  FROM procurement_logistics_shipment_allocation",
                "  WHERE owner_user_id = #{ownerUserId} AND is_deleted = b'0' AND confirmation_status = 'CONFIRMED'",
                "  GROUP BY owner_user_id, in_transit_goods_line_id",
                ")",
                "SELECT batch.id, 'IN_TRANSIT_BATCH' AS sourceKind,",
                "       COALESCE(NULLIF(batch.batch_reference_no, ''), NULLIF(batch.tracking_no, ''),",
                "                NULLIF(batch.external_shipment_no, ''), CAST(batch.id AS CHAR)) AS batchNo,",
                "       batch.tracking_no AS trackingNo, batch.external_shipment_no AS externalShipmentNo,",
                "       batch.forwarderName, batch.transport_mode AS transportMode,",
                "       batch.batch_status AS status, batch.latest_node_status AS latestNodeStatus,",
                "       NULL AS selectedOptionId,",
                "       COALESCE(SUM(CASE WHEN line.scopedQuantity IS NOT NULL",
                "                         THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                         ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END), 0) AS totalQuantity,",
                "       COALESCE(SUM(CASE WHEN line.scopedQuantity IS NOT NULL",
                "                         THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                         ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END), 0) AS storeSiteQuantity,",
                "       COALESCE(SUM(LEAST(GREATEST(COALESCE(linked.linkedQuantity, 0), 0),",
                "                         CASE WHEN line.scopedQuantity IS NOT NULL",
                "                              THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                              ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END)), 0) AS linkedQuantity,",
                "       COALESCE(SUM(GREATEST((CASE WHEN line.scopedQuantity IS NOT NULL",
                "                                      THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                                      ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END)",
                "                                   - GREATEST(COALESCE(linked.scheduledAppointmentQuantity, 0), 0), 0)), 0) AS remainingQuantity,",
                "       COALESCE(SUM(LEAST(GREATEST(COALESCE(linked.scheduledAppointmentQuantity, 0), 0),",
                "                         CASE WHEN line.scopedQuantity IS NOT NULL",
                "                              THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                              ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END)), 0) AS scheduledAppointmentQuantity,",
                "       CASE WHEN COALESCE(SUM(GREATEST(COALESCE(linked.scheduledAppointmentQuantity, 0), 0)), 0) &gt; 0 THEN 1 ELSE 0 END AS alreadyAppointed,",
                "       CASE WHEN COALESCE(SUM(GREATEST(COALESCE(linked.linkedQuantity, 0), 0)), 0) &gt; 0 THEN 1 ELSE 0 END AS batchUsedByAsn,",
                "       CASE WHEN COALESCE(SUM(GREATEST(COALESCE(linked.scheduledAppointmentQuantity, 0), 0)), 0) &gt; 0 THEN '已约仓'",
                "            WHEN COALESCE(SUM(GREATEST(COALESCE(linked.linkedQuantity, 0), 0)), 0) &gt; 0 THEN '已建ASN'",
                "            ELSE '可约仓' END AS batchUsageLabel,",
                "       COUNT(DISTINCT BINARY line.sku) AS skuCount,",
                "       COALESCE(SUM(COALESCE(purchase.purchaseOrderCount, 0)), 0) AS purchaseOrderCount,",
                "       NULL AS storeSummaryJson, NULL AS siteSummaryJson, NULL AS transportSummaryJson,",
                "       DATE_FORMAT(batch.gmt_updated, '%Y-%m-%d %H:%i') AS updatedAt",
                "FROM eligibleBatches batch",
                "JOIN resolvedLines line ON line.batch_id = batch.id AND line.owner_user_id = batch.owner_user_id",
                "LEFT JOIN linked ON linked.owner_user_id = batch.owner_user_id",
                " AND linked.in_transit_goods_line_id = line.id",
                "LEFT JOIN purchase ON purchase.owner_user_id = batch.owner_user_id",
                " AND purchase.in_transit_goods_line_id = line.id",
                "GROUP BY batch.id, batch.batch_reference_no, batch.tracking_no, batch.external_shipment_no,",
                "         batch.forwarderName, batch.transport_mode, batch.batch_status, batch.latest_node_status, batch.gmt_updated",
                "ORDER BY batchUsedByAsn ASC, batch.gmt_updated DESC, batch.id DESC",
                "LIMIT #{limit}",
                "</script>"
        );
    }

    public static String listShippingBatchSourceAllocations() {
        return String.join("\n",
                "<script>",
                strictBarcodeProductCtes(),
                ", allocationScope AS (",
                "  SELECT owner_user_id, in_transit_goods_line_id,",
                "         CAST(FLOOR(SUM(GREATEST(COALESCE(allocated_quantity, 0), 0))) AS SIGNED) AS scopedQuantity,",
                "         MIN(product_variant_id) AS allocatedProductVariantId,",
                "         COUNT(DISTINCT product_variant_id) AS allocatedVariantCount",
                "  FROM procurement_logistics_shipment_allocation",
                "  WHERE owner_user_id = #{ownerUserId} AND is_deleted = b'0'",
                "    AND confirmation_status = 'CONFIRMED'",
                "    AND target_store_code = #{storeCode} AND target_site_code = #{siteCode}",
                "  GROUP BY owner_user_id, in_transit_goods_line_id",
                "), purchase AS (",
                "  SELECT owner_user_id, in_transit_goods_line_id,",
                "         MIN(purchase_batch_id) AS purchaseBatchId, MIN(source_id) AS sourceId",
                "  FROM procurement_logistics_shipment_allocation",
                "  WHERE owner_user_id = #{ownerUserId} AND is_deleted = b'0' AND confirmation_status = 'CONFIRMED'",
                "  GROUP BY owner_user_id, in_transit_goods_line_id",
                ")",
                "SELECT NULL AS shippingBatchId,",
                "       COALESCE(NULLIF(b.batch_reference_no, ''), NULLIF(b.tracking_no, ''),",
                "                NULLIF(b.external_shipment_no, ''), CAST(b.id AS CHAR)) AS shippingBatchNo,",
                "       b.batch_status AS status, NULL AS selectedOptionId, NULL AS shippingBatchSourceId,",
                "       b.id AS inTransitBatchId, b.batch_reference_no AS batchReferenceNo, b.tracking_no AS trackingNo,",
                "       b.external_shipment_no AS externalShipmentNo, COALESCE(f.forwarder_name, b.raw_forwarder_name) AS forwarderName,",
                "       b.transport_mode AS transportMode, b.latest_node_status AS latestNodeStatus, line.id AS inTransitGoodsLineId,",
                "       line.sku AS sourceBarcode, NULL AS fulfillmentBalanceId, #{storeCode} AS sourceStoreCode,",
                "       product.sourceStoreName, purchase.purchaseBatchId AS purchaseOrderId, purchase.sourceId AS purchaseOrderNo,",
                "       NULL AS purchaseOrderTitle, NULL AS purchaseOrderItemId, NULL AS purchaseOrderItemSiteId,",
                "       product.productMasterId, product.productVariantId, product.partnerSku, product.skuParent,",
                "       product.titleCache, product.imageUrlCache, COALESCE(NULLIF(line.site_code, ''), #{siteCode}) AS siteCode,",
                "       b.transport_mode AS plannedTransportMode, 'FBN' AS fulfillmentType,",
                "       COALESCE(f.forwarder_name, b.raw_forwarder_name) AS sourcePartyName,",
                "       CASE WHEN allocation.scopedQuantity IS NOT NULL",
                "            THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), allocation.scopedQuantity)",
                "            ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END AS quantity",
                "FROM in_transit_batch b",
                "JOIN in_transit_goods_line line ON line.batch_id = b.id",
                " AND line.owner_user_id = b.owner_user_id AND line.is_deleted = b'0'",
                "JOIN barcodeProducts product ON product.barcode = line.sku",
                " AND BINARY product.barcode = BINARY line.sku",
                "LEFT JOIN allocationScope allocation ON allocation.owner_user_id = line.owner_user_id",
                " AND allocation.in_transit_goods_line_id = line.id",
                "LEFT JOIN in_transit_forwarder f ON f.id = b.standard_forwarder_id",
                " AND f.owner_user_id = b.owner_user_id AND f.is_deleted = b'0'",
                "LEFT JOIN purchase ON purchase.owner_user_id = b.owner_user_id",
                " AND purchase.in_transit_goods_line_id = line.id",
                "WHERE b.owner_user_id = #{ownerUserId} AND b.is_deleted = b'0'",
                "  AND line.psku = product.partnerSku",
                "  AND BINARY line.psku = BINARY product.partnerSku",
                "  AND (allocation.in_transit_goods_line_id IS NULL",
                "       OR (allocation.allocatedVariantCount = 1",
                "           AND allocation.allocatedProductVariantId = product.productVariantId))",
                "  AND (",
                "    (b.target_site_code IS NOT NULL AND b.target_site_code &lt;&gt; '' AND b.target_site_code = #{siteCode})",
                "    OR (#{siteCode} = 'SA' AND (COALESCE(b.target_store_code, '') LIKE 'RUH%'",
                "        OR COALESCE(b.target_store_code, '') LIKE 'JED%'))",
                "    OR (#{siteCode} = 'AE' AND (COALESCE(b.target_store_code, '') LIKE 'DB%'",
                "        OR COALESCE(b.target_store_code, '') LIKE 'DXB%'",
                "        OR COALESCE(b.target_store_code, '') LIKE 'AUH%'))",
                "  )",
                "  AND (b.batch_status IN ('shipped', 'in_transit', 'customs_clearance', 'delivering', 'warehouse_received')",
                "       OR b.latest_node_status IN ('departed_origin', 'in_transit', 'arrived_port', 'customs_clearance',",
                "                                    'customs_released', 'delivering', 'warehouse_received'))",
                "<if test='batchIds != null and batchIds.size() &gt; 0'>",
                "  AND b.id IN",
                "  <foreach item='batchId' collection='batchIds' open='(' separator=',' close=')'>#{batchId}</foreach>",
                "</if>",
                "<if test='(partnerSkus != null and partnerSkus.size() &gt; 0) or (variantIds != null and variantIds.size() &gt; 0)'>",
                "  AND (1 = 0",
                "  <if test='partnerSkus != null and partnerSkus.size() &gt; 0'>",
                "    OR product.partnerSku IN",
                "    <foreach item='partnerSku' collection='partnerSkus' open='(' separator=',' close=')'>#{partnerSku}</foreach>",
                "  </if>",
                "  <if test='variantIds != null and variantIds.size() &gt; 0'>",
                "    OR product.productVariantId IN",
                "    <foreach item='variantId' collection='variantIds' open='(' separator=',' close=')'>#{variantId}</foreach>",
                "  </if>",
                "  )",
                "</if>",
                "HAVING quantity &gt; 0",
                "ORDER BY b.gmt_updated DESC, b.id DESC, line.id ASC",
                "</script>"
        );
    }

    static String strictBarcodeProductCtes() {
        return String.join("\n",
                "WITH ownerBarcodeCandidates AS (",
                "  SELECT BINARY pb.barcode AS barcodeKey, pb.logical_store_id AS logicalStoreId, pb.partner_sku AS partnerSku",
                "  FROM product_barcode pb",
                "  JOIN product_master pm ON pm.id = pb.product_master_id",
                "   AND pm.logical_store_id = pb.logical_store_id",
                "   AND pm.partner_sku = pb.partner_sku AND BINARY pm.partner_sku = BINARY pb.partner_sku",
                "   AND pm.is_deleted = b'0'",
                "  JOIN logical_store ls ON ls.id = pb.logical_store_id",
                "   AND ls.owner_user_id = #{ownerUserId} AND ls.is_deleted = b'0'",
                "  WHERE pb.is_deleted = b'0' AND COALESCE(pb.barcode_type, '') &lt;&gt; 'PARTNER_SKU_ALIAS'",
                "    AND NULLIF(TRIM(pb.barcode), '') IS NOT NULL",
                "), ownerBarcodeIdentity AS (",
                "  SELECT barcodeKey",
                "  FROM ownerBarcodeCandidates",
                "  GROUP BY barcodeKey",
                "  HAVING COUNT(DISTINCT logicalStoreId, BINARY partnerSku) = 1",
                "), storeScope AS (",
                "  SELECT ls.id AS logicalStoreId, lss.id AS siteId, ls.project_name AS sourceStoreName",
                "  FROM logical_store_site lss",
                "  JOIN logical_store ls ON ls.id = lss.logical_store_id",
                "   AND ls.owner_user_id = #{ownerUserId} AND ls.is_deleted = b'0'",
                "  WHERE lss.store_code = #{storeCode} AND lss.site = #{siteCode} AND lss.is_deleted = b'0'",
                "), barcodeProductCandidates AS (",
                "  SELECT BINARY pb.barcode AS barcodeKey, pb.barcode, pm.id AS productMasterId,",
                "         pv.id AS productVariantId, pso.id AS productSiteOfferId, pm.partner_sku AS partnerSku,",
                "         pm.sku_parent AS skuParent, COALESCE(pm.title_cn_cache, pm.title_cache, pv.partner_sku, pm.sku_parent) AS titleCache,",
                "         pm.cover_image_url AS imageUrlCache, scope.sourceStoreName",
                "  FROM storeScope scope",
                "  JOIN product_barcode pb ON pb.logical_store_id = scope.logicalStoreId",
                "   AND pb.is_deleted = b'0' AND COALESCE(pb.barcode_type, '') &lt;&gt; 'PARTNER_SKU_ALIAS'",
                "  JOIN ownerBarcodeIdentity identityScope ON identityScope.barcodeKey = BINARY pb.barcode",
                "  JOIN product_master pm ON pm.id = pb.product_master_id",
                "   AND pm.logical_store_id = pb.logical_store_id",
                "   AND pm.partner_sku = pb.partner_sku AND BINARY pm.partner_sku = BINARY pb.partner_sku",
                "   AND pm.is_deleted = b'0'",
                "  JOIN product_variant pv ON pv.product_master_id = pm.id",
                "   AND pv.partner_sku = pb.partner_sku AND BINARY pv.partner_sku = BINARY pb.partner_sku",
                "   AND pv.is_deleted = b'0'",
                "  JOIN product_site_offer pso ON pso.variant_id = pv.id",
                "   AND pso.site_id = scope.siteId AND pso.is_deleted = b'0'",
                "  WHERE NULLIF(TRIM(pb.barcode), '') IS NOT NULL",
                "), barcodeProducts AS (",
                "  SELECT barcodeKey, MIN(barcode) AS barcode, MIN(productMasterId) AS productMasterId,",
                "         MIN(productVariantId) AS productVariantId, MIN(productSiteOfferId) AS productSiteOfferId,",
                "         MIN(partnerSku) AS partnerSku, MIN(skuParent) AS skuParent, MIN(titleCache) AS titleCache,",
                "         MIN(imageUrlCache) AS imageUrlCache, MIN(sourceStoreName) AS sourceStoreName",
                "  FROM barcodeProductCandidates",
                "  GROUP BY barcodeKey",
                "  HAVING COUNT(DISTINCT productMasterId, productVariantId, BINARY partnerSku) = 1",
                ")"
        );
    }
}
