package com.nuono.next.infrastructure.mapper;

public final class OfficialWarehouseShippingBatchSqlProvider {

    private OfficialWarehouseShippingBatchSqlProvider() {
    }

    public static String listShippingBatchCandidates() {
        return String.join("\n",
                "<script>",
                "WITH storeScope AS (",
                "  SELECT ls.id AS logicalStoreId, lss.id AS siteId",
                "  FROM logical_store_site lss",
                "  JOIN logical_store ls ON ls.id = lss.logical_store_id",
                "   AND ls.owner_user_id = #{ownerUserId} AND ls.is_deleted = b'0'",
                "  WHERE lss.store_code = #{storeCode} AND lss.site = #{siteCode} AND lss.is_deleted = b'0'",
                "), storeProducts AS (",
                "  SELECT pv.id AS productVariantId, pso.psku_code AS pskuCode,",
                "         pm.partner_sku AS masterPartnerSku, pv.partner_sku AS variantPartnerSku,",
                "         pv.child_sku AS childSku, pm.sku_parent AS skuParent",
                "  FROM storeScope scope",
                "  JOIN product_site_offer pso ON pso.site_id = scope.siteId AND pso.is_deleted = b'0'",
                "  JOIN product_variant pv ON pv.id = pso.variant_id AND pv.is_deleted = b'0'",
                "  JOIN product_master pm ON pm.id = pv.product_master_id",
                "   AND pm.logical_store_id = scope.logicalStoreId AND pm.is_deleted = b'0'",
                "), productIdentifiers AS (",
                "  SELECT productVariantId, pskuCode AS identifier FROM storeProducts",
                "  WHERE pskuCode IS NOT NULL AND pskuCode &lt;&gt; ''",
                "  UNION ALL SELECT productVariantId, masterPartnerSku FROM storeProducts",
                "  WHERE masterPartnerSku IS NOT NULL AND masterPartnerSku &lt;&gt; ''",
                "  UNION ALL SELECT productVariantId, variantPartnerSku FROM storeProducts",
                "  WHERE variantPartnerSku IS NOT NULL AND variantPartnerSku &lt;&gt; ''",
                "  UNION ALL SELECT productVariantId, childSku FROM storeProducts",
                "  WHERE childSku IS NOT NULL AND childSku &lt;&gt; ''",
                "  UNION ALL SELECT productVariantId, skuParent FROM storeProducts",
                "  WHERE skuParent IS NOT NULL AND skuParent &lt;&gt; ''",
                "), allocationScope AS (",
                "  SELECT owner_user_id, in_transit_goods_line_id,",
                "         CAST(FLOOR(SUM(GREATEST(COALESCE(allocated_quantity, 0), 0))) AS SIGNED) AS scopedQuantity,",
                "         MIN(product_variant_id) AS allocatedProductVariantId",
                "  FROM procurement_logistics_shipment_allocation",
                "  WHERE owner_user_id = #{ownerUserId} AND is_deleted = b'0'",
                "    AND confirmation_status = 'CONFIRMED'",
                "    AND target_store_code = #{storeCode} AND target_site_code = #{siteCode}",
                "  GROUP BY owner_user_id, in_transit_goods_line_id",
                "), eligibleBatches AS (",
                "  SELECT b.id, b.owner_user_id, b.batch_reference_no, b.tracking_no, b.external_shipment_no,",
                "         COALESCE(f.forwarder_name, b.raw_forwarder_name) AS forwarderName,",
                "         b.transport_mode, b.batch_status, b.latest_node_status, b.gmt_updated",
                "  FROM in_transit_batch b",
                "  LEFT JOIN in_transit_forwarder f ON f.id = b.standard_forwarder_id",
                "   AND f.owner_user_id = b.owner_user_id AND f.is_deleted = b'0'",
                "  WHERE b.owner_user_id = #{ownerUserId} AND b.is_deleted = b'0'",
                "    AND (",
                "      (b.target_site_code IS NOT NULL AND b.target_site_code &lt;&gt; '' AND b.target_site_code = #{siteCode})",
                "      OR (#{siteCode} = 'SA' AND (COALESCE(b.target_store_code, '') LIKE 'RUH%'",
                "          OR COALESCE(b.target_store_code, '') LIKE 'JED%'))",
                "      OR (#{siteCode} = 'AE' AND (COALESCE(b.target_store_code, '') LIKE 'DB%'",
                "          OR COALESCE(b.target_store_code, '') LIKE 'DXB%'",
                "          OR COALESCE(b.target_store_code, '') LIKE 'AUH%'))",
                "    )",
                "    AND (b.batch_status IN ('shipped', 'in_transit', 'customs_clearance', 'delivering', 'warehouse_received')",
                "         OR b.latest_node_status IN ('departed_origin', 'in_transit', 'arrived_port', 'customs_clearance',",
                "                                      'customs_released', 'delivering', 'warehouse_received'))",
                "  <if test='keywordLike != null and keywordLike != \"\"'>",
                "    AND (b.batch_reference_no LIKE #{keywordLike} OR b.tracking_no LIKE #{keywordLike}",
                "         OR b.external_shipment_no LIKE #{keywordLike} OR b.raw_forwarder_name LIKE #{keywordLike}",
                "         OR f.forwarder_name LIKE #{keywordLike})",
                "  </if>",
                "), eligibleLines AS (",
                "  SELECT line.id, line.batch_id, line.owner_user_id, line.shipped_quantity,",
                "         line.psku, line.sku, line.msku, allocation.scopedQuantity,",
                "         allocation.allocatedProductVariantId",
                "  FROM eligibleBatches batch",
                "  JOIN in_transit_goods_line line ON line.batch_id = batch.id",
                "   AND line.owner_user_id = batch.owner_user_id AND line.is_deleted = b'0'",
                "  JOIN storeScope scope ON 1 = 1",
                "  LEFT JOIN allocationScope allocation ON allocation.owner_user_id = line.owner_user_id",
                "   AND allocation.in_transit_goods_line_id = line.id",
                "  WHERE allocation.in_transit_goods_line_id IS NOT NULL",
                "     OR (line.store_code = #{storeCode} AND line.site_code = #{siteCode})",
                "     OR EXISTS (",
                "       SELECT 1 FROM product_barcode scopeBarcode",
                "       WHERE scopeBarcode.logical_store_id = scope.logicalStoreId",
                "         AND scopeBarcode.is_deleted = b'0'",
                "         AND COALESCE(scopeBarcode.barcode_type, '') &lt;&gt; 'PARTNER_SKU_ALIAS'",
                "         AND scopeBarcode.barcode = line.sku",
                "         AND BINARY scopeBarcode.barcode = BINARY line.sku",
                "     )",
                "     OR EXISTS (",
                "       SELECT 1 FROM product_barcode scopeBarcode",
                "       WHERE scopeBarcode.logical_store_id = scope.logicalStoreId",
                "         AND scopeBarcode.is_deleted = b'0'",
                "         AND COALESCE(scopeBarcode.barcode_type, '') &lt;&gt; 'PARTNER_SKU_ALIAS'",
                "         AND scopeBarcode.partner_sku = line.psku",
                "         AND BINARY scopeBarcode.partner_sku = BINARY line.psku",
                "     )",
                "), lineIdentifiers AS (",
                "  SELECT id AS lineId, psku AS identifier FROM eligibleLines",
                "  WHERE psku IS NOT NULL AND psku &lt;&gt; ''",
                "  UNION ALL SELECT id, sku FROM eligibleLines WHERE sku IS NOT NULL AND sku &lt;&gt; ''",
                "  UNION ALL SELECT id, msku FROM eligibleLines WHERE msku IS NOT NULL AND msku &lt;&gt; ''",
                "), matchedProductCandidates AS (",
                "  SELECT identifier.lineId, product.productVariantId",
                "  FROM lineIdentifiers identifier",
                "  JOIN productIdentifiers product ON product.identifier = identifier.identifier",
                "  GROUP BY identifier.lineId, product.productVariantId",
                "), matchedProducts AS (",
                "  SELECT lineId, MIN(productVariantId) AS matchedProductVariantId",
                "  FROM matchedProductCandidates GROUP BY lineId",
                "), resolvedLines AS (",
                "  SELECT line.id, line.batch_id, line.owner_user_id, line.shipped_quantity,",
                "         line.psku, line.sku, line.msku, line.scopedQuantity",
                "  FROM eligibleLines line",
                "  LEFT JOIN matchedProducts matched ON matched.lineId = line.id",
                "  JOIN matchedProductCandidates identity ON identity.lineId = line.id",
                "   AND identity.productVariantId = COALESCE(line.allocatedProductVariantId, matched.matchedProductVariantId)",
                "), linked AS (",
                "  SELECT link.owner_user_id, link.in_transit_goods_line_id,",
                "         SUM(GREATEST(COALESCE(link.quantity, 0), 0)) AS linkedQuantity,",
                "         SUM(CASE WHEN EXISTS (",
                "           SELECT 1 FROM official_warehouse_appointment scheduledAppointment",
                "           WHERE scheduledAppointment.asn_id = link.asn_id",
                "             AND scheduledAppointment.owner_user_id = link.owner_user_id",
                "             AND scheduledAppointment.is_deleted = b'0'",
                "             AND scheduledAppointment.status = 'SCHEDULED'",
                "         ) THEN GREATEST(COALESCE(link.quantity, 0), 0) ELSE 0 END) AS scheduledAppointmentQuantity",
                "  FROM official_warehouse_asn_shipping_batch_link link",
                "  JOIN official_warehouse_asn linkedAsn ON linkedAsn.id = link.asn_id",
                "   AND linkedAsn.owner_user_id = link.owner_user_id AND linkedAsn.is_deleted = b'0'",
                "   AND UPPER(COALESCE(linkedAsn.status, '')) NOT IN ('FAILED', 'CANCELED', 'CANCELLED')",
                "  WHERE link.owner_user_id = #{ownerUserId} AND link.is_deleted = b'0'",
                "    AND link.in_transit_goods_line_id IS NOT NULL",
                "  GROUP BY link.owner_user_id, link.in_transit_goods_line_id",
                "), purchase AS (",
                "  SELECT owner_user_id, in_transit_goods_line_id, COUNT(DISTINCT source_id) AS purchaseOrderCount",
                "  FROM procurement_logistics_shipment_allocation",
                "  WHERE owner_user_id = #{ownerUserId} AND is_deleted = b'0' AND confirmation_status = 'CONFIRMED'",
                "  GROUP BY owner_user_id, in_transit_goods_line_id",
                ")",
                "SELECT batch.id, 'IN_TRANSIT_BATCH' AS sourceKind,",
                "       COALESCE(NULLIF(batch.batch_reference_no, ''), NULLIF(batch.tracking_no, ''),",
                "                NULLIF(batch.external_shipment_no, ''), CAST(batch.id AS CHAR)) AS batchNo,",
                "       batch.tracking_no AS trackingNo, batch.external_shipment_no AS externalShipmentNo,",
                "       batch.forwarderName, batch.transport_mode AS transportMode,",
                "       batch.batch_status AS status, batch.latest_node_status AS latestNodeStatus,",
                "       NULL AS selectedOptionId,",
                "       COALESCE(SUM(CASE WHEN line.scopedQuantity IS NOT NULL",
                "                         THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                         ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END), 0) AS totalQuantity,",
                "       COALESCE(SUM(CASE WHEN line.scopedQuantity IS NOT NULL",
                "                         THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                         ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END), 0) AS storeSiteQuantity,",
                "       COALESCE(SUM(LEAST(GREATEST(COALESCE(linked.linkedQuantity, 0), 0),",
                "                         CASE WHEN line.scopedQuantity IS NOT NULL",
                "                              THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                              ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END)), 0) AS linkedQuantity,",
                "       COALESCE(SUM(GREATEST((CASE WHEN line.scopedQuantity IS NOT NULL",
                "                                      THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                                      ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END)",
                "                                   - GREATEST(COALESCE(linked.scheduledAppointmentQuantity, 0), 0), 0)), 0) AS remainingQuantity,",
                "       COALESCE(SUM(LEAST(GREATEST(COALESCE(linked.scheduledAppointmentQuantity, 0), 0),",
                "                         CASE WHEN line.scopedQuantity IS NOT NULL",
                "                              THEN LEAST(GREATEST(COALESCE(line.shipped_quantity, 0), 0), line.scopedQuantity)",
                "                              ELSE GREATEST(COALESCE(line.shipped_quantity, 0), 0) END)), 0) AS scheduledAppointmentQuantity,",
                "       CASE WHEN COALESCE(SUM(GREATEST(COALESCE(linked.scheduledAppointmentQuantity, 0), 0)), 0) &gt; 0 THEN 1 ELSE 0 END AS alreadyAppointed,",
                "       CASE WHEN COALESCE(SUM(GREATEST(COALESCE(linked.linkedQuantity, 0), 0)), 0) &gt; 0 THEN 1 ELSE 0 END AS batchUsedByAsn,",
                "       CASE WHEN COALESCE(SUM(GREATEST(COALESCE(linked.scheduledAppointmentQuantity, 0), 0)), 0) &gt; 0 THEN '已约仓'",
                "            WHEN COALESCE(SUM(GREATEST(COALESCE(linked.linkedQuantity, 0), 0)), 0) &gt; 0 THEN '已建ASN'",
                "            ELSE '可约仓' END AS batchUsageLabel,",
                "       COUNT(DISTINCT COALESCE(NULLIF(line.psku, ''), NULLIF(line.sku, ''), NULLIF(line.msku, ''))) AS skuCount,",
                "       COALESCE(SUM(COALESCE(purchase.purchaseOrderCount, 0)), 0) AS purchaseOrderCount,",
                "       NULL AS storeSummaryJson, NULL AS siteSummaryJson, NULL AS transportSummaryJson,",
                "       DATE_FORMAT(batch.gmt_updated, '%Y-%m-%d %H:%i') AS updatedAt",
                "FROM eligibleBatches batch",
                "JOIN resolvedLines line ON line.batch_id = batch.id AND line.owner_user_id = batch.owner_user_id",
                "LEFT JOIN linked ON linked.owner_user_id = batch.owner_user_id",
                " AND linked.in_transit_goods_line_id = line.id",
                "LEFT JOIN purchase ON purchase.owner_user_id = batch.owner_user_id",
                " AND purchase.in_transit_goods_line_id = line.id",
                "GROUP BY batch.id, batch.batch_reference_no, batch.tracking_no, batch.external_shipment_no,",
                "         batch.forwarderName, batch.transport_mode, batch.batch_status, batch.latest_node_status, batch.gmt_updated",
                "ORDER BY batchUsedByAsn ASC, batch.gmt_updated DESC, batch.id DESC",
                "LIMIT #{limit}",
                "</script>"
        );
    }
}
