package com.nuono.next.infrastructure.mapper;

import com.nuono.next.postsaleprofit.PostSaleProfitSourceRecords.FinanceSaleCandidateRow;
import com.nuono.next.postsaleprofit.PostSaleProfitSourceRecords.HeadhaulCostBatchRow;
import com.nuono.next.postsaleprofit.PostSaleProfitSourceRecords.OrderSaleCandidateRow;
import com.nuono.next.postsaleprofit.PostSaleProfitSourceRecords.PurchaseCostBatchRow;
import com.nuono.next.postsaleprofit.PostSaleProfitBatchQuery;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.AttributionReadRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.AttributionTotalsRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.AttributionWriteRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.BatchMoveRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.BatchReadRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.BatchStatusRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.BatchWriteRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.FxRateRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.LockedAttributionRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.RecalculationRunRow;
import com.nuono.next.postsaleprofit.PostSaleProfitPersistenceRecords.TransferAttributionRow;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PostSaleProfitMapper {

    @Update({
            "UPDATE post_sale_profit_recalculation_run",
            "SET scope_hash = CONCAT(scope_hash, '|deleted|', id),",
            "    is_deleted = b'1',",
            "    gmt_updated = NOW()",
            "WHERE owner_user_id = #{ownerUserId}",
            "  AND store_code = #{storeCode}",
            "  AND site_code = #{siteCode}",
            "  AND date_from = #{dateFrom}",
            "  AND date_to = #{dateTo}",
            "  AND status = 'PREVIEW'",
            "  AND is_deleted = b'0'"
    })
    int softDeletePreviewRuns(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("dateFrom") LocalDate dateFrom,
            @Param("dateTo") LocalDate dateTo
    );

    @Insert({
            "INSERT INTO post_sale_profit_recalculation_run (",
            "owner_user_id, store_code, site_code, date_from, date_to, status, scope_hash,",
            "order_line_count, attributed_quantity, locked_quantity, unassigned_quantity, missing_issue_count,",
            "diagnostic_json, started_at, finished_at, created_by",
            ") VALUES (",
            "#{row.ownerUserId}, #{row.storeCode}, #{row.siteCode}, #{row.dateFrom}, #{row.dateTo}, #{row.status}, #{row.scopeHash},",
            "#{row.orderLineCount}, #{row.attributedQuantity}, #{row.lockedQuantity}, #{row.unassignedQuantity}, #{row.missingIssueCount},",
            "#{row.diagnosticJson}, #{row.startedAt}, #{row.finishedAt}, #{row.createdBy}",
            ")"
    })
    @Options(useGeneratedKeys = true, keyProperty = "row.id")
    int insertRecalculationRun(@Param("row") RecalculationRunRow row);

    @Insert({
            "INSERT INTO post_sale_profit_batch (",
            "run_id, owner_user_id, store_code, site_code, partner_sku, sku_parent, title_snapshot, image_url_snapshot,",
            "purchase_source_type, purchase_source_id, purchase_batch_time, purchase_quantity,",
            "purchase_unit_cost_cny, purchase_cost_cny,",
            "shipping_source_type, shipping_source_id, shipping_batch_no, in_transit_batch_id, in_transit_reference_no,",
            "available_at, available_at_source, headhaul_cost_source_type,",
            "headhaul_unit_cost_cny, headhaul_cost_cny, sold_quantity, auto_quantity, locked_quantity,",
            "net_proceeds_lcy, referral_fee_lcy, fulfillment_fee_lcy, other_fee_net_lcy,",
            "currency, fx_rate_to_cny, profit_cny, profit_rate,",
            "quality_status_json, evidence_json",
            ") VALUES (",
            "#{row.runId}, #{row.ownerUserId}, #{row.storeCode}, #{row.siteCode}, #{row.partnerSku},",
            "#{row.skuParent}, #{row.productTitle}, #{row.productImageUrl},",
            "CASE",
            "  WHEN #{row.sourceId} LIKE 'UNASSIGNED:%' THEN 'UNASSIGNED_ORDER_QUANTITY'",
            "  WHEN #{row.sourceId} LIKE 'ALI1688_ALLOCATION:%' THEN 'ALI1688_ALLOCATION'",
            "  WHEN #{row.sourceId} LIKE 'ALI1688_PRODUCT_LINK:%' THEN 'ALI1688_PRODUCT_LINK'",
            "  ELSE 'MANUAL_SKU_PURCHASE_BATCH'",
            "END,",
            "#{row.sourceId}, #{row.purchaseBatchTime}, #{row.purchaseQuantity},",
            "#{row.purchaseUnitCostCny}, #{row.purchaseCostCny},",
            "#{row.shippingSourceType}, #{row.shippingSourceId}, #{row.shippingBatchNo},",
            "#{row.inTransitBatchId}, #{row.inTransitReferenceNo}, #{row.availableAt}, #{row.availableAtSource},",
            "#{row.headhaulCostSourceType},",
            "#{row.headhaulUnitCostCny}, #{row.headhaulCostCny}, #{row.soldQuantity}, #{row.autoQuantity}, #{row.lockedQuantity},",
            "#{row.netProceedsLcy}, #{row.referralFeeLcy}, #{row.fulfillmentFeeLcy}, #{row.otherFeeNetLcy},",
            "#{row.currency}, #{row.fxRateToCny}, #{row.profitCny}, #{row.profitRate},",
            "#{row.qualityStatusJson}, #{row.evidenceJson}",
            ")"
    })
    @Options(useGeneratedKeys = true, keyProperty = "row.id")
    int insertBatch(@Param("row") BatchWriteRow row);

    @Insert({
            "INSERT INTO post_sale_profit_order_attribution (",
            "run_id, batch_id, owner_user_id, store_code, site_code, finance_item_nr,",
            "order_nr, item_nr, order_time, partner_sku, sku, attributed_quantity,",
            "attribution_method, locked, manual_reason, net_proceeds_lcy, referral_fee_lcy,",
            "fulfillment_fee_lcy, other_fee_net_lcy, currency, quality_status_json",
            ") VALUES (",
            "#{row.runId}, #{row.batchId}, #{row.ownerUserId}, #{row.storeCode}, #{row.siteCode}, #{row.financeItemNr},",
            "#{row.orderNr}, #{row.itemNr}, #{row.orderTime}, #{row.partnerSku}, #{row.sku}, #{row.attributedQuantity},",
            "#{row.attributionMethod}, #{row.locked}, #{row.manualReason}, #{row.netProceedsLcy}, #{row.referralFeeLcy},",
            "#{row.fulfillmentFeeLcy}, #{row.otherFeeNetLcy}, #{row.currency}, #{row.qualityStatusJson}",
            ")"
    })
    @Options(useGeneratedKeys = true, keyProperty = "row.id")
    int insertOrderAttribution(@Param("row") AttributionWriteRow row);

    @Select({
            "SELECT id",
            "FROM post_sale_profit_recalculation_run",
            "WHERE owner_user_id = #{ownerUserId}",
            "  AND store_code = #{storeCode}",
            "  AND site_code = #{siteCode}",
            "  AND date_from = #{dateFrom}",
            "  AND date_to = #{dateTo}",
            "  AND is_deleted = b'0'",
            "ORDER BY CASE WHEN status = 'PREVIEW' THEN 0 ELSE 1 END, finished_at DESC, id DESC",
            "LIMIT 1"
    })
    Long selectLatestRunId(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("dateFrom") LocalDate dateFrom,
            @Param("dateTo") LocalDate dateTo
    );

    @Select({
            "SELECT id AS id, owner_user_id AS ownerUserId, store_code AS storeCode, site_code AS siteCode,",
            "       date_from AS dateFrom, date_to AS dateTo, status AS status,",
            "       order_line_count AS orderLineCount, attributed_quantity AS attributedQuantity,",
            "       locked_quantity AS lockedQuantity, unassigned_quantity AS unassignedQuantity,",
            "       missing_issue_count AS missingIssueCount, diagnostic_json AS diagnosticJson,",
            "       started_at AS startedAt, finished_at AS finishedAt, created_by AS createdBy",
            "FROM post_sale_profit_recalculation_run",
            "WHERE owner_user_id = #{ownerUserId}",
            "  AND store_code = #{storeCode}",
            "  AND site_code = #{siteCode}",
            "  AND is_deleted = b'0'",
            "ORDER BY CASE WHEN status = 'PREVIEW' THEN 0 ELSE 1 END, finished_at DESC, id DESC",
            "LIMIT 1"
    })
    RecalculationRunRow selectLatestRun(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode
    );

    @Select({
            "SELECT fx.rate_to_cny",
            "FROM post_sale_profit_fx_rate fx",
            "WHERE (fx.owner_user_id = #{ownerUserId} OR fx.owner_user_id IS NULL)",
            "  AND fx.site_code = #{siteCode}",
            "  AND fx.currency = #{currency}",
            "  AND fx.effective_from <= #{dateTo}",
            "  AND (fx.effective_to IS NULL OR fx.effective_to >= #{dateFrom})",
            "  AND fx.status = 'ACTIVE'",
            "  AND fx.is_deleted = b'0'",
            "ORDER BY CASE WHEN fx.owner_user_id = #{ownerUserId} THEN 0 ELSE 1 END,",
            "         fx.effective_from DESC, fx.id DESC",
            "LIMIT 1"
    })
    BigDecimal selectApplicableFxRate(
            @Param("ownerUserId") Long ownerUserId,
            @Param("siteCode") String siteCode,
            @Param("currency") String currency,
            @Param("dateFrom") LocalDate dateFrom,
            @Param("dateTo") LocalDate dateTo
    );

    @Select({
            "SELECT fx.id AS id, fx.owner_user_id AS ownerUserId, fx.site_code AS siteCode,",
            "       fx.currency AS currency, fx.rate_to_cny AS rateToCny,",
            "       fx.effective_from AS effectiveFrom, fx.effective_to AS effectiveTo,",
            "       fx.source_label AS sourceLabel",
            "FROM post_sale_profit_fx_rate fx",
            "WHERE fx.owner_user_id = #{ownerUserId}",
            "  AND fx.site_code = #{siteCode}",
            "  AND fx.status = 'ACTIVE'",
            "  AND fx.is_deleted = b'0'",
            "ORDER BY fx.currency ASC, fx.effective_from DESC, fx.id DESC"
    })
    List<FxRateRow> listFxRates(
            @Param("ownerUserId") Long ownerUserId,
            @Param("siteCode") String siteCode
    );

    @Update({
            "UPDATE post_sale_profit_fx_rate",
            "SET is_deleted = b'1', gmt_updated = NOW()",
            "WHERE owner_user_id = #{row.ownerUserId}",
            "  AND site_code = #{row.siteCode}",
            "  AND currency = #{row.currency}",
            "  AND effective_from = #{row.effectiveFrom}",
            "  AND is_deleted = b'0'"
    })
    int softDeleteSameFxRate(@Param("row") FxRateRow row);

    @Insert({
            "INSERT INTO post_sale_profit_fx_rate (",
            "owner_user_id, site_code, currency, rate_to_cny, effective_from, effective_to, source_label, status",
            ") VALUES (",
            "#{row.ownerUserId}, #{row.siteCode}, #{row.currency}, #{row.rateToCny},",
            "#{row.effectiveFrom}, #{row.effectiveTo}, #{row.sourceLabel}, 'ACTIVE'",
            ")"
    })
    @Options(useGeneratedKeys = true, keyProperty = "row.id")
    int insertFxRate(@Param("row") FxRateRow row);

    @Select({
            "<script>",
            "SELECT COUNT(*)",
            "FROM post_sale_profit_batch batch",
            "WHERE batch.run_id = #{runId}",
            "  AND batch.owner_user_id = #{query.ownerUserId}",
            "  AND batch.store_code = #{query.storeCode}",
            "  AND batch.site_code = #{query.siteCode}",
            "  AND batch.is_deleted = b'0'",
            "<if test='query.keyword != null and query.keyword != \"\"'>",
            "  AND (batch.partner_sku LIKE CONCAT('%', #{query.keyword}, '%')",
            "       OR batch.sku_parent LIKE CONCAT('%', #{query.keyword}, '%')",
            "       OR batch.title_snapshot LIKE CONCAT('%', #{query.keyword}, '%'))",
            "</if>",
            "<if test='query.quality != null and query.quality != \"\"'>",
            "  AND batch.quality_status_json LIKE CONCAT('%', #{query.quality}, '%')",
            "</if>",
            "<if test='query.onlyLoss'>",
            "  AND batch.profit_cny IS NOT NULL AND batch.profit_cny &lt; 0",
            "</if>",
            "<if test='query.onlyMissing'>",
            "  AND (batch.quality_status_json LIKE '%MISSING_ORDER_LINE%'",
            "       OR batch.quality_status_json LIKE '%MISSING_FINANCE%'",
            "       OR batch.quality_status_json LIKE '%MISSING_PURCHASE_COST%'",
            "       OR batch.quality_status_json LIKE '%MISSING_HEADHAUL%'",
            "       OR batch.quality_status_json LIKE '%MISSING_FX_RATE%'",
            "       OR batch.quality_status_json LIKE '%UNASSIGNED_ORDER_QUANTITY%')",
            "</if>",
            "</script>"
    })
    int countBatchRows(
            @Param("runId") Long runId,
            @Param("query") PostSaleProfitBatchQuery query
    );

    @Select({
            "<script>",
            "SELECT batch.id AS id, batch.purchase_source_id AS sourceId, batch.partner_sku AS partnerSku,",
            "       COALESCE(batch.sku_parent, catalog_partner_master.sku_parent, catalog_offer_master.sku_parent) AS skuParent,",
            "       COALESCE(NULLIF(batch.title_snapshot, ''),",
            "                NULLIF(catalog_partner_master.title_cn_cache, ''), NULLIF(catalog_partner_master.title_cache, ''),",
            "                NULLIF(catalog_offer_master.title_cn_cache, ''), NULLIF(catalog_offer_master.title_cache, '')) AS productTitle,",
            "       COALESCE(NULLIF(batch.image_url_snapshot, ''), catalog_partner_master.cover_image_url, catalog_offer_master.cover_image_url) AS productImageUrl,",
            "       batch.purchase_batch_time AS purchaseBatchTime,",
            "       batch.purchase_quantity AS purchaseQuantity,",
            "       batch.purchase_unit_cost_cny AS purchaseUnitCostCny,",
            "       batch.purchase_cost_cny AS purchaseCostCny,",
            "       batch.shipping_source_type AS shippingSourceType,",
            "       batch.shipping_source_id AS shippingSourceId,",
            "       batch.shipping_batch_no AS shippingBatchNo,",
            "       batch.in_transit_batch_id AS inTransitBatchId,",
            "       batch.in_transit_reference_no AS inTransitReferenceNo,",
            "       batch.available_at AS availableAt,",
            "       batch.available_at_source AS availableAtSource,",
            "       batch.headhaul_cost_source_type AS headhaulCostSourceType,",
            "       batch.headhaul_unit_cost_cny AS headhaulUnitCostCny,",
            "       batch.headhaul_cost_cny AS headhaulCostCny,",
            "       batch.sold_quantity AS soldQuantity, batch.auto_quantity AS autoQuantity,",
            "       batch.locked_quantity AS lockedQuantity, batch.net_proceeds_lcy AS netProceedsLcy,",
            "       batch.referral_fee_lcy AS referralFeeLcy,",
            "       batch.fulfillment_fee_lcy AS fulfillmentFeeLcy,",
            "       batch.other_fee_net_lcy AS otherFeeNetLcy,",
            "       sale_summary.average_sale_price_lcy AS averageSalePriceLcy,",
            "       sale_summary.gmv_lcy AS gmvLcy,",
            "       sale_summary.sale_price_fact_count AS salePriceFactCount,",
            "       batch.currency AS currency, batch.fx_rate_to_cny AS fxRateToCny,",
            "       batch.profit_cny AS profitCny, batch.profit_rate AS profitRate,",
            "       batch.quality_status_json AS qualityStatusJson,",
            "       batch.evidence_json AS evidenceJson",
            "FROM post_sale_profit_batch batch",
            "LEFT JOIN logical_store_site catalog_site",
            "  ON catalog_site.store_code COLLATE utf8mb4_unicode_ci = batch.store_code COLLATE utf8mb4_unicode_ci",
            " AND catalog_site.site COLLATE utf8mb4_unicode_ci = batch.site_code COLLATE utf8mb4_unicode_ci",
            " AND catalog_site.is_deleted = b'0'",
            "LEFT JOIN logical_store catalog_store",
            "  ON catalog_store.id = catalog_site.logical_store_id",
            " AND catalog_store.owner_user_id = batch.owner_user_id",
            " AND catalog_store.is_deleted = b'0'",
            "LEFT JOIN product_variant catalog_partner_variant",
            "  ON catalog_partner_variant.partner_sku COLLATE utf8mb4_unicode_ci = batch.partner_sku COLLATE utf8mb4_unicode_ci",
            " AND catalog_partner_variant.is_deleted = b'0'",
            "LEFT JOIN product_master catalog_partner_master",
            "  ON catalog_partner_master.id = catalog_partner_variant.product_master_id",
            " AND catalog_partner_master.logical_store_id = catalog_store.id",
            " AND catalog_partner_master.is_deleted = b'0'",
            "LEFT JOIN product_site_offer catalog_offer",
            "  ON catalog_offer.site_id = catalog_site.id",
            " AND catalog_offer.psku_code COLLATE utf8mb4_unicode_ci = batch.partner_sku COLLATE utf8mb4_unicode_ci",
            " AND catalog_offer.is_deleted = b'0'",
            "LEFT JOIN product_variant catalog_offer_variant",
            "  ON catalog_offer_variant.id = catalog_offer.variant_id",
            " AND catalog_offer_variant.is_deleted = b'0'",
            "LEFT JOIN product_master catalog_offer_master",
            "  ON catalog_offer_master.id = catalog_offer_variant.product_master_id",
            " AND catalog_offer_master.logical_store_id = catalog_store.id",
            " AND catalog_offer_master.is_deleted = b'0'",
            "LEFT JOIN (",
            "  SELECT attr.batch_id,",
            "         SUM(order_line.offer_price) / NULLIF(SUM(attr.attributed_quantity), 0) AS average_sale_price_lcy,",
            "         SUM(order_line.gmv_lcy) AS gmv_lcy,",
            "         COUNT(order_line.id) AS sale_price_fact_count",
            "  FROM post_sale_profit_order_attribution attr",
            "  LEFT JOIN noon_order_line_fact order_line",
            "    ON order_line.owner_user_id = attr.owner_user_id",
            "   AND order_line.store_code COLLATE utf8mb4_unicode_ci = attr.store_code COLLATE utf8mb4_unicode_ci",
            "   AND order_line.site_code COLLATE utf8mb4_unicode_ci = attr.site_code COLLATE utf8mb4_unicode_ci",
            "   AND order_line.order_identity COLLATE utf8mb4_unicode_ci = attr.order_nr COLLATE utf8mb4_unicode_ci",
            "   AND order_line.item_nr COLLATE utf8mb4_unicode_ci = attr.item_nr COLLATE utf8mb4_unicode_ci",
            "  WHERE attr.run_id = #{runId}",
            "    AND attr.is_deleted = b'0'",
            "  GROUP BY attr.batch_id",
            ") sale_summary ON sale_summary.batch_id = batch.id",
            "WHERE batch.run_id = #{runId}",
            "  AND batch.owner_user_id = #{query.ownerUserId}",
            "  AND batch.store_code = #{query.storeCode}",
            "  AND batch.site_code = #{query.siteCode}",
            "  AND batch.is_deleted = b'0'",
            "<if test='query.keyword != null and query.keyword != \"\"'>",
            "  AND (batch.partner_sku LIKE CONCAT('%', #{query.keyword}, '%')",
            "       OR batch.sku_parent LIKE CONCAT('%', #{query.keyword}, '%')",
            "       OR batch.title_snapshot LIKE CONCAT('%', #{query.keyword}, '%'))",
            "</if>",
            "<if test='query.quality != null and query.quality != \"\"'>",
            "  AND batch.quality_status_json LIKE CONCAT('%', #{query.quality}, '%')",
            "</if>",
            "<if test='query.onlyLoss'>",
            "  AND batch.profit_cny IS NOT NULL AND batch.profit_cny &lt; 0",
            "</if>",
            "<if test='query.onlyMissing'>",
            "  AND (batch.quality_status_json LIKE '%MISSING_ORDER_LINE%'",
            "       OR batch.quality_status_json LIKE '%MISSING_FINANCE%'",
            "       OR batch.quality_status_json LIKE '%MISSING_PURCHASE_COST%'",
            "       OR batch.quality_status_json LIKE '%MISSING_HEADHAUL%'",
            "       OR batch.quality_status_json LIKE '%MISSING_FX_RATE%'",
            "       OR batch.quality_status_json LIKE '%UNASSIGNED_ORDER_QUANTITY%')",
            "</if>",
            "ORDER BY CASE WHEN batch.profit_cny IS NULL THEN 0 ELSE 1 END ASC,",
            "         batch.profit_cny ASC, batch.sold_quantity DESC, batch.id ASC",
            "LIMIT #{limit} OFFSET #{offset}",
            "</script>"
    })
    List<BatchReadRow> listBatchRows(
            @Param("runId") Long runId,
            @Param("query") PostSaleProfitBatchQuery query,
            @Param("offset") Integer offset,
            @Param("limit") Integer limit
    );

    @Select({
            "SELECT attr.id AS id, attr.order_nr AS orderNr, attr.item_nr AS itemNr,",
            "       attr.order_time AS orderTime, attr.partner_sku AS partnerSku, attr.sku AS sku,",
            "       attr.attributed_quantity AS attributedQuantity,",
            "       attr.attribution_method AS attributionMethod,",
            "       CASE WHEN attr.locked = b'1' THEN TRUE ELSE FALSE END AS locked,",
            "       attr.manual_reason AS manualReason,",
            "       attr.net_proceeds_lcy AS netProceedsLcy,",
            "       attr.referral_fee_lcy AS referralFeeLcy,",
            "       attr.fulfillment_fee_lcy AS fulfillmentFeeLcy,",
            "       attr.other_fee_net_lcy AS otherFeeNetLcy,",
            "       attr.currency AS currency",
            "FROM post_sale_profit_order_attribution attr",
            "WHERE attr.owner_user_id = #{ownerUserId}",
            "  AND attr.store_code = #{storeCode}",
            "  AND attr.site_code = #{siteCode}",
            "  AND attr.batch_id = #{batchId}",
            "  AND attr.is_deleted = b'0'",
            "ORDER BY attr.order_time ASC, attr.id ASC"
    })
    List<AttributionReadRow> listOrderAttributions(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("batchId") Long batchId
    );

    @Select({
            "SELECT attr.item_nr AS itemNr,",
            "       batch.purchase_source_id AS sourceId,",
            "       attr.attributed_quantity AS quantity,",
            "       attr.manual_reason AS manualReason",
            "FROM post_sale_profit_order_attribution attr",
            "JOIN post_sale_profit_batch batch",
            "  ON batch.owner_user_id = attr.owner_user_id",
            " AND batch.store_code = attr.store_code",
            " AND batch.site_code = attr.site_code",
            " AND batch.run_id = attr.run_id",
            " AND batch.id = attr.batch_id",
            " AND batch.is_deleted = b'0'",
            "JOIN post_sale_profit_recalculation_run run",
            "  ON run.id = attr.run_id",
            " AND run.owner_user_id = attr.owner_user_id",
            " AND run.store_code = attr.store_code",
            " AND run.site_code = attr.site_code",
            " AND run.is_deleted = b'0'",
            "WHERE attr.owner_user_id = #{ownerUserId}",
            "  AND attr.store_code = #{storeCode}",
            "  AND attr.site_code = #{siteCode}",
            "  AND attr.locked = b'1'",
            "  AND attr.is_deleted = b'0'",
            "  AND run.status = 'PREVIEW'",
            "  AND run.date_from = #{dateFrom}",
            "  AND run.date_to = #{dateTo}",
            "ORDER BY attr.order_time ASC, attr.id ASC"
    })
    List<LockedAttributionRow> listLockedAttributionsForScope(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("dateFrom") LocalDate dateFrom,
            @Param("dateTo") LocalDate dateTo
    );

    @Select({
            "SELECT batch.id AS id, batch.sold_quantity AS soldQuantity,",
            "       batch.locked_quantity AS lockedQuantity,",
            "       batch.quality_status_json AS qualityStatusJson",
            "FROM post_sale_profit_batch batch",
            "WHERE batch.owner_user_id = #{ownerUserId}",
            "  AND batch.store_code = #{storeCode}",
            "  AND batch.site_code = #{siteCode}",
            "  AND batch.id = #{batchId}",
            "  AND batch.is_deleted = b'0'",
            "LIMIT 1"
    })
    BatchStatusRow selectBatchStatus(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("batchId") Long batchId
    );

    @Update({
            "UPDATE post_sale_profit_order_attribution",
            "SET locked = #{locked}, attribution_method = #{attributionMethod},",
            "    manual_reason = #{manualReason}, gmt_updated = NOW()",
            "WHERE owner_user_id = #{ownerUserId}",
            "  AND store_code = #{storeCode}",
            "  AND site_code = #{siteCode}",
            "  AND batch_id = #{batchId}",
            "  AND is_deleted = b'0'"
    })
    int updateBatchAttributionLockState(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("batchId") Long batchId,
            @Param("locked") boolean locked,
            @Param("attributionMethod") String attributionMethod,
            @Param("manualReason") String manualReason
    );

    @Update({
            "UPDATE post_sale_profit_batch",
            "SET locked_quantity = #{lockedQuantity},",
            "    auto_quantity = #{autoQuantity},",
            "    quality_status_json = #{qualityStatusJson},",
            "    gmt_updated = NOW()",
            "WHERE owner_user_id = #{ownerUserId}",
            "  AND store_code = #{storeCode}",
            "  AND site_code = #{siteCode}",
            "  AND id = #{batchId}",
            "  AND is_deleted = b'0'"
    })
    int updateBatchLockSummary(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("batchId") Long batchId,
            @Param("lockedQuantity") BigDecimal lockedQuantity,
            @Param("autoQuantity") BigDecimal autoQuantity,
            @Param("qualityStatusJson") String qualityStatusJson
    );

    @Select({
            "SELECT batch.id AS id, batch.run_id AS runId, batch.partner_sku AS partnerSku,",
            "       batch.purchase_unit_cost_cny AS purchaseUnitCostCny,",
            "       batch.headhaul_unit_cost_cny AS headhaulUnitCostCny,",
            "       batch.fx_rate_to_cny AS fxRateToCny,",
            "       batch.quality_status_json AS qualityStatusJson",
            "FROM post_sale_profit_batch batch",
            "WHERE batch.owner_user_id = #{ownerUserId}",
            "  AND batch.store_code = #{storeCode}",
            "  AND batch.site_code = #{siteCode}",
            "  AND batch.id = #{batchId}",
            "  AND batch.is_deleted = b'0'",
            "LIMIT 1"
    })
    BatchMoveRow selectBatchForMove(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("batchId") Long batchId
    );

    @Select({
            "SELECT attr.id AS id, attr.run_id AS runId, attr.finance_item_nr AS financeItemNr,",
            "       attr.order_nr AS orderNr, attr.item_nr AS itemNr, attr.order_time AS orderTime,",
            "       attr.partner_sku AS partnerSku, attr.sku AS sku,",
            "       attr.attributed_quantity AS attributedQuantity,",
            "       attr.net_proceeds_lcy AS netProceedsLcy,",
            "       attr.referral_fee_lcy AS referralFeeLcy,",
            "       attr.fulfillment_fee_lcy AS fulfillmentFeeLcy,",
            "       attr.other_fee_net_lcy AS otherFeeNetLcy,",
            "       attr.currency AS currency",
            "FROM post_sale_profit_order_attribution attr",
            "WHERE attr.owner_user_id = #{ownerUserId}",
            "  AND attr.store_code = #{storeCode}",
            "  AND attr.site_code = #{siteCode}",
            "  AND attr.batch_id = #{batchId}",
            "  AND attr.is_deleted = b'0'",
            "ORDER BY attr.locked ASC, attr.order_time ASC, attr.id ASC"
    })
    List<TransferAttributionRow> listTransferableAttributions(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("batchId") Long batchId
    );

    @Update({
            "UPDATE post_sale_profit_order_attribution",
            "SET attributed_quantity = #{attributedQuantity},",
            "    net_proceeds_lcy = #{netProceedsLcy},",
            "    referral_fee_lcy = #{referralFeeLcy},",
            "    fulfillment_fee_lcy = #{fulfillmentFeeLcy},",
            "    other_fee_net_lcy = #{otherFeeNetLcy},",
            "    gmt_updated = NOW()",
            "WHERE owner_user_id = #{ownerUserId}",
            "  AND store_code = #{storeCode}",
            "  AND site_code = #{siteCode}",
            "  AND id = #{attributionId}",
            "  AND is_deleted = b'0'"
    })
    int updateAttributionSlice(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("attributionId") Long attributionId,
            @Param("attributedQuantity") BigDecimal attributedQuantity,
            @Param("netProceedsLcy") BigDecimal netProceedsLcy,
            @Param("referralFeeLcy") BigDecimal referralFeeLcy,
            @Param("fulfillmentFeeLcy") BigDecimal fulfillmentFeeLcy,
            @Param("otherFeeNetLcy") BigDecimal otherFeeNetLcy
    );

    @Update({
            "UPDATE post_sale_profit_order_attribution",
            "SET is_deleted = b'1', gmt_updated = NOW()",
            "WHERE owner_user_id = #{ownerUserId}",
            "  AND store_code = #{storeCode}",
            "  AND site_code = #{siteCode}",
            "  AND id = #{attributionId}",
            "  AND is_deleted = b'0'"
    })
    int softDeleteAttributionSlice(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("attributionId") Long attributionId
    );

    @Select({
            "SELECT COALESCE(SUM(attr.attributed_quantity), 0) AS soldQuantity,",
            "       COALESCE(SUM(CASE WHEN attr.locked = b'1' THEN 0 ELSE attr.attributed_quantity END), 0) AS autoQuantity,",
            "       COALESCE(SUM(CASE WHEN attr.locked = b'1' THEN attr.attributed_quantity ELSE 0 END), 0) AS lockedQuantity,",
            "       COALESCE(SUM(attr.net_proceeds_lcy), 0) AS netProceedsLcy,",
            "       COALESCE(SUM(attr.referral_fee_lcy), 0) AS referralFeeLcy,",
            "       COALESCE(SUM(attr.fulfillment_fee_lcy), 0) AS fulfillmentFeeLcy,",
            "       COALESCE(SUM(attr.other_fee_net_lcy), 0) AS otherFeeNetLcy,",
            "       MAX(attr.currency) AS currency",
            "FROM post_sale_profit_order_attribution attr",
            "WHERE attr.owner_user_id = #{ownerUserId}",
            "  AND attr.store_code = #{storeCode}",
            "  AND attr.site_code = #{siteCode}",
            "  AND attr.batch_id = #{batchId}",
            "  AND attr.is_deleted = b'0'"
    })
    AttributionTotalsRow selectBatchAttributionTotals(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("batchId") Long batchId
    );

    @Update({
            "UPDATE post_sale_profit_batch",
            "SET sold_quantity = #{soldQuantity},",
            "    auto_quantity = #{autoQuantity},",
            "    locked_quantity = #{lockedQuantity},",
            "    net_proceeds_lcy = #{netProceedsLcy},",
            "    referral_fee_lcy = #{referralFeeLcy},",
            "    fulfillment_fee_lcy = #{fulfillmentFeeLcy},",
            "    other_fee_net_lcy = #{otherFeeNetLcy},",
            "    currency = #{currency},",
            "    purchase_cost_cny = #{purchaseCostCny},",
            "    headhaul_cost_cny = #{headhaulCostCny},",
            "    profit_cny = #{profitCny},",
            "    profit_rate = #{profitRate},",
            "    quality_status_json = #{qualityStatusJson},",
            "    gmt_updated = NOW()",
            "WHERE owner_user_id = #{ownerUserId}",
            "  AND store_code = #{storeCode}",
            "  AND site_code = #{siteCode}",
            "  AND id = #{batchId}",
            "  AND is_deleted = b'0'"
    })
    int updateBatchFinancialSummary(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("batchId") Long batchId,
            @Param("soldQuantity") BigDecimal soldQuantity,
            @Param("autoQuantity") BigDecimal autoQuantity,
            @Param("lockedQuantity") BigDecimal lockedQuantity,
            @Param("netProceedsLcy") BigDecimal netProceedsLcy,
            @Param("referralFeeLcy") BigDecimal referralFeeLcy,
            @Param("fulfillmentFeeLcy") BigDecimal fulfillmentFeeLcy,
            @Param("otherFeeNetLcy") BigDecimal otherFeeNetLcy,
            @Param("currency") String currency,
            @Param("purchaseCostCny") BigDecimal purchaseCostCny,
            @Param("headhaulCostCny") BigDecimal headhaulCostCny,
            @Param("profitCny") BigDecimal profitCny,
            @Param("profitRate") BigDecimal profitRate,
            @Param("qualityStatusJson") String qualityStatusJson
    );

    @Select({
            "SELECT finance.item_nr AS item_nr, finance.order_nr AS order_nr,",
            "       COALESCE(NULLIF(finance.partner_sku, ''), finance_variant.partner_sku) AS partner_sku, finance.sku AS sku,",
            "       CAST(1 AS DECIMAL(18,4)) AS sold_quantity,",
            "       SUM(finance.net_proceeds) AS net_proceeds_lcy,",
            "       SUM(finance.referral_fee_including_vat) AS referral_fee_lcy,",
            "       SUM(finance.fulfillment_logistics_fees_including_vat) AS fulfillment_fee_lcy,",
            "       SUM(finance.shipping_credits_including_vat",
            "           + finance.other_order_fees_including_vat",
            "           + finance.order_subsidies_including_vat",
            "           + finance.non_order_fees_including_vat",
            "           + finance.non_order_subsidies_including_vat",
            "           + finance.others_including_vat) AS other_fee_net_lcy,",
            "       finance.currency AS currency,",
            "       CAST(MAX(finance.order_date) AS DATETIME) AS order_time",
            "FROM noon_finance_transaction_fact finance",
            "LEFT JOIN logical_store_site finance_site",
            "  ON finance_site.store_code = finance.store_code",
            " AND finance_site.site = finance.site_code",
            " AND finance_site.is_deleted = b'0'",
            "LEFT JOIN product_site_offer finance_offer",
            "  ON finance_offer.site_id = finance_site.id",
            " AND finance_offer.psku_code = SUBSTRING_INDEX(finance.sku, '-', 1)",
            " AND finance_offer.is_deleted = b'0'",
            "LEFT JOIN product_variant finance_variant",
            "  ON finance_variant.id = finance_offer.variant_id",
            " AND finance_variant.is_deleted = b'0'",
            "WHERE finance.owner_user_id = #{ownerUserId}",
            "  AND finance.store_code = #{storeCode}",
            "  AND finance.site_code = #{siteCode}",
            "  AND finance.transaction_date >= #{dateFrom}",
            "  AND finance.transaction_date <= #{dateTo}",
            "GROUP BY finance.item_nr, finance.order_nr,",
            "         COALESCE(NULLIF(finance.partner_sku, ''), finance_variant.partner_sku), finance.sku, finance.currency",
            "ORDER BY order_time ASC, finance.item_nr ASC"
    })
    List<FinanceSaleCandidateRow> listFinanceSaleCandidates(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("dateFrom") LocalDate dateFrom,
            @Param("dateTo") LocalDate dateTo
    );

    @Select({
            "SELECT MIN(order_line.id) AS order_line_fact_id, order_line.item_nr AS item_nr,",
            "       order_line.order_identity AS order_nr, order_line.partner_sku AS partner_sku,",
            "       order_line.sku AS sku, COUNT(*) AS sold_quantity,",
            "       SUM(order_line.offer_price) AS offer_price_lcy,",
            "       SUM(order_line.gmv_lcy) AS gmv_lcy,",
            "       MAX(order_line.currency_code) AS currency,",
            "       MIN(order_line.order_timestamp) AS order_time",
            "FROM noon_order_line_fact order_line",
            "WHERE order_line.owner_user_id = #{ownerUserId}",
            "  AND order_line.store_code = #{storeCode}",
            "  AND order_line.site_code = #{siteCode}",
            "  AND DATE(order_line.order_timestamp) >= #{dateFrom}",
            "  AND DATE(order_line.order_timestamp) <= #{dateTo}",
            "GROUP BY order_line.item_nr, order_line.order_identity, order_line.partner_sku, order_line.sku",
            "ORDER BY order_time ASC, order_line.item_nr ASC"
    })
    List<OrderSaleCandidateRow> listOrderSaleCandidates(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode,
            @Param("dateFrom") LocalDate dateFrom,
            @Param("dateTo") LocalDate dateTo
    );

    @Select({
            "SELECT purchase.source_id, purchase.batch_id, purchase.source_type,",
            "       purchase.store_code, purchase.site_code, purchase.sku_parent,",
            "       purchase.partner_sku, purchase.psku_code, purchase.batch_label,",
            "       purchase.product_title, purchase.product_image_url,",
            "       purchase.purchase_batch_time, purchase.purchase_quantity,",
            "       purchase.purchase_cost_cny, purchase.purchase_unit_cost_cny,",
            "       purchase.provider_order_no AS providerOrderNo, purchase.item_id AS itemId,",
            "       purchase.assignment_id AS assignmentId, purchase.source_title AS sourceTitle,",
            "       purchase.source_sku_text AS sourceSkuText, purchase.source_model_text AS sourceModelText,",
            "       purchase.source_image_url AS sourceImageUrl, purchase.source_quantity AS sourceQuantity,",
            "       purchase.source_unit AS sourceUnit, purchase.source_amount AS sourceAmount,",
            "       purchase.paid_amount AS paidAmount, purchase.assignment_quantity AS assignmentQuantity,",
            "       purchase.consumed_source_quantity AS consumedSourceQuantity, purchase.sku_quantity AS skuQuantity,",
            "       purchase.pack_size AS packSize, purchase.allocation_basis AS allocationBasis,",
            "       purchase.evidence_text AS evidenceText",
            "FROM (",
            "SELECT CONCAT('MANUAL_SKU_PURCHASE_BATCH:', batch.id) AS source_id,",
            "       batch.id AS batch_id, 'MANUAL_SKU_PURCHASE_BATCH' AS source_type,",
            "       lss.store_code AS store_code, lss.site AS site_code,",
            "       batch.sku_parent AS sku_parent, batch.partner_sku AS partner_sku, batch.psku_code AS psku_code,",
            "       manual_master.title_cache AS product_title, manual_master.cover_image_url AS product_image_url,",
            "       batch.batch_label AS batch_label,",
            "       COALESCE(MIN(source.source_order_time), batch.gmt_create) AS purchase_batch_time,",
            "       batch.counted_quantity AS purchase_quantity,",
            "       batch.counted_cost AS purchase_cost_cny,",
            "       batch.counted_cost / NULLIF(batch.counted_quantity, 0) AS purchase_unit_cost_cny,",
            "       MIN(source.source_order_no) AS provider_order_no,",
            "       MIN(source.item_id) AS item_id,",
            "       MIN(source.assignment_id) AS assignment_id,",
            "       NULL AS source_title, NULL AS source_sku_text, NULL AS source_model_text,",
            "       NULL AS source_image_url, batch.counted_quantity AS source_quantity,",
            "       NULL AS source_unit, batch.counted_cost AS source_amount, batch.counted_cost AS paid_amount,",
            "       NULL AS assignment_quantity, NULL AS consumed_source_quantity,",
            "       batch.counted_quantity AS sku_quantity, NULL AS pack_size,",
            "       'MANUAL_CONFIRMED' AS allocation_basis, MAX(batch.note) AS evidence_text,",
            "       batch.batch_sequence AS source_sequence",
            "FROM procurement_ali1688_sku_purchase_batch batch",
            "JOIN logical_store ls",
            "  ON ls.owner_user_id = batch.owner_user_id",
            " AND ls.project_code COLLATE utf8mb4_unicode_ci = batch.target_store_code COLLATE utf8mb4_unicode_ci",
            " AND ls.is_deleted = b'0'",
            "JOIN logical_store_site lss",
            "  ON lss.logical_store_id = ls.id",
            " AND lss.store_code = #{storeCode}",
            " AND lss.site = #{siteCode}",
            " AND lss.is_deleted = b'0'",
            "LEFT JOIN product_master manual_master",
            "  ON manual_master.logical_store_id = ls.id",
            " AND manual_master.sku_parent COLLATE utf8mb4_unicode_ci = batch.sku_parent COLLATE utf8mb4_unicode_ci",
            " AND manual_master.is_deleted = b'0'",
            "LEFT JOIN procurement_ali1688_sku_purchase_batch_source source",
            "  ON source.owner_user_id = batch.owner_user_id",
            " AND source.batch_id = batch.id",
            " AND source.status = 'active'",
            " AND source.is_deleted = b'0'",
            "WHERE batch.owner_user_id = #{ownerUserId}",
            "  AND batch.status = 'active'",
            "  AND batch.is_deleted = b'0'",
            "  AND (batch.target_site_code = #{siteCode} OR batch.target_site_code = '*')",
            "GROUP BY batch.id, lss.store_code, lss.site, batch.sku_parent, batch.partner_sku,",
            "         batch.psku_code, manual_master.title_cache, manual_master.cover_image_url,",
            "         batch.batch_label, batch.gmt_create, batch.counted_quantity, batch.counted_cost",
            "UNION ALL",
            "SELECT CONCAT('ALI1688_ALLOCATION:', allocation.order_id, ':',",
            "              COALESCE(allocation.assignment_id, allocation.item_id, 0), ':',",
            "              COALESCE(NULLIF(allocation.partner_sku, ''), NULLIF(allocation.psku_code, ''), allocation.sku_parent)) AS source_id,",
            "       NULL AS batch_id, 'ALI1688_ALLOCATION' AS source_type,",
            "       lss.store_code AS store_code, lss.site AS site_code,",
            "       allocation.sku_parent AS sku_parent,",
            "       allocation.partner_sku AS partner_sku, allocation.psku_code AS psku_code,",
            "       COALESCE(NULLIF(allocation.product_title, ''), NULLIF(allocation_master.title_cache, '')) AS product_title,",
            "       COALESCE(NULLIF(allocation_master.cover_image_url, ''), NULLIF(allocation.product_image_url, '')) AS product_image_url,",
            "       CONCAT('1688 allocation ', allocation_header.provider_order_no) AS batch_label,",
            "       COALESCE(allocation_header.order_time, MIN(allocation.gmt_create)) AS purchase_batch_time,",
            "       SUM(CASE WHEN allocation.sku_quantity > 0 THEN allocation.sku_quantity ELSE 0 END) AS purchase_quantity,",
            "       SUM(allocation.allocated_cost) AS purchase_cost_cny,",
            "       SUM(allocation.allocated_cost) / NULLIF(SUM(CASE WHEN allocation.sku_quantity > 0 THEN allocation.sku_quantity ELSE 0 END), 0) AS purchase_unit_cost_cny,",
            "       allocation_header.provider_order_no AS provider_order_no,",
            "       allocation.item_id AS item_id, allocation.assignment_id AS assignment_id,",
            "       MAX(allocation.source_line_label) AS source_title,",
            "       MAX(allocation.source_line_key) AS source_sku_text, NULL AS source_model_text,",
            "       MAX(allocation.product_image_url) AS source_image_url,",
            "       MAX(allocation.source_quantity) AS source_quantity, MAX(allocation.source_unit) AS source_unit,",
            "       MAX(allocation.source_amount) AS source_amount, SUM(allocation.allocated_cost) AS paid_amount,",
            "       NULL AS assignment_quantity, SUM(allocation.consumed_source_quantity) AS consumed_source_quantity,",
            "       SUM(allocation.sku_quantity) AS sku_quantity, MAX(allocation.pack_size) AS pack_size,",
            "       MAX(allocation.allocation_basis) AS allocation_basis, MAX(allocation.evidence_text) AS evidence_text,",
            "       COALESCE(allocation.assignment_id, allocation.item_id, allocation.order_id) AS source_sequence",
            "FROM procurement_ali1688_order_sku_allocation allocation",
            "JOIN procurement_ali1688_order_header allocation_header",
            "  ON allocation_header.owner_user_id = allocation.owner_user_id",
            " AND allocation_header.id = allocation.order_id",
            " AND allocation_header.is_deleted = b'0'",
            "JOIN logical_store ls",
            "  ON ls.owner_user_id = allocation.owner_user_id",
            " AND allocation.target_store_code COLLATE utf8mb4_unicode_ci = ls.project_code COLLATE utf8mb4_unicode_ci",
            " AND ls.is_deleted = b'0'",
            "JOIN logical_store_site lss",
            "  ON lss.logical_store_id = ls.id",
            " AND lss.store_code COLLATE utf8mb4_unicode_ci = #{storeCode} COLLATE utf8mb4_unicode_ci",
            " AND lss.site COLLATE utf8mb4_unicode_ci = #{siteCode} COLLATE utf8mb4_unicode_ci",
            " AND lss.is_deleted = b'0'",
            "LEFT JOIN product_master allocation_master",
            "  ON allocation_master.logical_store_id = ls.id",
            " AND allocation_master.sku_parent COLLATE utf8mb4_unicode_ci = allocation.sku_parent COLLATE utf8mb4_unicode_ci",
            " AND allocation_master.is_deleted = b'0'",
            "WHERE allocation.owner_user_id = #{ownerUserId}",
            "  AND allocation.status = 'active'",
            "  AND allocation.is_deleted = b'0'",
            "  AND (COALESCE(allocation.target_site_code, '*') COLLATE utf8mb4_unicode_ci = #{siteCode} COLLATE utf8mb4_unicode_ci",
            "       OR COALESCE(allocation.target_site_code, '*') = '*')",
            "  AND NOT EXISTS (",
            "    SELECT 1",
            "    FROM procurement_ali1688_sku_purchase_batch_source existing_source",
            "    JOIN procurement_ali1688_sku_purchase_batch existing_batch",
            "      ON existing_batch.owner_user_id = existing_source.owner_user_id",
            "     AND existing_batch.id = existing_source.batch_id",
            "     AND existing_batch.status = 'active'",
            "     AND existing_batch.is_deleted = b'0'",
            "    WHERE existing_source.owner_user_id = allocation.owner_user_id",
            "      AND existing_source.order_id = allocation.order_id",
            "      AND existing_source.status = 'active'",
            "      AND existing_source.is_deleted = b'0'",
            "      AND existing_batch.target_store_code COLLATE utf8mb4_unicode_ci = allocation.target_store_code COLLATE utf8mb4_unicode_ci",
            "      AND existing_batch.sku_parent COLLATE utf8mb4_unicode_ci = allocation.sku_parent COLLATE utf8mb4_unicode_ci",
            "      AND (existing_batch.target_site_code COLLATE utf8mb4_unicode_ci = COALESCE(allocation.target_site_code, '*') COLLATE utf8mb4_unicode_ci",
            "           OR existing_batch.target_site_code = '*')",
            "  )",
            "GROUP BY allocation.order_id, allocation.assignment_id, allocation.item_id,",
            "         allocation.target_site_code, lss.store_code, lss.site, allocation.sku_parent,",
            "         allocation.partner_sku, allocation.psku_code, allocation_header.provider_order_no,",
            "         allocation.product_title, allocation.product_image_url,",
            "         allocation_master.title_cache, allocation_master.cover_image_url, allocation_header.order_time",
            "HAVING SUM(CASE WHEN allocation.sku_quantity > 0 THEN allocation.sku_quantity ELSE 0 END) > 0",
            "UNION ALL",
            "SELECT CONCAT('ALI1688_PRODUCT_LINK:', link.order_id, ':', link.assignment_id, ':',",
            "              COALESCE(NULLIF(link.partner_sku, ''), NULLIF(link.psku_code, ''), link.sku_parent)) AS source_id,",
            "       NULL AS batch_id, 'ALI1688_PRODUCT_LINK' AS source_type,",
            "       lss.store_code AS store_code, lss.site AS site_code,",
            "       link.sku_parent AS sku_parent,",
            "       link.partner_sku AS partner_sku, link.psku_code AS psku_code,",
            "       COALESCE(NULLIF(link.product_title, ''), NULLIF(link_master.title_cache, '')) AS product_title,",
            "       COALESCE(NULLIF(link_master.cover_image_url, ''), NULLIF(link.product_image_url, '')) AS product_image_url,",
            "       CONCAT('1688 product link ', link_header.provider_order_no, ' ',",
            "              MAX(CASE",
            "                    WHEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)) > 0",
            "                     AND COALESCE(",
            "                           NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                           NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                         ) > 0",
            "                    THEN 'paid_amount_allocated'",
            "                    ELSE 'item_amount_allocated'",
            "                  END)) AS batch_label,",
            "       COALESCE(link_header.order_time, MIN(link.gmt_create)) AS purchase_batch_time,",
            "       SUM(assignment.assigned_quantity) AS purchase_quantity,",
            "       SUM(CASE",
            "             WHEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)) > 0",
            "              AND COALESCE(",
            "                    NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                    NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                  ) > 0",
            "             THEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  * CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  / COALESCE(",
            "                      NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                      NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                    )",
            "                  * assignment.assigned_quantity / link_item.quantity",
            "             ELSE CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  * assignment.assigned_quantity / link_item.quantity",
            "           END) AS purchase_cost_cny,",
            "       SUM(CASE",
            "             WHEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)) > 0",
            "              AND COALESCE(",
            "                    NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                    NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                  ) > 0",
            "             THEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  * CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  / COALESCE(",
            "                      NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                      NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                    )",
            "                  * assignment.assigned_quantity / link_item.quantity",
            "             ELSE CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  * assignment.assigned_quantity / link_item.quantity",
            "           END) / NULLIF(SUM(assignment.assigned_quantity), 0) AS purchase_unit_cost_cny,",
            "       link_header.provider_order_no AS provider_order_no,",
            "       link.item_id AS item_id, link.assignment_id AS assignment_id,",
            "       link_item.title AS source_title, link_item.sku_text AS source_sku_text,",
            "       link_item.model_text AS source_model_text, link_item.image_url AS source_image_url,",
            "       link_item.quantity AS source_quantity, link_item.unit AS source_unit,",
            "       CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)) AS source_amount,",
            "       SUM(CASE",
            "             WHEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)) > 0",
            "              AND COALESCE(",
            "                    NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                    NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                  ) > 0",
            "             THEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  * CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  / COALESCE(",
            "                      NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                      NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                    )",
            "                  * assignment.assigned_quantity / link_item.quantity",
            "             ELSE CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  * assignment.assigned_quantity / link_item.quantity",
            "           END) AS paid_amount,",
            "       SUM(assignment.assigned_quantity) AS assignment_quantity,",
            "       NULL AS consumed_source_quantity, NULL AS sku_quantity, NULL AS pack_size,",
            "       MAX(CASE",
            "             WHEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)) > 0",
            "              AND COALESCE(",
            "                    NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                    NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                  ) > 0",
            "             THEN 'paid_amount_allocated'",
            "             ELSE 'item_amount_allocated'",
            "           END) AS allocation_basis,",
            "       '按订单行实付金额分摊' AS evidence_text,",
            "       link.assignment_id AS source_sequence",
            "FROM procurement_ali1688_order_item_product_link link",
            "JOIN procurement_ali1688_order_item_assignment assignment",
            "  ON assignment.id = link.assignment_id",
            " AND assignment.owner_user_id = link.owner_user_id",
            " AND assignment.order_id = link.order_id",
            " AND assignment.item_id = link.item_id",
            " AND assignment.target_type = 'STORE_SITE'",
            " AND assignment.status = 'active'",
            " AND assignment.is_deleted = b'0'",
            "JOIN procurement_ali1688_order_item link_item",
            "  ON link_item.id = link.item_id",
            " AND link_item.order_id = link.order_id",
            " AND link_item.is_deleted = b'0'",
            "JOIN procurement_ali1688_order_header link_header",
            "  ON link_header.owner_user_id = link.owner_user_id",
            " AND link_header.id = link.order_id",
            " AND link_header.is_deleted = b'0'",
            "LEFT JOIN (",
            "  SELECT item_total.order_id,",
            "         SUM(CAST(NULLIF(REPLACE(REPLACE(REPLACE(item_total.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))) AS order_item_amount_total",
            "  FROM procurement_ali1688_order_item item_total",
            "  WHERE item_total.is_deleted = b'0'",
            "  GROUP BY item_total.order_id",
            ") item_amount_total",
            "  ON item_amount_total.order_id = link_header.id",
            "JOIN logical_store ls",
            "  ON ls.owner_user_id = link.owner_user_id",
            " AND link.target_store_code COLLATE utf8mb4_unicode_ci = ls.project_code COLLATE utf8mb4_unicode_ci",
            " AND ls.is_deleted = b'0'",
            "JOIN logical_store_site lss",
            "  ON lss.logical_store_id = ls.id",
            " AND lss.store_code COLLATE utf8mb4_unicode_ci = #{storeCode} COLLATE utf8mb4_unicode_ci",
            " AND lss.site COLLATE utf8mb4_unicode_ci = #{siteCode} COLLATE utf8mb4_unicode_ci",
            " AND lss.is_deleted = b'0'",
            "LEFT JOIN product_master link_master",
            "  ON link_master.logical_store_id = ls.id",
            " AND link_master.sku_parent COLLATE utf8mb4_unicode_ci = link.sku_parent COLLATE utf8mb4_unicode_ci",
            " AND link_master.is_deleted = b'0'",
            "WHERE link.owner_user_id = #{ownerUserId}",
            "  AND link.status = 'active'",
            "  AND link.is_deleted = b'0'",
            "  AND assignment.assigned_quantity > 0",
            "  AND link_item.quantity > 0",
            "  AND CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)) > 0",
            "  AND (COALESCE(link.target_site_code, '*') COLLATE utf8mb4_unicode_ci = #{siteCode} COLLATE utf8mb4_unicode_ci",
            "       OR COALESCE(link.target_site_code, '*') = '*')",
            "  AND NOT EXISTS (",
            "    SELECT 1",
            "    FROM procurement_ali1688_sku_purchase_batch_source existing_source",
            "    JOIN procurement_ali1688_sku_purchase_batch existing_batch",
            "      ON existing_batch.owner_user_id = existing_source.owner_user_id",
            "     AND existing_batch.id = existing_source.batch_id",
            "     AND existing_batch.status = 'active'",
            "     AND existing_batch.is_deleted = b'0'",
            "    WHERE existing_source.owner_user_id = link.owner_user_id",
            "      AND existing_source.order_id = link.order_id",
            "      AND existing_source.item_id = link.item_id",
            "      AND existing_source.assignment_id = link.assignment_id",
            "      AND existing_source.status = 'active'",
            "      AND existing_source.is_deleted = b'0'",
            "      AND existing_batch.target_store_code COLLATE utf8mb4_unicode_ci = link.target_store_code COLLATE utf8mb4_unicode_ci",
            "      AND existing_batch.sku_parent COLLATE utf8mb4_unicode_ci = link.sku_parent COLLATE utf8mb4_unicode_ci",
            "      AND (existing_batch.target_site_code COLLATE utf8mb4_unicode_ci = COALESCE(link.target_site_code, '*') COLLATE utf8mb4_unicode_ci",
            "           OR existing_batch.target_site_code = '*')",
            "  )",
            "  AND NOT EXISTS (",
            "    SELECT 1",
            "    FROM procurement_ali1688_order_sku_allocation existing_allocation",
            "    WHERE existing_allocation.owner_user_id = link.owner_user_id",
            "      AND existing_allocation.order_id = link.order_id",
            "      AND (existing_allocation.assignment_id = link.assignment_id OR existing_allocation.item_id = link.item_id)",
            "      AND existing_allocation.target_store_code COLLATE utf8mb4_unicode_ci = link.target_store_code COLLATE utf8mb4_unicode_ci",
            "      AND COALESCE(existing_allocation.target_site_code, '*') COLLATE utf8mb4_unicode_ci = COALESCE(link.target_site_code, '*') COLLATE utf8mb4_unicode_ci",
            "      AND existing_allocation.sku_parent COLLATE utf8mb4_unicode_ci = link.sku_parent COLLATE utf8mb4_unicode_ci",
            "      AND COALESCE(existing_allocation.partner_sku, '') COLLATE utf8mb4_unicode_ci = COALESCE(link.partner_sku, '') COLLATE utf8mb4_unicode_ci",
            "      AND COALESCE(existing_allocation.psku_code, '') COLLATE utf8mb4_unicode_ci = COALESCE(link.psku_code, '') COLLATE utf8mb4_unicode_ci",
            "      AND existing_allocation.status = 'active'",
            "      AND existing_allocation.is_deleted = b'0'",
            "  )",
            "GROUP BY link.order_id, link.assignment_id, link.item_id, link.target_site_code,",
            "         lss.store_code, lss.site, link.sku_parent, link.partner_sku, link.psku_code,",
            "         link.product_title, link.product_image_url, link_master.title_cache, link_master.cover_image_url,",
            "         link_header.provider_order_no, link_header.order_time,",
            "         link_item.title, link_item.sku_text, link_item.model_text, link_item.image_url,",
            "         link_item.quantity, link_item.unit, link_item.amount_text",
            "HAVING SUM(assignment.assigned_quantity) > 0",
            "   AND SUM(CASE",
            "             WHEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)) > 0",
            "              AND COALESCE(",
            "                    NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                    NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                  ) > 0",
            "             THEN CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.paid_amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  * CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  / COALESCE(",
            "                      NULLIF(item_amount_total.order_item_amount_total, 0),",
            "                      NULLIF(CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_header.goods_total_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4)), 0)",
            "                    )",
            "                  * assignment.assigned_quantity / link_item.quantity",
            "             ELSE CAST(NULLIF(REPLACE(REPLACE(REPLACE(link_item.amount_text, '¥', ''), ',', ''), ' ', ''), '') AS DECIMAL(18, 4))",
            "                  * assignment.assigned_quantity / link_item.quantity",
            "           END) > 0",
            ") purchase",
            "ORDER BY purchase.purchase_batch_time ASC, purchase.source_sequence ASC, purchase.source_id ASC"
    })
    List<PurchaseCostBatchRow> listPurchaseCostBatches(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode
    );

    @Select({
            "WITH sku_headhaul_components AS (",
            "  SELECT CONCAT('IN_TRANSIT_HEADHAUL_SKU_AVERAGE:', component.target_site_code, ':', component.psku) COLLATE utf8mb4_unicode_ci AS source_id,",
            "         NULL AS in_transit_batch_id, component.psku COLLATE utf8mb4_unicode_ci AS partner_sku,",
            "         component.target_site_code COLLATE utf8mb4_unicode_ci AS site_code,",
            "         GROUP_CONCAT(DISTINCT bill.bill_no ORDER BY bill.bill_no SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS bill_no,",
            "         GROUP_CONCAT(DISTINCT COALESCE(NULLIF(freight_batch.batch_reference_no, ''), CAST(component.batch_id AS CHAR)) ORDER BY component.batch_id SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS batch_reference_no,",
            "         GROUP_CONCAT(DISTINCT bill.transport_mode ORDER BY bill.transport_mode SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS transport_mode,",
            "         GROUP_CONCAT(DISTINCT bill.destination_code ORDER BY bill.destination_code SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS destination_code,",
            "         SUM(component.quantity) AS freight_quantity, SUM(component.cny_amount) AS headhaul_cost_cny,",
            "         MAX(COALESCE(bill.business_occurred_at, bill.bill_date, bill.gmt_create)) AS freight_occurred_at,",
            "         'actual_component_quantity' COLLATE utf8mb4_unicode_ci AS allocation_basis",
            "  FROM in_transit_freight_actual_component component",
            "  JOIN in_transit_freight_actual_bill bill",
            "    ON bill.owner_user_id = component.owner_user_id",
            "   AND bill.id = component.actual_bill_id",
            "   AND bill.is_deleted = b'0'",
            "  LEFT JOIN in_transit_batch freight_batch",
            "    ON freight_batch.owner_user_id = component.owner_user_id",
            "   AND freight_batch.id = component.batch_id",
            "   AND freight_batch.is_deleted = b'0'",
            "  WHERE component.owner_user_id = #{ownerUserId}",
            "    AND component.psku IS NOT NULL",
            "    AND component.psku <> ''",
            "    AND component.target_site_code COLLATE utf8mb4_unicode_ci = #{siteCode} COLLATE utf8mb4_unicode_ci",
            "    AND component.standard_fee_type = 'HEADHAUL'",
            "    AND component.is_deleted = b'0'",
            "  GROUP BY component.psku, component.target_site_code",
            "  HAVING SUM(component.quantity) > 0",
            "), batch_headhaul_components AS (",
            "  SELECT batch_headhaul.owner_user_id, batch_headhaul.batch_id,",
            "         GROUP_CONCAT(DISTINCT bill.bill_no ORDER BY bill.bill_no SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS bill_no,",
            "         GROUP_CONCAT(DISTINCT COALESCE(NULLIF(freight_batch.batch_reference_no, ''), CAST(batch_headhaul.batch_id AS CHAR)) ORDER BY batch_headhaul.batch_id SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS batch_reference_no,",
            "         GROUP_CONCAT(DISTINCT bill.transport_mode ORDER BY bill.transport_mode SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS transport_mode,",
            "         GROUP_CONCAT(DISTINCT bill.destination_code ORDER BY bill.destination_code SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS destination_code,",
            "         SUM(batch_headhaul.cny_amount) AS batch_headhaul_cost_cny,",
            "         MAX(COALESCE(bill.business_occurred_at, bill.bill_date, bill.gmt_create)) AS freight_occurred_at",
            "  FROM in_transit_freight_actual_component batch_headhaul",
            "  JOIN in_transit_freight_actual_bill bill",
            "    ON bill.owner_user_id = batch_headhaul.owner_user_id",
            "   AND bill.id = batch_headhaul.actual_bill_id",
            "   AND bill.is_deleted = b'0'",
            "  LEFT JOIN in_transit_batch freight_batch",
            "    ON freight_batch.owner_user_id = batch_headhaul.owner_user_id",
            "   AND freight_batch.id = batch_headhaul.batch_id",
            "   AND freight_batch.is_deleted = b'0'",
            "  WHERE batch_headhaul.owner_user_id = #{ownerUserId}",
            "    AND (batch_headhaul.psku IS NULL OR batch_headhaul.psku = '')",
            "    AND batch_headhaul.standard_fee_type = 'HEADHAUL'",
            "    AND batch_headhaul.cny_amount IS NOT NULL",
            "    AND batch_headhaul.is_deleted = b'0'",
            "  GROUP BY batch_headhaul.owner_user_id, batch_headhaul.batch_id",
            "), batch_totals AS (",
            "  SELECT freight_line.owner_user_id, freight_line.batch_id, freight_line.site_code,",
            "         SUM(freight_line.shipped_quantity) AS batch_shipped_quantity",
            "  FROM in_transit_goods_line freight_line",
            "  WHERE freight_line.owner_user_id = #{ownerUserId}",
            "    AND freight_line.site_code COLLATE utf8mb4_unicode_ci = #{siteCode} COLLATE utf8mb4_unicode_ci",
            "    AND freight_line.psku IS NOT NULL",
            "    AND freight_line.psku <> ''",
            "    AND freight_line.shipped_quantity > 0",
            "    AND freight_line.is_deleted = b'0'",
            "  GROUP BY freight_line.owner_user_id, freight_line.batch_id, freight_line.site_code",
            "), batch_headhaul_allocations AS (",
            "  SELECT CONCAT('IN_TRANSIT_HEADHAUL_BATCH_PRORATED:', batch_totals.site_code, ':', freight_line.psku) COLLATE utf8mb4_unicode_ci AS source_id,",
            "         NULL AS in_transit_batch_id, freight_line.psku COLLATE utf8mb4_unicode_ci AS partner_sku, batch_totals.site_code COLLATE utf8mb4_unicode_ci AS site_code,",
            "         GROUP_CONCAT(DISTINCT batch_headhaul.bill_no ORDER BY batch_headhaul.bill_no SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS bill_no,",
            "         GROUP_CONCAT(DISTINCT batch_headhaul.batch_reference_no ORDER BY batch_headhaul.batch_reference_no SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS batch_reference_no,",
            "         GROUP_CONCAT(DISTINCT batch_headhaul.transport_mode ORDER BY batch_headhaul.transport_mode SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS transport_mode,",
            "         GROUP_CONCAT(DISTINCT batch_headhaul.destination_code ORDER BY batch_headhaul.destination_code SEPARATOR ',') COLLATE utf8mb4_unicode_ci AS destination_code,",
            "         SUM(freight_line.shipped_quantity) AS freight_quantity,",
            "         SUM(batch_headhaul.batch_headhaul_cost_cny * freight_line.shipped_quantity / NULLIF(batch_totals.batch_shipped_quantity, 0)) AS headhaul_cost_cny,",
            "         MAX(batch_headhaul.freight_occurred_at) AS freight_occurred_at,",
            "         'batch_headhaul_prorated_by_shipped_quantity' COLLATE utf8mb4_unicode_ci AS allocation_basis",
            "  FROM batch_headhaul_components batch_headhaul",
            "  JOIN batch_totals",
            "    ON batch_totals.owner_user_id = batch_headhaul.owner_user_id",
            "   AND batch_totals.batch_id = batch_headhaul.batch_id",
            "  JOIN in_transit_goods_line freight_line",
            "    ON freight_line.owner_user_id = batch_headhaul.owner_user_id",
            "   AND freight_line.batch_id = batch_headhaul.batch_id",
            "   AND freight_line.site_code COLLATE utf8mb4_unicode_ci = batch_totals.site_code COLLATE utf8mb4_unicode_ci",
            "   AND freight_line.psku IS NOT NULL",
            "   AND freight_line.psku <> ''",
            "   AND freight_line.shipped_quantity > 0",
            "   AND freight_line.is_deleted = b'0'",
            "  GROUP BY freight_line.psku, batch_totals.site_code",
            "), headhaul_sources AS (",
            "  SELECT * FROM sku_headhaul_components",
            "  UNION ALL",
            "  SELECT * FROM batch_headhaul_allocations",
            ")",
            "SELECT CONCAT('IN_TRANSIT_HEADHAUL_SKU_AVERAGE:', site_code, ':', partner_sku) AS source_id,",
            "       NULL AS in_transit_batch_id, partner_sku, site_code,",
            "       GROUP_CONCAT(DISTINCT bill_no ORDER BY bill_no SEPARATOR ',') AS bill_no,",
            "       GROUP_CONCAT(DISTINCT batch_reference_no ORDER BY batch_reference_no SEPARATOR ',') AS batch_reference_no,",
            "       GROUP_CONCAT(DISTINCT transport_mode ORDER BY transport_mode SEPARATOR ',') AS transport_mode,",
            "       GROUP_CONCAT(DISTINCT destination_code ORDER BY destination_code SEPARATOR ',') AS destination_code,",
            "       SUM(freight_quantity) AS freight_quantity,",
            "       SUM(headhaul_cost_cny) AS headhaul_cost_cny,",
            "       SUM(headhaul_cost_cny) / NULLIF(SUM(freight_quantity), 0) AS headhaul_unit_cost_cny,",
            "       MAX(freight_occurred_at) AS freight_occurred_at,",
            "       GROUP_CONCAT(DISTINCT allocation_basis ORDER BY allocation_basis SEPARATOR ',') AS allocation_basis,",
            "       'actual HEADHAUL components aggregated by psku + site; batch-level HEADHAUL bills are prorated by in-transit shipped quantity; purchase batch is not linked to in-transit batch' AS evidence_text",
            "FROM headhaul_sources",
            "GROUP BY partner_sku, site_code",
            "HAVING SUM(freight_quantity) > 0",
            "ORDER BY freight_occurred_at ASC, partner_sku ASC"
    })
    List<HeadhaulCostBatchRow> listHeadhaulCostBatches(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode
    );
}
