package com.nuono.next.infrastructure.mapper;

import com.nuono.next.productlisting.ProductListingTaskRecord;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ProductListingAttemptGuardMapper {

    @Select({
            "SELECT",
            "  real_run.id, real_run.draft_id, real_run.owner_user_id, real_run.store_code,",
            "  real_run.task_no, real_run.mode, real_run.status, real_run.source_task_id,",
            "  real_run.input_snapshot_json, real_run.validation_json, real_run.confirmation_json,",
            "  real_run.noon_result_json, real_run.failure_category, real_run.failure_code,",
            "  real_run.failure_message, real_run.submitted_by, real_run.submitted_at,",
            "  real_run.started_at, real_run.completed_at, real_run.gmt_create, real_run.gmt_updated",
            "FROM product_listing_task real_run",
            "LEFT JOIN product_listing_task source_dry_run",
            "  ON source_dry_run.id = real_run.source_task_id",
            " AND source_dry_run.owner_user_id = real_run.owner_user_id",
            " AND source_dry_run.draft_id = real_run.draft_id",
            " AND source_dry_run.mode = 'DRY_RUN'",
            "WHERE real_run.owner_user_id = #{ownerUserId}",
            "  AND real_run.draft_id = #{draftId}",
            "  AND real_run.mode = 'REAL_RUN'",
            "  AND NOT (",
            "    COALESCE(source_dry_run.status, '') = 'superseded'",
            "    AND real_run.status IN ('failed', 'rejected')",
            "    AND (",
            "      real_run.noon_result_json IS NULL",
            "      OR TRIM(real_run.noon_result_json) = ''",
            "      OR CASE",
            "        WHEN JSON_VALID(real_run.noon_result_json) THEN",
            "          JSON_TYPE(JSON_EXTRACT(real_run.noon_result_json, '$')) = 'OBJECT'",
            "          AND (",
            "            JSON_EXTRACT(real_run.noon_result_json, '$.success') IS NULL",
            "            OR JSON_TYPE(JSON_EXTRACT(real_run.noon_result_json, '$.success')) = 'BOOLEAN'",
            "          )",
            "          AND (",
            "            JSON_EXTRACT(real_run.noon_result_json, '$.steps') IS NULL",
            "            OR JSON_TYPE(JSON_EXTRACT(real_run.noon_result_json, '$.steps')) = 'ARRAY'",
            "          )",
            "        ELSE FALSE",
            "      END",
            "    )",
            "    AND COALESCE(CASE",
            "          WHEN JSON_VALID(real_run.noon_result_json)",
            "          THEN JSON_UNQUOTE(JSON_EXTRACT(",
            "               real_run.noon_result_json, '$.success'))",
            "          ELSE 'false'",
            "        END, 'false') <> 'true'",
            "    AND NOT EXISTS (",
            "      SELECT 1",
            "      FROM JSON_TABLE(",
            "        CASE",
            "          WHEN JSON_VALID(real_run.noon_result_json)",
            "          THEN real_run.noon_result_json",
            "          ELSE JSON_OBJECT('steps', JSON_ARRAY())",
            "        END,",
            "        '$.steps[*]' COLUMNS (",
            "          step_key VARCHAR(64) PATH '$.stepKey',",
            "          step_status VARCHAR(32) PATH '$.status',",
            "          external_reference VARCHAR(2048) PATH '$.externalReference'",
            "        )",
            "      ) AS write_evidence",
            "      WHERE LOWER(write_evidence.step_key)",
            "        IN ('create_product', 'resolve_create_reference')",
            "        AND LOWER(write_evidence.step_status) = 'succeeded'",
            "        AND REGEXP_LIKE(write_evidence.external_reference,",
            "          '(^|;)[[:space:]]*skuparent[[:space:]]*=[[:space:]]*[^;[:space:]]',",
            "          'i')",
            "        AND REGEXP_LIKE(write_evidence.external_reference,",
            "          '(^|;)[[:space:]]*pskucode[[:space:]]*=[[:space:]]*[^;[:space:]]',",
            "          'i')",
            "    )",
            "    AND COALESCE(real_run.failure_code, '')",
            "        NOT IN ('noon_create_outcome_unknown', 'real_run_interrupted')",
            "    AND (",
            "      real_run.status = 'rejected'",
            "      OR (",
            "        real_run.status = 'failed'",
            "        AND COALESCE(real_run.failure_code, '') NOT IN (",
            "          'noon_write_exception', 'noon_write_outcome_unknown'",
            "        )",
            "        AND (",
            "          LOWER(COALESCE(real_run.failure_category, '')) IN ('validation', 'guard')",
            "          OR LOWER(COALESCE(real_run.failure_code, '')) IN (",
            "            'noon_auth_required',",
            "            'noon_pre_create_failed',",
            "            'noon_create_rejected',",
            "            'noon_create_not_found_confirmed',",
            "            'noon_warehouse_stock_not_supported', 'real_run_interrupted_before_write',",
            "            'partner_sku_already_exists',",
            "            'barcode_already_exists'",
            "          )",
            "        )",
            "      )",
            "    )",
            "  )",
            "ORDER BY CASE",
            "  WHEN real_run.status IN ('submitted', 'running', 'written_verify_failed') THEN 0",
            "  WHEN real_run.status = 'succeeded' THEN 1",
            "  ELSE 2",
            "END, real_run.submitted_at DESC, real_run.id DESC",
            "LIMIT 1"
    })
    ProductListingTaskRecord selectCurrentRealRunTaskByDraftId(
            @Param("ownerUserId") Long ownerUserId,
            @Param("draftId") Long draftId
    );
}
