package com.nuono.next.infrastructure.mapper;

import com.nuono.next.productanalysis.ProductLifecycleAnalysisQuery;
import com.nuono.next.productanalysis.ProductLifecycleAnalysisRowView;
import com.nuono.next.productanalysis.ProductLifecycleAnalysisSummaryView;
import java.time.LocalDate;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ProductLifecycleAnalysisMapper {

    @Select({
            "SELECT ls.owner_user_id",
            "FROM logical_store_site lss",
            "JOIN logical_store ls ON ls.id = lss.logical_store_id AND ls.is_deleted = b'0'",
            "WHERE lss.store_code = #{storeCode}",
            "  AND lss.site = #{siteCode}",
            "  AND lss.is_deleted = b'0'",
            "  AND ls.owner_user_id IS NOT NULL",
            "ORDER BY ls.id ASC",
            "LIMIT 1"
    })
    Long selectDataOwnerUserId(
            @Param("storeCode") String storeCode,
            @Param("siteCode") String siteCode
    );

    @ConstructorArgs({
            @Arg(column = "storeCode", javaType = String.class),
            @Arg(column = "siteCode", javaType = String.class),
            @Arg(column = "totalProductCount", javaType = int.class),
            @Arg(column = "readyProductCount", javaType = int.class),
            @Arg(column = "missingParameterProductCount", javaType = int.class)
    })
    @Select({
            "SELECT",
            "  #{query.storeCode} AS storeCode,",
            "  #{query.siteCode} AS siteCode,",
            "  COUNT(*) AS totalProductCount,",
            "  COALESCE(SUM(CASE WHEN pls.quality_state = 'ready' THEN 1 ELSE 0 END), 0) AS readyProductCount,",
            "  COALESCE(SUM(CASE WHEN pls.quality_state <> 'ready' THEN 1 ELSE 0 END), 0) AS missingParameterProductCount",
            "FROM product_lifecycle_current_state pls",
            "WHERE pls.owner_user_id = #{query.ownerUserId}",
            "  AND pls.store_code = #{query.storeCode}",
            "  AND pls.site_code = #{query.siteCode}"
    })
    ProductLifecycleAnalysisSummaryView selectSummary(@Param("query") ProductLifecycleAnalysisQuery query);

    @ConstructorArgs({
            @Arg(column = "partnerSku", javaType = String.class),
            @Arg(column = "sku", javaType = String.class),
            @Arg(column = "productTitle", javaType = String.class),
            @Arg(column = "imageUrl", javaType = String.class),
            @Arg(column = "brand", javaType = String.class),
            @Arg(column = "productFulltype", javaType = String.class),
            @Arg(column = "lifecycleCode", javaType = String.class),
            @Arg(column = "lifecycleLabel", javaType = String.class),
            @Arg(column = "analysisState", javaType = String.class),
            @Arg(column = "analysisStateLabel", javaType = String.class),
            @Arg(column = "analysisDate", javaType = LocalDate.class),
            @Arg(column = "listingDate", javaType = LocalDate.class),
            @Arg(column = "currentStageStartDate", javaType = LocalDate.class),
            @Arg(column = "listingDateSource", javaType = String.class),
            @Arg(column = "ruleVersion", javaType = String.class),
            @Arg(column = "currentStock", javaType = Integer.class),
            @Arg(column = "recent30DaySales", javaType = Integer.class),
            @Arg(column = "earliestFactDate", javaType = LocalDate.class),
            @Arg(column = "latestFactDate", javaType = LocalDate.class)
    })
    @Select({
            "SELECT",
            "  pls.partner_sku AS partnerSku,",
            "  pls.sku AS sku,",
            "  COALESCE((",
            "    SELECT NULLIF(pm_dim.title_cache, '')",
            "    FROM product_site_offer pso_dim",
            "    JOIN product_variant pv_dim ON pv_dim.id = pso_dim.variant_id AND pv_dim.is_deleted = b'0'",
            "    JOIN product_master pm_dim ON pm_dim.id = pv_dim.product_master_id AND pm_dim.is_deleted = b'0'",
            "    JOIN logical_store ls_dim ON ls_dim.id = pm_dim.logical_store_id AND ls_dim.is_deleted = b'0'",
            "    JOIN logical_store_site lss_dim ON lss_dim.id = pso_dim.site_id",
            "      AND lss_dim.logical_store_id = ls_dim.id",
            "      AND lss_dim.is_deleted = b'0'",
            "    WHERE ls_dim.owner_user_id = pls.owner_user_id",
            "      AND lss_dim.store_code = pls.store_code",
            "      AND lss_dim.site = pls.site_code",
            "      AND pso_dim.is_deleted = b'0'",
            "      AND pv_dim.partner_sku = pls.partner_sku",
            "      AND (",
            "        pso_dim.offer_code = pls.sku",
            "        OR pso_dim.psku_code = pls.sku",
            "        OR pv_dim.child_sku = pls.sku",
            "        OR pm_dim.sku_parent = pls.sku",
            "      )",
            "    LIMIT 1",
            "  ), (",
            "    SELECT dsf.product_title",
            "    FROM daily_sales_fact dsf",
            "    WHERE dsf.owner_user_id = pls.owner_user_id",
            "      AND dsf.store_code = pls.store_code",
            "      AND dsf.site_code = pls.site_code",
            "      AND dsf.partner_sku = pls.partner_sku",
            "      AND dsf.sku = pls.sku",
            "      AND dsf.product_title IS NOT NULL",
            "      AND dsf.product_title <> ''",
            "    ORDER BY dsf.fact_date DESC, dsf.id DESC",
            "    LIMIT 1",
            "  ), pls.partner_sku) AS productTitle,",
            "  (",
            "    SELECT NULLIF(pm_dim.cover_image_url, '')",
            "    FROM product_site_offer pso_dim",
            "    JOIN product_variant pv_dim ON pv_dim.id = pso_dim.variant_id AND pv_dim.is_deleted = b'0'",
            "    JOIN product_master pm_dim ON pm_dim.id = pv_dim.product_master_id AND pm_dim.is_deleted = b'0'",
            "    JOIN logical_store ls_dim ON ls_dim.id = pm_dim.logical_store_id AND ls_dim.is_deleted = b'0'",
            "    JOIN logical_store_site lss_dim ON lss_dim.id = pso_dim.site_id",
            "      AND lss_dim.logical_store_id = ls_dim.id",
            "      AND lss_dim.is_deleted = b'0'",
            "    WHERE ls_dim.owner_user_id = pls.owner_user_id",
            "      AND lss_dim.store_code = pls.store_code",
            "      AND lss_dim.site = pls.site_code",
            "      AND pso_dim.is_deleted = b'0'",
            "      AND pv_dim.partner_sku = pls.partner_sku",
            "      AND (",
            "        pso_dim.offer_code = pls.sku",
            "        OR pso_dim.psku_code = pls.sku",
            "        OR pv_dim.child_sku = pls.sku",
            "        OR pm_dim.sku_parent = pls.sku",
            "      )",
            "    LIMIT 1",
            "  ) AS imageUrl,",
            "  (",
            "    SELECT NULLIF(pm_dim.brand_cache, '')",
            "    FROM product_site_offer pso_dim",
            "    JOIN product_variant pv_dim ON pv_dim.id = pso_dim.variant_id AND pv_dim.is_deleted = b'0'",
            "    JOIN product_master pm_dim ON pm_dim.id = pv_dim.product_master_id AND pm_dim.is_deleted = b'0'",
            "    JOIN logical_store ls_dim ON ls_dim.id = pm_dim.logical_store_id AND ls_dim.is_deleted = b'0'",
            "    JOIN logical_store_site lss_dim ON lss_dim.id = pso_dim.site_id",
            "      AND lss_dim.logical_store_id = ls_dim.id",
            "      AND lss_dim.is_deleted = b'0'",
            "    WHERE ls_dim.owner_user_id = pls.owner_user_id",
            "      AND lss_dim.store_code = pls.store_code",
            "      AND lss_dim.site = pls.site_code",
            "      AND pso_dim.is_deleted = b'0'",
            "      AND pv_dim.partner_sku = pls.partner_sku",
            "      AND (",
            "        pso_dim.offer_code = pls.sku",
            "        OR pso_dim.psku_code = pls.sku",
            "        OR pv_dim.child_sku = pls.sku",
            "        OR pm_dim.sku_parent = pls.sku",
            "      )",
            "    LIMIT 1",
            "  ) AS brand,",
            "  (",
            "    SELECT NULLIF(pm_dim.product_fulltype_cache, '')",
            "    FROM product_site_offer pso_dim",
            "    JOIN product_variant pv_dim ON pv_dim.id = pso_dim.variant_id AND pv_dim.is_deleted = b'0'",
            "    JOIN product_master pm_dim ON pm_dim.id = pv_dim.product_master_id AND pm_dim.is_deleted = b'0'",
            "    JOIN logical_store ls_dim ON ls_dim.id = pm_dim.logical_store_id AND ls_dim.is_deleted = b'0'",
            "    JOIN logical_store_site lss_dim ON lss_dim.id = pso_dim.site_id",
            "      AND lss_dim.logical_store_id = ls_dim.id",
            "      AND lss_dim.is_deleted = b'0'",
            "    WHERE ls_dim.owner_user_id = pls.owner_user_id",
            "      AND lss_dim.store_code = pls.store_code",
            "      AND lss_dim.site = pls.site_code",
            "      AND pso_dim.is_deleted = b'0'",
            "      AND pv_dim.partner_sku = pls.partner_sku",
            "      AND (",
            "        pso_dim.offer_code = pls.sku",
            "        OR pso_dim.psku_code = pls.sku",
            "        OR pv_dim.child_sku = pls.sku",
            "        OR pm_dim.sku_parent = pls.sku",
            "      )",
            "    LIMIT 1",
            "  ) AS productFulltype,",
            "  pls.lifecycle_code AS lifecycleCode,",
            "  pls.lifecycle_label AS lifecycleLabel,",
            "  pls.quality_state AS analysisState,",
            "  CASE",
            "    WHEN pls.quality_state = 'ready' THEN '可分析'",
            "    WHEN pls.quality_state = 'data_insufficient' THEN '数据不足'",
            "    WHEN pls.quality_state = 'stockout_no_previous_state' THEN '断货无前态'",
            "    ELSE pls.quality_state",
            "  END AS analysisStateLabel,",
            "  pls.analysis_date AS analysisDate,",
            "  pls.listing_date AS listingDate,",
            "  CASE",
            "    WHEN pls.lifecycle_code = 'new' THEN pls.listing_date",
            "    ELSE (",
            "      SELECT MAX(plh.analysis_date)",
            "      FROM product_lifecycle_history plh",
            "      WHERE plh.owner_user_id = pls.owner_user_id",
            "        AND plh.store_code = pls.store_code",
            "        AND plh.site_code = pls.site_code",
            "        AND plh.partner_sku = pls.partner_sku",
            "        AND plh.sku = pls.sku",
            "        AND plh.lifecycle_code = pls.lifecycle_code",
            "    )",
            "  END AS currentStageStartDate,",
            "  pls.listing_date_source AS listingDateSource,",
            "  pls.rule_version AS ruleVersion,",
            "  (",
            "    SELECT CASE",
            "      WHEN COUNT(*) = 0 THEN NULL",
            "      WHEN SUM(CASE",
            "        WHEN pso_stock.fbn_stock IS NOT NULL",
            "          OR pso_stock.supermall_stock IS NOT NULL",
            "          OR pso_stock.fbp_stock IS NOT NULL THEN 1",
            "        ELSE 0",
            "      END) = 0 THEN NULL",
            "      ELSE SUM(COALESCE(pso_stock.fbn_stock, 0)",
            "        + COALESCE(pso_stock.supermall_stock, 0)",
            "        + COALESCE(pso_stock.fbp_stock, 0))",
            "    END",
            "    FROM product_site_offer pso_stock",
            "    JOIN product_variant pv_stock ON pv_stock.id = pso_stock.variant_id AND pv_stock.is_deleted = b'0'",
            "    JOIN product_master pm_stock ON pm_stock.id = pv_stock.product_master_id AND pm_stock.is_deleted = b'0'",
            "    JOIN logical_store ls_stock ON ls_stock.id = pm_stock.logical_store_id AND ls_stock.is_deleted = b'0'",
            "    JOIN logical_store_site lss_stock ON lss_stock.id = pso_stock.site_id",
            "      AND lss_stock.logical_store_id = ls_stock.id",
            "      AND lss_stock.is_deleted = b'0'",
            "    WHERE ls_stock.owner_user_id = pls.owner_user_id",
            "      AND lss_stock.store_code = pls.store_code",
            "      AND lss_stock.site = pls.site_code",
            "      AND pso_stock.is_deleted = b'0'",
            "      AND pv_stock.partner_sku = pls.partner_sku",
            "      AND (",
            "        pso_stock.offer_code = pls.sku",
            "        OR pso_stock.psku_code = pls.sku",
            "        OR pv_stock.child_sku = pls.sku",
            "        OR pm_stock.sku_parent = pls.sku",
            "      )",
            "  ) AS currentStock,",
            "  (",
            "    SELECT COALESCE(SUM(dsf.net_units), 0)",
            "    FROM daily_sales_fact dsf",
            "    WHERE dsf.owner_user_id = pls.owner_user_id",
            "      AND dsf.store_code = pls.store_code",
            "      AND dsf.site_code = pls.site_code",
            "      AND dsf.partner_sku = pls.partner_sku",
            "      AND dsf.sku = pls.sku",
            "      AND dsf.fact_date BETWEEN DATE_SUB(pls.analysis_date, INTERVAL 29 DAY) AND pls.analysis_date",
            "  ) AS recent30DaySales,",
            "  (",
            "    SELECT MIN(dsf.fact_date)",
            "    FROM daily_sales_fact dsf",
            "    WHERE dsf.owner_user_id = pls.owner_user_id",
            "      AND dsf.store_code = pls.store_code",
            "      AND dsf.site_code = pls.site_code",
            "      AND dsf.partner_sku = pls.partner_sku",
            "      AND dsf.sku = pls.sku",
            "  ) AS earliestFactDate,",
            "  (",
            "    SELECT MAX(dsf.fact_date)",
            "    FROM daily_sales_fact dsf",
            "    WHERE dsf.owner_user_id = pls.owner_user_id",
            "      AND dsf.store_code = pls.store_code",
            "      AND dsf.site_code = pls.site_code",
            "      AND dsf.partner_sku = pls.partner_sku",
            "      AND dsf.sku = pls.sku",
            "  ) AS latestFactDate",
            "FROM product_lifecycle_current_state pls",
            "WHERE pls.owner_user_id = #{query.ownerUserId}",
            "  AND pls.store_code = #{query.storeCode}",
            "  AND pls.site_code = #{query.siteCode}",
            "ORDER BY",
            "  CASE WHEN pls.quality_state = 'ready' THEN 0 ELSE 1 END,",
            "  pls.lifecycle_code ASC,",
            "  pls.partner_sku ASC,",
            "  pls.sku ASC"
    })
    List<ProductLifecycleAnalysisRowView> selectRows(@Param("query") ProductLifecycleAnalysisQuery query);
}
