package com.nuono.next.infrastructure.mapper;

import com.nuono.next.product.ProductImageProfileSummaryRecord;
import com.nuono.next.product.ProductImageSuiteStatus;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;

public interface ProductImageProfileSummaryMapper {

    @Results(id = "productImageProfileSummaryMap", value = {
            @Result(column = "id", property = "id"),
            @Result(column = "owner_user_id", property = "ownerUserId"),
            @Result(column = "store_code", property = "storeCode"),
            @Result(column = "psku_code", property = "pskuCode"),
            @Result(column = "product_identity_key", property = "productIdentityKey"),
            @Result(column = "product_master_id", property = "productMasterId"),
            @Result(column = "product_title", property = "productTitle"),
            @Result(column = "brand", property = "brand"),
            @Result(column = "title_ar", property = "titleAr"),
            @Result(column = "title_en", property = "titleEn"),
            @Result(column = "spec_summary", property = "specSummary"),
            @Result(column = "product_fact_text", property = "productFactText"),
            @Result(column = "cover_image_url", property = "coverImageUrl"),
            @Result(column = "asset_count", property = "assetCount"),
            @Result(column = "suite_count", property = "suiteCount"),
            @Result(column = "active_suite_count", property = "activeSuiteCount"),
            @Result(column = "has_adopted_suite", property = "hasAdoptedSuite"),
            @Result(
                    column = "primary_suite_status",
                    property = "primarySuiteStatus",
                    javaType = ProductImageSuiteStatus.class
            ),
            @Result(column = "updated_at", property = "updatedAt", javaType = LocalDateTime.class)
    })
    @Select({
            "<script>",
            "SELECT",
            "  p.id, p.owner_user_id, p.store_code, p.psku_code, p.product_identity_key,",
            "  p.product_master_id, p.product_title, p.brand, p.title_ar, p.title_en,",
            "  p.spec_summary, p.product_fact_text, p.updated_at,",
            "  COALESCE((",
            "    SELECT pia.image_url",
            "    FROM product_image_profile_asset pia",
            "    WHERE pia.profile_id = p.id",
            "      AND pia.asset_status = 'ACTIVE'",
            "    ORDER BY CASE pia.image_role WHEN 'MAIN' THEN 0 WHEN 'SIZE' THEN 1 ELSE 2 END,",
            "             pia.sort_order ASC, pia.id ASC",
            "    LIMIT 1",
            "  ), (",
            "    SELECT pima.url",
            "    FROM product_image_asset pima",
            "    WHERE pima.product_master_id = p.product_master_id",
            "      AND pima.is_deleted = b'0'",
            "    ORDER BY pima.id ASC",
            "    LIMIT 1",
            "  )) AS cover_image_url,",
            "  COALESCE(pac.profile_asset_count, 0) + COALESCE(cac.current_asset_count, 0) AS asset_count,",
            "  COALESCE(sc.suite_count, 0) AS suite_count,",
            "  COALESCE(sc.active_suite_count, 0) AS active_suite_count,",
            "  COALESCE(sc.has_adopted_suite, 0) AS has_adopted_suite,",
            "  sc.primary_suite_status",
            "FROM product_image_profile p",
            "JOIN (",
            "  SELECT CAST(SUBSTRING_INDEX(GROUP_CONCAT(",
            "    p2.id ORDER BY COALESCE(ac2.asset_count, 0) DESC, p2.updated_at DESC, p2.id ASC",
            "  ), ',', 1) AS UNSIGNED) AS canonical_id",
            "  FROM product_image_profile p2",
            "  LEFT JOIN (",
            "    SELECT profile_id, COUNT(1) AS asset_count",
            "    FROM product_image_profile_asset",
            "    WHERE asset_status = 'ACTIVE'",
            "    GROUP BY profile_id",
            "  ) ac2 ON ac2.profile_id = p2.id",
            "  WHERE p2.owner_user_id = #{ownerUserId}",
            "    AND p2.deleted = b'0'",
            "    AND (",
            "      p2.store_code = #{storeCode}",
            "      OR p2.logical_store_id = (",
            "        SELECT lss.logical_store_id",
            "        FROM logical_store_site lss",
            "        JOIN logical_store ls",
            "          ON ls.id = lss.logical_store_id",
            "         AND ls.owner_user_id = #{ownerUserId}",
            "         AND ls.is_deleted = b'0'",
            "        WHERE lss.store_code = #{storeCode}",
            "          AND lss.is_deleted = b'0'",
            "        LIMIT 1",
            "      )",
            "    )",
            "<if test='keyword != null and keyword != \"\"'>",
            "    AND (",
            "      p2.psku_code LIKE CONCAT('%', #{keyword}, '%')",
            "      OR p2.product_title LIKE CONCAT('%', #{keyword}, '%')",
            "      OR p2.brand LIKE CONCAT('%', #{keyword}, '%')",
            "      OR p2.title_en LIKE CONCAT('%', #{keyword}, '%')",
            "      OR p2.title_ar LIKE CONCAT('%', #{keyword}, '%')",
            "    )",
            "</if>",
            "  GROUP BY p2.owner_user_id, p2.psku_code, p2.product_identity_key",
            ") canonical ON canonical.canonical_id = p.id",
            "LEFT JOIN (",
            "  SELECT profile_id, COUNT(1) AS profile_asset_count",
            "  FROM product_image_profile_asset",
            "  WHERE asset_status = 'ACTIVE'",
            "  GROUP BY profile_id",
            ") pac ON pac.profile_id = p.id",
            "LEFT JOIN (",
            "  SELECT product_master_id, COUNT(1) AS current_asset_count",
            "  FROM product_image_asset",
            "  WHERE is_deleted = b'0'",
            "  GROUP BY product_master_id",
            ") cac ON cac.product_master_id = p.product_master_id",
            "LEFT JOIN (",
            "  SELECT profile_id,",
            "         COUNT(1) AS suite_count,",
            "         SUM(CASE WHEN suite_status NOT IN ('HISTORICAL', 'DISCARDED')",
            "                  THEN 1 ELSE 0 END) AS active_suite_count,",
            "         MAX(CASE WHEN suite_status = 'ADOPTED' THEN 1 ELSE 0 END) AS has_adopted_suite,",
            "         SUBSTRING_INDEX(GROUP_CONCAT(",
            "           CASE WHEN suite_status NOT IN ('HISTORICAL', 'DISCARDED')",
            "                THEN CASE",
            "                  WHEN suite_status = 'PENDING_REVIEW' AND (",
            "                    SELECT COUNT(DISTINCT ready_asset.image_role)",
            "                    FROM product_image_suite_asset ready_asset",
            "                    WHERE ready_asset.suite_id = product_image_suite.id",
            "                      AND ready_asset.image_role IN (",
            "                        'MAIN', 'SIZE', 'CORE_FEATURE', 'MATERIAL_DETAIL', 'USAGE_SCENE'",
            "                      )",
            "                      AND ready_asset.image_url IS NOT NULL",
            "                      AND TRIM(ready_asset.image_url) != ''",
            "                      AND ready_asset.sha256 IS NOT NULL",
            "                      AND TRIM(ready_asset.sha256) != ''",
            "                  ) &lt; 5 THEN 'GENERATING'",
            "                  ELSE suite_status",
            "                END",
            "           END",
            "           ORDER BY CASE",
            "             WHEN suite_status = 'FAILED' THEN 1",
            "             WHEN suite_status IN ('PENDING_REVIEW', 'ADOPTED') THEN 2",
            "             WHEN suite_status = 'PUBLISHING' THEN 3",
            "             WHEN suite_status IN ('PENDING_GENERATION', 'GENERATING', 'REGENERATING') THEN 4",
            "             WHEN suite_status = 'ONLINE' THEN 5",
            "             WHEN suite_status = 'DRAFT' THEN 6",
            "             ELSE 99",
            "           END, updated_at DESC, id DESC",
            "         ), ',', 1) AS primary_suite_status",
            "  FROM product_image_suite",
            "  WHERE deleted = b'0'",
            "    AND suite_status != 'DISCARDED'",
            "  GROUP BY profile_id",
            ") sc ON sc.profile_id = p.id",
            "ORDER BY p.updated_at DESC, p.id DESC",
            "</script>"
    })
    List<ProductImageProfileSummaryRecord> selectProfileSummariesForStore(
            @Param("ownerUserId") Long ownerUserId,
            @Param("storeCode") String storeCode,
            @Param("keyword") String keyword
    );
}
