package com.nuono.next.infrastructure.mapper;

import com.nuono.next.systemreports.StoreDataReportRow;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SystemReportMapper {

    @Select({
            "<script>",
            "WITH authorized_sites AS (",
            "  SELECT",
            "    ls.owner_user_id AS ownerUserId,",
            "    ls.id AS logicalStoreId,",
            "    ls.project_code AS projectCode,",
            "    ls.project_name AS projectName,",
            "    lss.id AS siteId,",
            "    lss.store_code AS storeCode,",
            "    lss.site AS siteCode,",
            "    lss.site_status AS siteStatus",
            "  FROM logical_store_site lss",
            "  JOIN logical_store ls ON ls.id = lss.logical_store_id",
            "  WHERE COALESCE(ls.is_deleted, 0) = 0",
            "    AND COALESCE(lss.is_deleted, 0) = 0",
            "    <if test='storeCodes != null and storeCodes.size > 0'>",
            "    AND lss.store_code IN",
            "    <foreach collection='storeCodes' item='storeCode' open='(' separator=',' close=')'>",
            "      #{storeCode}",
            "    </foreach>",
            "    </if>",
            "), latest_baseline AS (",
            "  SELECT s.product_master_id, s.snapshot_json",
            "  FROM product_master_snapshot s",
            "  JOIN (",
            "    SELECT product_master_id, MAX(id) AS id",
            "    FROM product_master_snapshot",
            "    WHERE snapshot_type = 'baseline'",
            "      AND COALESCE(is_deleted, 0) = 0",
            "    GROUP BY product_master_id",
            "  ) latest ON latest.id = s.id",
            "  WHERE s.snapshot_type = 'baseline'",
            "    AND COALESCE(s.is_deleted, 0) = 0",
            "), offer_keys AS (",
            "  SELECT",
            "    site.ownerUserId,",
            "    site.logicalStoreId,",
            "    site.projectCode,",
            "    site.projectName,",
            "    site.storeCode,",
            "    site.siteCode,",
            "    site.siteStatus,",
            "    pso.id AS siteOfferId,",
            "    pm.id AS productMasterId,",
            "    pv.partner_sku AS partnerSku,",
            "    pv.child_sku AS sku,",
            "    CASE WHEN pm.logical_store_id = site.logicalStoreId THEN 0 ELSE 1 END AS crossStoreOffer,",
            "    CASE WHEN lb.product_master_id IS NULL THEN 1 ELSE 0 END AS missingBaseline,",
            "    CASE",
            "      WHEN JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.content.titleEn')) IS NULL",
            "        OR JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.content.titleEn')) = ''",
            "        OR JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.content.titleEn')) = 'null'",
            "      THEN 1 ELSE 0 END AS missingTitleEn,",
            "    CASE",
            "      WHEN JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.content.descriptionEn')) IS NULL",
            "        OR JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.content.descriptionEn')) = ''",
            "        OR JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.content.descriptionEn')) = 'null'",
            "      THEN 1 ELSE 0 END AS missingDescriptionEn,",
            "    CASE",
            "      WHEN JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.identity.brand')) IS NULL",
            "        OR JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.identity.brand')) = ''",
            "        OR JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.identity.brand')) = 'null'",
            "      THEN 1 ELSE 0 END AS missingBrand,",
            "    CASE",
            "      WHEN JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.taxonomy.productFulltype')) IS NULL",
            "        OR JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.taxonomy.productFulltype')) = ''",
            "        OR JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.taxonomy.productFulltype')) = 'null'",
            "      THEN 1 ELSE 0 END AS missingProductFulltype,",
            "    CASE",
            "      WHEN CAST(JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.content.imageCount')) AS UNSIGNED) IS NULL",
            "        OR CAST(JSON_UNQUOTE(JSON_EXTRACT(lb.snapshot_json, '$.content.imageCount')) AS UNSIGNED) = 0",
            "      THEN 1 ELSE 0 END AS missingImage",
            "  FROM authorized_sites site",
            "  JOIN product_site_offer pso ON pso.site_id = site.siteId",
            "    AND COALESCE(pso.is_deleted, 0) = 0",
            "  JOIN product_variant pv ON pv.id = pso.variant_id",
            "    AND COALESCE(pv.is_deleted, 0) = 0",
            "  JOIN product_master pm ON pm.id = pv.product_master_id",
            "    AND COALESCE(pm.is_deleted, 0) = 0",
            "  LEFT JOIN latest_baseline lb ON lb.product_master_id = pm.id",
            "), sales_keys AS (",
            "  SELECT",
            "    owner_user_id AS ownerUserId,",
            "    store_code AS storeCode,",
            "    site_code AS siteCode,",
            "    partner_sku AS partnerSku,",
            "    sku,",
            "    COUNT(*) AS factRows,",
            "    MAX(fact_date) AS latestFactDate",
            "  FROM daily_sales_fact",
            "  WHERE 1 = 1",
            "    <if test='storeCodes != null and storeCodes.size > 0'>",
            "    AND store_code IN",
            "    <foreach collection='storeCodes' item='storeCode' open='(' separator=',' close=')'>",
            "      #{storeCode}",
            "    </foreach>",
            "    </if>",
            "  GROUP BY owner_user_id, store_code, site_code, partner_sku, sku",
            "), offer_stats AS (",
            "  SELECT",
            "    ok.ownerUserId, ok.storeCode, ok.siteCode,",
            "    COUNT(*) AS siteOfferCount,",
            "    SUM(ok.crossStoreOffer) AS crossStoreOfferCount,",
            "    SUM(ok.missingBaseline) AS missingDetailBaselineCount,",
            "    SUM(ok.missingTitleEn) AS missingTitleEnCount,",
            "    SUM(ok.missingDescriptionEn) AS missingDescriptionEnCount,",
            "    SUM(ok.missingBrand) AS missingBrandCount,",
            "    SUM(ok.missingProductFulltype) AS missingProductFulltypeCount,",
            "    SUM(ok.missingImage) AS missingImageCount,",
            "    SUM(CASE WHEN sk.partnerSku IS NULL THEN 0 ELSE 1 END) AS offersWithSalesFacts,",
            "    SUM(CASE WHEN sk.partnerSku IS NULL THEN 1 ELSE 0 END) AS offersWithoutSalesFacts,",
            "    COALESCE(SUM(sk.factRows), 0) AS matchedSalesFactRows,",
            "    MAX(sk.latestFactDate) AS latestMatchedFactDate",
            "  FROM offer_keys ok",
            "  LEFT JOIN sales_keys sk",
            "    ON sk.ownerUserId = ok.ownerUserId",
            "    AND sk.storeCode = ok.storeCode",
            "    AND sk.siteCode = ok.siteCode",
            "    AND sk.partnerSku = ok.partnerSku",
            "    AND sk.sku = ok.sku",
            "  GROUP BY ok.ownerUserId, ok.storeCode, ok.siteCode",
            "), sales_stats AS (",
            "  SELECT",
            "    sk.ownerUserId, sk.storeCode, sk.siteCode,",
            "    COUNT(*) AS salesProductKeyCount,",
            "    SUM(sk.factRows) AS salesFactRows,",
            "    MAX(sk.latestFactDate) AS latestFactDate,",
            "    SUM(CASE WHEN ok.siteOfferId IS NULL THEN 1 ELSE 0 END) AS salesKeysWithoutOfferCount",
            "  FROM sales_keys sk",
            "  LEFT JOIN offer_keys ok",
            "    ON ok.ownerUserId = sk.ownerUserId",
            "    AND ok.storeCode = sk.storeCode",
            "    AND ok.siteCode = sk.siteCode",
            "    AND ok.partnerSku = sk.partnerSku",
            "    AND ok.sku = sk.sku",
            "  GROUP BY sk.ownerUserId, sk.storeCode, sk.siteCode",
            "), import_latest_time AS (",
            "  SELECT owner_user_id AS ownerUserId, store_code AS storeCode, site_code AS siteCode, MAX(imported_at) AS latestImportedAt",
            "  FROM sales_import_batch",
            "  WHERE 1 = 1",
            "    <if test='storeCodes != null and storeCodes.size > 0'>",
            "    AND store_code IN",
            "    <foreach collection='storeCodes' item='storeCode' open='(' separator=',' close=')'>",
            "      #{storeCode}",
            "    </foreach>",
            "    </if>",
            "  GROUP BY owner_user_id, store_code, site_code",
            "), import_stats AS (",
            "  SELECT",
            "    sib.owner_user_id AS ownerUserId,",
            "    sib.store_code AS storeCode,",
            "    sib.site_code AS siteCode,",
            "    COUNT(*) AS salesImportBatchCount,",
            "    MAX(CASE WHEN sib.imported_at = latest.latestImportedAt THEN sib.status ELSE NULL END) AS latestSalesImportStatus,",
            "    latest.latestImportedAt AS latestSalesImportedAt",
            "  FROM sales_import_batch sib",
            "  JOIN import_latest_time latest",
            "    ON latest.ownerUserId = sib.owner_user_id",
            "    AND latest.storeCode = sib.store_code",
            "    AND latest.siteCode = sib.site_code",
            "  GROUP BY sib.owner_user_id, sib.store_code, sib.site_code, latest.latestImportedAt",
            "), lifecycle_stats AS (",
            "  SELECT",
            "    ok.ownerUserId, ok.storeCode, ok.siteCode,",
            "    COUNT(plcs.partner_sku) AS lifecycleCurrentCount,",
            "    SUM(CASE WHEN plcs.partner_sku IS NULL THEN 1 ELSE 0 END) AS lifecycleMissingCount,",
            "    SUM(CASE WHEN plcs.lifecycle_code = 'data_insufficient' OR plcs.quality_state LIKE 'data_insufficient%' THEN 1 ELSE 0 END)",
            "      AS lifecycleDataInsufficientCount",
            "  FROM offer_keys ok",
            "  LEFT JOIN product_lifecycle_current_state plcs",
            "    ON plcs.owner_user_id = ok.ownerUserId",
            "    AND plcs.store_code = ok.storeCode",
            "    AND plcs.site_code = ok.siteCode",
            "    AND plcs.partner_sku = ok.partnerSku",
            "    AND plcs.sku = ok.sku",
            "  GROUP BY ok.ownerUserId, ok.storeCode, ok.siteCode",
            ")",
            "SELECT",
            "  site.ownerUserId,",
            "  site.logicalStoreId,",
            "  site.projectCode,",
            "  site.projectName,",
            "  site.storeCode,",
            "  site.siteCode,",
            "  site.siteStatus,",
            "  COALESCE(os.siteOfferCount, 0) AS siteOfferCount,",
            "  COALESCE(os.crossStoreOfferCount, 0) AS crossStoreOfferCount,",
            "  COALESCE(os.missingDetailBaselineCount, 0) AS missingDetailBaselineCount,",
            "  COALESCE(os.missingTitleEnCount, 0) AS missingTitleEnCount,",
            "  COALESCE(os.missingDescriptionEnCount, 0) AS missingDescriptionEnCount,",
            "  COALESCE(os.missingBrandCount, 0) AS missingBrandCount,",
            "  COALESCE(os.missingProductFulltypeCount, 0) AS missingProductFulltypeCount,",
            "  COALESCE(os.missingImageCount, 0) AS missingImageCount,",
            "  COALESCE(os.offersWithSalesFacts, 0) AS offersWithSalesFacts,",
            "  COALESCE(os.offersWithoutSalesFacts, 0) AS offersWithoutSalesFacts,",
            "  COALESCE(ss.salesProductKeyCount, 0) AS salesProductKeyCount,",
            "  COALESCE(ss.salesKeysWithoutOfferCount, 0) AS salesKeysWithoutOfferCount,",
            "  COALESCE(ss.salesFactRows, 0) AS salesFactRows,",
            "  ss.latestFactDate AS latestFactDate,",
            "  COALESCE(im.salesImportBatchCount, 0) AS salesImportBatchCount,",
            "  im.latestSalesImportStatus AS latestSalesImportStatus,",
            "  im.latestSalesImportedAt AS latestSalesImportedAt,",
            "  COALESCE(lc.lifecycleCurrentCount, 0) AS lifecycleCurrentCount,",
            "  COALESCE(lc.lifecycleMissingCount, 0) AS lifecycleMissingCount,",
            "  COALESCE(lc.lifecycleDataInsufficientCount, 0) AS lifecycleDataInsufficientCount",
            "FROM authorized_sites site",
            "LEFT JOIN offer_stats os",
            "  ON os.ownerUserId = site.ownerUserId",
            "  AND os.storeCode = site.storeCode",
            "  AND os.siteCode = site.siteCode",
            "LEFT JOIN sales_stats ss",
            "  ON ss.ownerUserId = site.ownerUserId",
            "  AND ss.storeCode = site.storeCode",
            "  AND ss.siteCode = site.siteCode",
            "LEFT JOIN import_stats im",
            "  ON im.ownerUserId = site.ownerUserId",
            "  AND im.storeCode = site.storeCode",
            "  AND im.siteCode = site.siteCode",
            "LEFT JOIN lifecycle_stats lc",
            "  ON lc.ownerUserId = site.ownerUserId",
            "  AND lc.storeCode = site.storeCode",
            "  AND lc.siteCode = site.siteCode",
            "ORDER BY site.projectCode, site.siteCode, site.storeCode",
            "</script>"
    })
    List<StoreDataReportRow> selectStoreDataReportRows(@Param("storeCodes") List<String> storeCodes);
}
